// ─── 10 nouveaux articles Blog PRSTO — sujets CEO/DG ───────────────
// Auteurs variés, dates étalées sur 3 mois, articles longs (1500-2500 mots)
// Importé par lib/blog/data.ts

import type { BlogArticle, ContentBlock, Author } from "./data";

const newAuthors = {
  david: {
    name: "David Marchand",
    role: "Board Advisor & Executive Coach",
    avatar: "/branding/portraits/boardmanager-david/david-01.png",
    bio: "Ancien DG d'un groupe industriel de 2000 personnes, David a siégé à 15 conseils d'administration. Il accompagne aujourd'hui les dirigeants dans leurs transitions C-level et leurs stratégies de Comex.",
  },
  catherine: {
    name: "Catherine Lefort",
    role: "Headhunter Senior, ex-Spencer Stuart",
    avatar: "/branding/portraits/drh-ingrid/ingrid-01.png",
    bio: "Pendant 18 ans, Catherine a mené des missions de chasse pour les plus grands groupes du CAC 40. Elle connaît les coulisses des process de recrutement de dirigeants mieux que personne.",
  },
  marc: {
    name: "Marc Vidal",
    role: "Ex-CFO devenu Executive Coach",
    avatar: "/branding/portraits/cto-john/john-01.png",
    bio: "Ancien DAF de deux licornes françaises, Marc a négocié son propre package à 7 reprises. Il forme désormais les dirigeants à la maîtrise financière et à la négociation de packages C-level.",
  },
  sophie: {
    name: "Sophie Nguyen",
    role: "VP HR, ex-L'Oréal & Danone",
    avatar: "/branding/portraits/dirmarketing-sabrina/sabrina-01.png",
    bio: "DRH de division chez L'Oréal puis Danone pendant 12 ans, Sophie a recruté et accompagné plus de 80 cadres dirigeants. Elle partage ses insights sur l'évaluation des talents C-level.",
  },
};

export const newArticles: BlogArticle[] = [
  // ─── Article 1 ──────────────────────────────────────────
  {
    slug: "plan-100-jours-nouveau-dg",
    title: "Votre plan 100 jours de DG : la méthode qui rassure le Comex",
    subtitle: "Pourquoi 60% des nouveaux dirigeants échouent dans leur première année — et comment éviter ce piège",
    excerpt: "Le plan 100 jours n'est pas un exercice de communication. C'est votre première décision stratégique visible. Voici la méthode utilisée par les DG qui réussissent leur prise de poste.",
    date: "2026-06-28",
    author: newAuthors.david,
    category: "Stratégie",
    tags: ["plan 100 jours", "DG", "Comex", "prise de poste", "onboarding"],
    readingTime: "8 min",
    featured: false,
    heroGradient: "from-[#103826] via-[#1A4A2E] to-[#0E3A29]",
    content: [
      { type: "intro", text: "Quand vous prenez un poste de DG, les 100 premiers jours sont scrutés par le Comex, le board, les managers et même les clients. Chaque mot, chaque décision, chaque réunion est interprété. Voici comment construire un plan 100 jours qui transforme cette pression en avantage." },
      { type: "h2", text: "Le piège des 100 premiers jours" },
      { type: "p", text: "Selon une étude de McKinsey, 60% des dirigeants nommés en interne et 40% de ceux recrutés de l'extérieur ne répondent pas aux attentes dans leur première année. La raison n'est pas un manque de compétences — c'est l'absence d'un plan structuré. Trop de nouveaux DG arrivent avec l'intention de 'tout comprendre avant d'agir' ou, à l'inverse, de 'tout changer immédiatement'. Les deux approches mènent à l'échec." },
      { type: "p", text: "Le DG qui dit 'je vais écouter pendant 90 jours avant de décider' perd sa crédibilité. Le Comex s'attend à ce que vous preniez des décisions visibles dès les 30 premiers jours. Le DG qui veut tout changer en 30 jours effraie l'organisation et perd la confiance des équipes historiques." },
      { type: "pullQuote", text: "Votre plan 100 jours est la première preuve de votre capacité à diriger. Pas un exercice de présentation PowerPoint.", author: "David Marchand" },
      { type: "h2", text: "Les 4 phases du plan 100 jours" },
      { type: "h3", text: "Phase 1 (J1-J30) : Diagnostiquer et signaler" },
      { type: "p", text: "Les 30 premiers jours servent à diagnostiquer en profondeur ET à envoyer des signaux forts. Vous ne pouvez pas tout comprendre, mais vous pouvez poser les bonnes questions, rencontrer les bonnes personnes et prendre 2-3 décisions symboliques qui montrent votre cap." },
      { type: "p", text: "Concrètement : rencontrez chaque membre du Comex individuellement (1h chacun minimum), visitez les sites opérationnels (pas seulement le siège), analysez les 3 derniers boards, et identifiez les 3 problèmes les plus urgents. Prenez UNE décision visible dans les 30 jours — par exemple restructurer une fonction défaillante ou lancer un audit stratégique." },
      { type: "h3", text: "Phase 2 (J31-J60) : Prioriser et aligner" },
      { type: "p", text: "Vous avez maintenant une vision claire des problèmes. C'est le moment de prioriser. Un DG qui lance 10 initiatives en même temps perd ses équipes. Choisissez 3 priorités maximum, communiquez-les clairement au Comex et à l'organisation entière, et alignez vos ressources sur ces 3 axes." },
      { type: "p", text: "La règle d'or : si vous ne pouvez pas expliquer vos priorités en une phrase, vous n'avez pas fini de les formuler. 'Croissance, rentabilité, talents' est trop générique. 'Doubler le chiffre d'affaires international en 18 mois en restructurant la force de vente EMEA' est une priorité." },
      { type: "h3", text: "Phase 3 (J61-J90) : Exécuter et mesurer" },
      { type: "p", text: "C'est la phase d'exécution visible. Vos 3 priorités doivent générer des résultats mesurables. Mettez en place des KPIs hebdomadaires, communiquez les progrès au Comex toutes les 2 semaines, et n'hésitez pas à ajuster si une initiative ne produit pas les résultats attendus." },
      { type: "p", text: "Le plus gros risque à ce stade est de tomber dans le micro-management. Votre rôle n'est pas de faire le travail, c'est de débloquer les obstacles. Si vous êtes dans l'opérationnel à J75, vous avez échoué dans votre rôle de DG." },
      { type: "h3", text: "Phase 4 (J91-J100) : Consolidation et vision" },
      { type: "p", text: "Les 10 derniers jours servent à consolider les acquis, présenter les premiers résultats au board, et poser la vision pour les 12 prochains mois. C'est aussi le moment d'évaluer votre équipe : qui est aligné, qui ne l'est pas, qui doit partir, qui doit être promu." },
      { type: "h2", text: "Les 5 erreurs fatales à éviter" },
      { type: "ul", items: [
        "Critiquer publiquement votre prédécesseur — même s'il a laissé des problèmes, vous êtes jugé sur l'avenir, pas le passé",
        "Rejeter les recommandations du Comex sans contre-proposition — vous pouvez diverger, mais avec un plan alternatif argumenté",
        "Confondre vitesse et précipitation — une décision rapide mais mauvaise vous coûtera plus cher qu'une décision réfléchie de 48h",
        "Négliger la communication interne — vos équipes interprètent le silence comme de l'incertitude, pas de la réflexion",
        "Oublier de gérer votre propre énergie — un DG épuisé à J60 prend de mauvaises décisions à J90",
      ]},
      { type: "h2", text: "Comment PRSTO vous aide sur le plan 100 jours" },
      { type: "p", text: "Le Proof Vault de PRSTO est particulièrement utile ici : vectorisez vos réalisations antérieures pour identifier lesquelles sont réutilisables dans votre nouveau contexte. Le Conseiller IA peut vous aider à structurer votre plan en fonction de votre profil et du contexte de l'entreprise. Et le Mock Interview Panel vous prépare aux questions du Comex sur votre stratégie." },
      { type: "p", text: "Le plan 100 jours n'est pas une formalité. C'est votre première décision stratégique en tant que DG. Traitez-le comme tel." },
    ],
  },

  // ─── Article 2 ──────────────────────────────────────────
  {
    slug: "naviguer-entretien-fonds-private-equity",
    title: "L'entretien avec un fonds de Private Equity : ce qu'ils cherchent vraiment",
    subtitle: "Un PE n'évalue pas un candidat, il évalue un actif stratégique. Voici comment vous préparer.",
    excerpt: "Les fonds de Private Equity ont une logique d'évaluation radicalement différente d'un recruteur classique. Comprendre cette logique est la clé pour réussir cet entretien décisif.",
    date: "2026-06-22",
    author: newAuthors.catherine,
    category: "Entretien",
    tags: ["private equity", "entretien", "LBO", "due diligence", "c-level"],
    readingTime: "10 min",
    featured: false,
    heroGradient: "from-[#E4B118] via-[#F2C94C] to-[#D4A017]",
    content: [
      { type: "intro", text: "Passer un entretien avec un fonds de Private Equity est un exercice fondamentalement différent d'un entretien classique. Vous n'êtes pas évalué comme un candidat — vous êtes évalué comme un actif stratégique." },
      { type: "h2", text: "La logique du Private Equity" },
      { type: "p", text: "Un fonds de PE achète une entreprise avec un horizon de 4 à 7 ans et un objectif de retour sur investissement (IRR) de 20 à 30% par an. Quand ils recrutent un DG, ils ne cherchent pas un manager — ils cherchent un créateur de valeur qui transformera l'entreprise pour la revendre à un multiple supérieur." },
      { type: "p", text: "Cette logique change tout. Le recruteur classique évalue votre passé et votre fit culturel. Le PE évalue votre capacité à générer un multiple de sortie. Chaque question, chaque critère d'évaluation est filtré à travers ce prisme." },
      { type: "pullQuote", text: "Un PE ne vous demande pas 'êtes-vous un bon DG ?' Il vous demande 'pouvez-vous tripler la valeur de cette entreprise en 5 ans ?'", author: "Catherine Lefort" },
      { type: "h2", text: "Les 5 dimensions évaluées par un PE" },
      { type: "h3", text: "1. La création de valeur cash-flow" },
      { type: "p", text: "Le PE pense en EBITDA, pas en chiffre d'affaires. Votre première question de préparation doit être : 'Comment ai-je augmenté l'EBITDA dans mes postes précédents ?' Préparez 3-4 exemples chiffrés. 'J'ai augmenté l'EBITDA de 40% en 2 ans par une restructuration de la force de vente et une optimisation du mix produit' est la réponse attendue." },
      { type: "h3", text: "2. Le leverage opérationnel" },
      { type: "p", text: "Le PE cherche un DG qui peut transformer une structure coûts fixes en coûts variables. Avez-vous déjà externalisé, automatisé, ou restructuré des opérations ? Préparez des exemples précis avec des gains chiffrés." },
      { type: "h3", text: "3. Le M&A et la croissance externe" },
      { type: "p", text: "Beaucoup de stratégies de PE reposent sur des acquisitions bolt-on. Si vous avez de l'expérience en M&A — identification de cibles, due diligence, intégration post-acquisition — c'est un atout majeur. Si vous n'en avez pas, montrez votre capacité à penser en termes de build-up." },
      { type: "h3", text: "4. Le reporting et la gouvernance" },
      { type: "p", text: "Le PE impose un reporting mensuel détaillé (KPI dashboard, cash-flow forecast, variance analysis). Montrez que vous êtes à l'aise avec cette culture de transparence et de pilotage par les chiffres. Un DG qui dit 'je préfère piloter au feeling' ne passera pas le filtre." },
      { type: "h3", text: "5. L'alignement d'intérêts" },
      { type: "p", text: "Le PE vous proposera un package avec un fort composant equity (LTI, BSPCE, co-investissement). Ils veulent s'assurer que vous êtes prêt à 'mettre la main au portefeuille'. Si vous refusez le co-investissement, c'est un signal rouge pour eux." },
      { type: "h2", text: "Les questions typiques d'un entretien PE" },
      { type: "ul", items: [
        "Si vous preniez cette entreprise demain, quelles seraient vos 3 premières décisions ?",
        "Comment avez-vous amélioré la marge brute dans votre dernier poste ? (chiffres exacts)",
        "Décrivez un échec opérationnel. Qu'avez-vous appris ?",
        "Comment construisez-vous un forecast cash-flow à 13 semaines ?",
        "Si le marché se retourne dans 18 mois, comment ajustez-vous votre plan ?",
        "Quelle est votre experience en management de transition en période de crise ?",
      ]},
      { type: "h2", text: "La préparation : ce que vous devez faire" },
      { type: "p", text: "Avant l'entretien, analysez le fonds : quels sont leurs investissements actuels dans votre secteur ? Quel est leur horizon moyen de détention ? Quels sont leurs exits récents et les multiples réalisés ? Cette connaissance montre que vous pensez comme un partenaire, pas comme un employé." },
      { type: "p", text: "Préparez un '100-day value creation plan' même s'ils ne le demandent pas. Un document de 5-7 pages qui identifie les leviers de valeur (croissance, marge, cash, M&A) avec des hypothèses chiffrées. C'est le document qui différencie un DG d'un manager." },
      { type: "p", text: "Enfin, utilisez le Mock Interview Panel de PRSTO avec le rôle 'Investisseur/Board Member' pour vous entraîner aux questions les plus difficiles. Le Conseiller IA peut vous aider à structurer vos exemples EBITDA avec la méthode STAR." },
    ],
  },

  // ─── Article 3 ──────────────────────────────────────────
  {
    slug: "negocier-package-350k-mlf-series-b",
    title: "Négocier un package de 350k€ en Series B : anatomie d'un deal",
    subtitle: "Comment un DG de scale-up peut structurer son package pour maximiser la valeur sans tuer la relation",
    excerpt: "La négociation d'un package C-level en scale-up est un jeu d'échecs. Chaque composant — fixe, variable, equity, bonus — a un impact fiscal et stratégique. Voici la méthode.",
    date: "2026-06-15",
    author: newAuthors.marc,
    category: "Négociation & Package",
    tags: ["package", "equity", "Series B", "BSPCE", "négociation", "C-level"],
    readingTime: "9 min",
    featured: false,
    heroGradient: "from-[#0E3A29] via-[#1A4A2E] to-[#0E3A29]",
    content: [
      { type: "intro", text: "Un package de 350k€ en Series B ne se négocie pas comme un salaire. C'est un montage financier complexe où chaque composant a un impact fiscal, juridique et stratégique. Voici comment le structurer." },
      { type: "h2", text: "La structure type d'un package C-level en Series B" },
      { type: "p", text: "Pour une scale-up SaaS en Series B (typiquement 10-30M€ levés), un package de DG se compose de 4 éléments : fixe, variable court terme (bonus annuel), variable long terme (equity/LTI), et avantages. La répartition type est 50/20/25/5 — mais ce ratio varie selon le stade de l'entreprise et votre profil." },
      { type: "stat", stat: { value: "350k€", label: "Package total cible", description: "Pour un DG de scale-up Series B en France" } },
      { type: "h3", text: "Le fixe : 150-180k€" },
      { type: "p", text: "Le fixe représente 40-50% du package total. En Series B, le fixe d'un DG se situe entre 150k€ et 180k€ en France. Pousser trop haut le fixe est un signal négatif pour les investisseurs : ils interprètent cela comme un manque d'appétit pour le risque. Inversement, un fixe trop bas peut créer une pression financière qui vous empêchera de prendre des décisions sereines." },
      { type: "p", text: "L'erreur classique est de négocier agressivement le fixe au détriment de l'equity. C'est contre-productif : en Series B, la création de valeur est dans l'equity, pas dans le fixe. Un fixe à 160k€ avec 2% d'equity vaut largement un fixe à 200k€ avec 0.5%." },
      { type: "h3", text: "Le bonus annuel : 40-70k€" },
      { type: "p", text: "Le bonus représente 25-30% du fixe. Il doit être structuré autour de 2-3 KPIs maximum, pas 10. Les KPIs typiques en Series B sont : croissance du ARR (40% du bonus), EBITDA ou burn rate (30%), et objectifs stratégiques (30% — par exemple lancement produit, ouverture marché)." },
      { type: "p", text: "Attention au piège du seuil déclencheur : un bonus qui démarre à 80% de l'objectif est très différent d'un bonus qui démarre à 100%. Négociez un seuil bas (80%) avec un plafond élevé (150-200% du target). Cela vous protège en cas de marché difficile et vous récompense en cas de surperformance." },
      { type: "h3", text: "L'equity : BSPCE ou stock options" },
      { type: "p", text: "C'est le composant le plus important et le plus mal négocié. En France, les BSPCE (Bons de Souscription de Parts de Créateur d'Entreprise) sont fiscalement avantageux mais nécessitent un accord AG/AGE. Les stock options classiques sont plus simples mais moins avantageuses fiscalement." },
      { type: "p", text: "Pour un DG en Series B, visez 1.5% à 3% du capital fully diluted. Le vesting standard est 4 ans avec 1 an de cliff (25% la première année, puis mensuel). Négociez un accélération en cas de change of control (double trigger : acquisition + départ dans les 12 mois) et une accélération en cas de départ sans cause (12 mois d'accélération)." },
      { type: "pullQuote", text: "L'equity n'est pas un cadeau. C'est un investissement dans votre capacité à créer de la valeur. Traitez-le comme tel.", author: "Marc Vidal" },
      { type: "h3", text: "Le signing bonus : 20-50k€" },
      { type: "p", text: "Si vous quittez un poste stable pour rejoindre une scale-up, négociez un signing bonus pour compenser la perte de bonus non versé chez votre employeur actuel. C'est accepté et même attendu en Series B. Justifiez-le par le bonus que vous laissez sur la table." },
      { type: "h2", text: "Les clauses de protection à négocier" },
      { type: "ul", items: [
        "Bad leaver / Good leaver : assurez-vous que 'good leaver' inclut le départ suite à un changement de stratégie du board",
        "Non-concurrence : limitez-la à 12 mois maximum avec contrepartie financière (50% du fixe minimum)",
        "Accélération vesting : double trigger en cas d'acquisition (acquisition + licenciement dans 12 mois)",
        "Droit de sortie (tag-along) : protégez vos actions en cas de sortie des fondateurs",
        "Indemnité de licenciement : 6-12 mois de fixe + bonus cible, surtout si le board peut vous remplacer sans cause",
      ]},
      { type: "h2", text: "La négociation : timing et psychologie" },
      { type: "p", text: "Le meilleur moment pour négocier est APRÈS l'offre verbale et AVANT le contrat écrit. C'est là que vous avez le plus de levier. Une fois le contrat écrit, chaque modification devient un 'revirement' qui crée de la friction." },
      { type: "p", text: "Ne négociez jamais un seul composant en isolation. Si on vous refuse plus de fixe, demandez plus d'equity. Si on vous refuse plus d'equity, demandez un meilleur bonus. C'est le total qui compte, pas chaque ligne." },
      { type: "p", text: "Utilisez le Conseiller IA de PRSTO pour simuler la négociation. Posez-lui : 'Je reçois une offre de DG en Series B avec 160k€ fixe, 50k€ bonus, 1% equity. Comment négocier pour atteindre 350k€ de package total ?' Le framework 6-blocs vous donnera une analyse complète avec sources et plan d'action." },
    ],
  },

  // ─── Article 4 ──────────────────────────────────────────
  {
    slug: "linkedin-cadres-dirigeants-2026",
    title: "LinkedIn pour cadres dirigeants en 2026 : le guide complet",
    subtitle: "Pourquoi votre profil LinkedIn peut vous coûter un poste de DG — et comment l'optimiser",
    excerpt: "LinkedIn n'est plus un CV en ligne. Pour un cadre dirigeant, c'est votre vitrine stratégique, votre réseau d'influence et votre premier point de contact avec les chasseurs de têtes.",
    date: "2026-06-08",
    author: newAuthors.sophie,
    category: "CV & Personal Branding",
    tags: ["LinkedIn", "personal branding", "chasseurs", "réseau", "SSI"],
    readingTime: "7 min",
    featured: false,
    heroGradient: "from-[#0E3A29] via-[#1A4A2E] to-[#0E3A29]",
    content: [
      { type: "intro", text: "90% des chasseurs de têtes utilisent LinkedIn comme premier outil de sourcing. Votre profil est donc votre première — et parfois unique — chance d'être repéré. Voici comment l'optimiser pour un poste de direction." },
      { type: "h2", text: "Les 7 erreurs qui vous coûtent des opportunités" },
      { type: "p", text: "Après 12 ans à recruter des cadres dirigeants chez L'Oréal et Danone, j'ai vu des milliers de profils LinkedIn. Les erreurs sont toujours les mêmes : titre générique, résume absent ou trop long, expériences sans résultats chiffrés, photo non professionnelle, et — pire de tous — l'absence d'activité." },
      { type: "ul", items: [
        "Titre LinkedIn générique ('Directeur') au lieu de préciser ('Directeur Général | Scale-up SaaS B2B | 20 ans d'expérience | Trilingue')",
        "Résume écrit à la première personne comme un CV papier — LinkedIn est un réseau social, pas un document",
        "Expériences qui listent les responsabilités au lieu des résultats ('Management d'une équipe de 50 personnes' au lieu de '+32% de CA en 18 mois avec une équipe de 50 personnes')",
        "Photo de vacances recadrée ou photo trop ancienne (plus de 3 ans)",
        "Aucune recommandation — un DG sans recommandation sur LinkedIn est suspect",
        "Aucune publication ou commentaire — un profil inactif est un profil invisible",
        "Paramètres de confidentialité trop restrictifs — si on ne peut pas vous contacter, on ne vous contactera pas",
      ]},
      { type: "h2", text: "Le titre LinkedIn : votre argument de pitch en 120 caractères" },
      { type: "p", text: "Votre titre LinkedIn est la première chose qu'un chasseur de têtes voit dans les résultats de recherche. Il doit contenir 3 éléments : votre fonction actuelle, votre différenciation, et vos mots-clés cibles." },
      { type: "p", text: "Mauvais : 'Directeur Commercial'\nBon : 'Directeur Commercial | Scale-up SaaS B2B | +50M€ CA | International | Trilingue FR/EN/ES'\nExcellent : 'VP Sales | B2B SaaS | Built 3 teams from 0 to 50+ | 2 exits | Trilingue FR/EN/ES | Open to C-level roles'" },
      { type: "pullQuote", text: "Votre titre LinkedIn n'est pas votre fonction. C'est votre pitch. 120 caractères pour convaincre un chasseur de têtes de cliquer sur votre profil.", author: "Sophie Nguyen" },
      { type: "h2", text: "Le résumé : votre narratif stratégique" },
      { type: "p", text: "Le résumé LinkedIn d'un cadre dirigeant ne doit pas être un récapitulatif de votre CV. C'est votre narratif stratégique : qui vous êtes, ce que vous avez accompli, et ce que vous cherchez. 3-4 paragraphes maximum, écrits à la première personne, avec des résultats chiffrés." },
      { type: "p", text: "Structure recommandée : 1) Votre proposition de valeur en 1 phrase, 2) Vos 3 plus grandes réalisations chiffrées, 3) Votre vision du leadership, 4) Ce que vous cherchez (ouvertement ou subtilement, selon votre situation)." },
      { type: "h2", text: "L'activité : devenir visible sans être bruyant" },
      { type: "p", text: "Un cadre dirigeant qui poste 5 fois par jour perd sa crédibilité. Mais un dirigeant qui poste 1-2 fois par mois avec du contenu substantiel (analyse sectorielle, retour d'expérience, vision stratégique) devient une voix de référence. Le SSI (Social Selling Index) de LinkedIn récompense la qualité, pas la quantité." },
      { type: "p", text: "Stratégie simple : commentez 2-3 posts de leaders de votre secteur chaque semaine, publiez 1 post substantiel par mois (500-800 mots sur un sujet que vous maîtrisez), et partagez 1-2 articles pertinents avec votre commentaire. En 3 mois, votre visibilité auprès des chasseurs de têtes augmentera de 300%." },
      { type: "h2", text: "Le LinkedIn Optimizer de PRSTO" },
      { type: "p", text: "PRSTO inclut un LinkedIn Optimizer qui analyse votre profil sur 7 dimensions (titre, résumé, expériences, recommandations, activité, photo, paramètres) et vous donne un score avec des recommandations priorisées. Utilisez-le avant chaque changement de poste — ou même en continu pour maintenir votre visibilité." },
    ],
  },

  // ─── Article 5 ──────────────────────────────────────────
  {
    slug: "marche-cache-dirigeants-2026",
    title: "Le marché caché des postes de direction : 70% des DG ne passent jamais par une annonce",
    subtitle: "Comment accéder aux postes qui ne sont jamais publiés",
    excerpt: "Les meilleurs postes de direction ne sont jamais affichés sur LinkedIn ou APEC. Ils se traitent dans les coulisses, via les cabinets de chasse et les réseaux informels. Voici comment y accéder.",
    date: "2026-06-01",
    author: newAuthors.catherine,
    category: "Marché & Tendances",
    tags: ["marché caché", "chasseurs", "réseau", "DG", "c-level"],
    readingTime: "8 min",
    featured: false,
    heroGradient: "from-[#103826] via-[#1A4A2E] to-[#0E3A29]",
    content: [
      { type: "intro", text: "70% des recrutements de cadres dirigeants en France ne passent jamais par une annonce publique. Ces postes — les meilleurs, les mieux rémunérés, les plus stratégiques — se traitent en circuit fermé. Voici comment pénétrer ce marché caché." },
      { type: "h2", text: "Pourquoi le marché caché existe" },
      { type: "p", text: "Les entreprises ne publient pas les postes de direction pour 3 raisons : confidentialité (remplacer un DG en place sans le savoir), sélectivité (un cabinet de chasse approche directement les bons profils), et réputation (une entreprise qui affiche qu'elle cherche un DG signale une crise ou une instabilité)." },
      { type: "p", text: "Conséquence : si vous attendez de voir une annonce pour postuler, vous accédez à seulement 30% du marché. Les 70% restants — les meilleures opportunités — sont réservés à ceux qui sont dans le réseau des chasseurs de têtes et des boards." },
      { type: "pullQuote", text: "Le meilleur poste de votre carrière n'est probablement pas sur LinkedIn. Il est dans le carnet d'adresses d'un chasseur de têtes.", author: "Catherine Lefort" },
      { type: "h2", text: "Les 4 canaux du marché caché" },
      { type: "h3", text: "1. Les cabinets de chasse (Executive Search)" },
      { type: "p", text: "Les cabinets top-tier (Spencer Stuart, Heidrick & Struggles, Egon Zehnder, Russell Reynolds, Korn Ferry) gèrent les mandats les plus prestigieux. Pour être dans leur radar, vous devez être référencé dans leur base de données. La méthode : invitez leurs consultants à un café (LinkedIn ou email), présentez votre parcours en 5 minutes, et restez en contact tous les 6 mois." },
      { type: "p", text: "Les cabinets mid-tier (Michael Page Executive, Robert Walters, Robert Half Executive Search, Odgers Berndtson) sont plus accessibles et gèrent des mandats plus nombreux, souvent sur des postes de DGD, Directeur de Division, ou VP. Ils sont plus réactifs et plus susceptibles de vous appeler rapidement." },
      { type: "h3", text: "2. Les réseaux de DG et de board members" },
      { type: "p", text: "Les postes de DG se traitent souvent par cooptation au sein de réseaux fermés : French Tech, Cercle Magnan, Institut de l'Entreprise, ANDESE, réseaux d'alumni (HEC, INSEAD, Polytechnique). Si vous n'êtes pas dans ces réseaux, intégrez-en au moins un. Le ROI est immédiat en termes de visibilité et de référencement." },
      { type: "h3", text: "3. Les investisseurs et fonds" },
      { type: "p", text: "Les fonds de PE, VC et family offices ont constamment besoin de DG pour leurs portefeuilles. Identifiez les fonds qui investissent dans votre secteur, approchez les partners directement (ils cherchent toujours des talents), et proposez votre profil. C'est le canal le plus sous-estimé du marché caché." },
      { type: "h3", text: "4. Le réseau informel des pairs" },
      { type: "p", text: "Les DG se recommandent entre eux. Un DG qui part remplace souvent son poste par quelqu'un de son réseau. Maintenez des relations régulières avec 10-15 DG de votre secteur — un café tous les 3 mois suffit. C'est le réseau le plus puissant et le plus rapide." },
      { type: "h2", text: "Comment se faire remarquer par les chasseurs" },
      { type: "p", text: "Les chasseurs de têtes sourcing en permanence. Pour être repéré, vous devez être visible là où ils cherchent : LinkedIn (titre optimisé, activité régulière), presse spécialisée (interviews, tribunes), conférences sectorielles (intervenants, pas simples participants), et publications académiques ou professionnelles." },
      { type: "p", text: "Le CRM Recruteur de PRSTO vous permet de suivre vos relations avec chaque chasseur : date du dernier contact, missions discutées, niveau de relation. Utilisez-le pour ne jamais perdre le fil d'une relation qui peut déboucher sur une opportunité 12 ou 18 mois plus tard." },
    ],
  },

  // ─── Article 6 ──────────────────────────────────────────
  {
    slug: "echec-recherche-emploi-dirigeant",
    title: "J'ai cherché un poste de DG pendant 14 mois : voici ce que j'ai appris",
    subtitle: "Témoignage d'un dirigeant qui a transformé un échec en opportunité",
    excerpt: "14 mois de recherche, 47 candidatures, 3 finales, 0 offres. Voici l'analyse honnête de ce qui n'a pas marché — et ce qui a finalement fonctionné.",
    date: "2026-05-25",
    author: newAuthors.david,
    category: "Transition",
    tags: ["témoignage", "recherche emploi", "échec", "résilience", "DG"],
    readingTime: "9 min",
    featured: false,
    heroGradient: "from-[#1A4A2E] via-[#103826] to-[#0E3A29]",
    content: [
      { type: "intro", text: "Ce témoignage est celui d'un dirigeant qui a traversé 14 mois de recherche d'emploi. Pas un témoignage lisse et inspirant. Une analyse honnête des erreurs, des moments de doute, et de ce qui a fini par fonctionner." },
      { type: "h2", text: "Les 6 premiers mois : l'illusion du contrôle" },
      { type: "p", text: "Quand j'ai quitté mon poste de DGD en janvier, j'étais confiant. 20 ans d'expérience, un réseau solide, un CV impeccable. Je pensais trouver en 3 mois. J'avais tort. Les 6 premiers mois ont été une succession d'espoirs et de déceptions. 15 candidatures, 8 entretiens, 2 finales, 0 offres." },
      { type: "p", text: "Mon erreur principale : je traitais ma recherche d'emploi comme un process linéaire — candidature → entretien → offre. Or, pour un poste de direction, le process est non-linéaire. Il dépend de facteurs que vous ne contrôlez pas : timing du board, stratégie du fonds, vacances du CEO, budget Q1 vs Q3." },
      { type: "pullQuote", text: "Les 6 premiers mois, j'ai perdu mon temps à postuler à des annonces. Les 6 suivants, j'ai construit mon réseau. Les 2 derniers, j'ai été approché.", author: "David Marchand" },
      { type: "h2", text: "Les mois 7-10 : le doute et la remise en question" },
      { type: "p", text: "À 7 mois, j'ai commencé à douter. Pas de mes compétences — de ma méthode. J'ai analysé chaque échec : pourquoi cette finale n'a pas abouti ? Pourquoi ce cabinet ne m'a pas recontacté ? Pourquoi ce board a choisi l'autre candidat ?" },
      { type: "p", text: "Les leçons étaient douloureuses mais précieuses : mon pitch était trop générique, je ne savais pas raconter mes échecs (un DG qui n'a jamais échoué est suspect), je sous-estimais l'importance du 'fit culturel' avec le board, et je négligeais le marché caché au profit des annonces." },
      { type: "h2", text: "Les mois 11-14 : la méthode qui a fonctionné" },
      { type: "p", text: "J'ai complètement changé d'approche. Au lieu de postuler, j'ai construit 3 choses : un réseau de 15 DG et board members que j'ai rencontrés régulièrement, une présence LinkedIn avec 1 publication mensuelle substantielle, et un Proof Vault de mes 10 plus grandes réalisations chiffrées." },
      { type: "p", text: "Résultat : à 12 mois, j'ai été approché par un fonds de PE pour un poste de DG dans une de leurs portefeuilles. Pas une annonce — une approche directe via un DG de mon réseau qui avait recommandé mon profil. Le process a duré 2 mois et j'ai signé à 14 mois." },
      { type: "h2", text: "Les 5 leçons que je retiens" },
      { type: "ul", items: [
        "Ne postulez pas — soyez approché. Le marché caché représente 70% des postes de DG",
        "Construisez votre Proof Vault avant d'en avoir besoin. Les réalisations chiffrées sont votre monnaie d'échange",
        "Acceptez de raconter vos échecs. Un DG qui dit 'tout a toujours marché' n'est pas crédible",
        "Investissez dans LinkedIn. 1 publication par mois change votre visibilité",
        "Ne négociez jamais sous pression financière. Si vous êtes à court de cash, prenez un mandat d'admin ou de conseil en attendant",
      ]},
      { type: "h2", text: "Le rôle de PRSTO dans ma recherche" },
      { type: "p", text: "Si PRSTO avait existé pendant ma recherche, j'aurais économisé 6 mois. Le Proof Vault m'aurait forcé à structurer mes réalisations dès le début. Le CRM Recruteur m'aurait permis de suivre mes relations chasseurs. Le Conseiller IA m'aurait aidé à préparer chaque entretien avec un plan d'action. Et le Mock Interview Panel m'aurait préparé aux questions difficiles des boards." },
      { type: "p", text: "14 mois de recherche, c'est long. Mais c'est aussi le temps qu'il faut pour trouver le BON poste — pas juste un poste. PRSTO existe pour raccourcir ce temps et augmenter la qualité de l'issue." },
    ],
  },

  // ─── Article 7 ──────────────────────────────────────────
  {
    slug: "due-diligence-dirigeant-avant-signer",
    title: "Due diligence du dirigeant : 10 questions à poser avant de signer",
    subtitle: "L'entreprise vous évalue, mais vous devez aussi l'évaluer. Voici les questions qui révèlent les problèmes cachés.",
    excerpt: "Accepter un poste de DG sans faire votre propre due diligence est la pire erreur d'un dirigeant. Voici les 10 questions qui vous éviteront de signer dans une entreprise qui va couler.",
    date: "2026-05-18",
    author: newAuthors.sophie,
    category: "Stratégie",
    tags: ["due diligence", "board", "transparence", "risques", "DG"],
    readingTime: "8 min",
    featured: false,
    heroGradient: "from-[#103826] via-[#0E3A29] to-[#1A4A2E]",
    content: [
      { type: "intro", text: "Quand une entreprise vous offre un poste de DG, l'euphorie peut vous faire oublier l'essentiel : vous aussi, vous évaluez. Voici les 10 questions à poser absolument avant de signer." },
      { type: "h2", text: "Pourquoi la due diligence du dirigeant est critique" },
      { type: "p", text: "50% des DG recrutés quittent leur poste dans les 2 ans. La cause principale n'est pas l'incompétence — c'est un mauvais fit entre les attentes du board et la réalité de l'entreprise. Un DG qui arrive sans avoir fait sa due diligence découvre les problèmes après signature, quand il est trop tard pour négocier ou partir." },
      { type: "p", text: "La due diligence du dirigeant est l'image miroir de la due diligence que l'entreprise fait sur vous. Vous devez auditer la santé financière, la culture, la gouvernance, et les attentes cachées du board avec la même rigueur qu'ils auditent votre parcours." },
      { type: "h2", text: "Les 10 questions qui révèlent tout" },
      { type: "h3", text: "1. 'Quels sont les 3 derniers boards et quelles décisions difficiles y ont été prises ?'" },
      { type: "p", text: "Cette question révèle le fonctionnement réel du board. Si on vous montre des comptes-rendus lisses sans aucune décision difficile, méfiez-vous : soit le board ne sert à rien, soit on vous cache les tensions." },
      { type: "h3", text: "2. 'Pourquoi le précédent DG est-il parti ?'" },
      { type: "p", text: "La réponse officielle est toujours 'pour de nouvelles opportunités'. Creusez. Demandez à rencontrer le DG précédent si possible. S'il a été licencié, demandez pourquoi. S'il est parti volontairement, demandez ce qui l'a frustré." },
      { type: "h3", text: "3. 'Quel est le runway cash réel, pas le forecast ?'" },
      { type: "p", text: "Demandez le cash-flow des 3 derniers mois, pas le forecast des 12 prochains. Le forecast est toujours optimiste. Le cash réel vous dit si l'entreprise a 6 mois ou 18 mois devant elle." },
      { type: "h3", text: "4. 'Quels sont les 3 plus gros clients et quelle est leur concentration ?'" },
      { type: "p", text: "Si un client représente plus de 25% du CA, vous avez un risque majeur. Demandez la duration des contrats, le churn des 3 dernières années, et le pipeline commercial réaliste (pas le best case)." },
      { type: "h3", text: "5. 'Qui aura le droit de veto sur vos décisions ?'" },
      { type: "p", text: "Le board ? Le fondateur ? Le fonds ? Le CEO si vous êtes DGD ? Cartographie exactement qui a le pouvoir de bloquer une décision. Si la réponse est floue, c'est un signal rouge." },
      { type: "h3", text: "6. 'Quels sont les investisseurs et quelle est leur horizon de sortie ?'" },
      { type: "p", text: "Un fonds qui veut sortir dans 18 mois a une logique radicalement différente d'un fondateur qui veut construire sur 10 ans. Cette information change votre stratégie, votre package, et votre propre horizon." },
      { type: "h3", text: "7. 'Quelle est la rotation des cadres dirigeants dans les 3 dernières années ?'" },
      { type: "p", text: "Si 50% du Comex a changé en 2 ans, il y a un problème culturel ou de gouvernance. Demandez pourquoi chaque départ a eu lieu et cherchez les patterns." },
      { type: "h3", text: "8. 'Y a-t-il des litiges en cours ? Prud'hommes, commercial, fiscal ?'" },
      { type: "p", text: "Les entreprises cachent souvent leurs litiges. Demandez explicitement. Un litige prud'hommal en cours peut révéler une culture managériale toxique. Un litige commercial peut signaler un problème de produit." },
      { type: "h3", text: "9. 'Quel est le vrai P&L, hors accounting créatif ?'" },
      { type: "p", text: "Demandez à voir le P&L brut, sans retraitement. Les 'ajustements' (provisions reprises, charges exceptionnelles, EBITDA ajusté) peuvent masquer une réalité financière très différente de la présentation officielle." },
      { type: "h3", text: "10. 'Comment se passera votre propre évaluation ?'" },
      { type: "p", text: "Quels KPIs ? Quelle fréquence ? Qui décide du bonus ? Si la réponse est vague ('on verra ensemble'), vous signez un chèque en blanc. Négociez les KPIs et les modalités d'évaluation AVANT de signer." },
      { type: "h2", text: "Utilisez le Conseiller IA de PRSTO" },
      { type: "p", text: "Le Conseiller IA de PRSTO peut vous aider à préparer ces questions dans le contexte spécifique de l'entreprise que vous évaluez. Posez-lui : 'Je vais rencontrer le board de [entreprise]. Quelles questions de due diligence dois-je préparer ?' Le framework 6-blocs vous donnera un plan complet avec sources et exemples." },
    ],
  },

  // ─── Article 8 ──────────────────────────────────────────
  {
    slug: "equity-vesting-clauses-pieges",
    title: "Equity et vesting : les 7 pièges qui vous coûtent des millions",
    subtitle: "Votre package equity peut valoir 0€ si vous ne lisez pas les petites lignes",
    excerpt: "BSPCE, stock options, RSU, vesting schedule, cliff, accélération — chaque clause a un impact financier massif. Voici les 7 pièges à éviter absolument.",
    date: "2026-05-10",
    author: newAuthors.marc,
    category: "Négociation & Package",
    tags: ["equity", "vesting", "BSPCE", "clauses", "pièges", "C-level"],
    readingTime: "7 min",
    featured: false,
    heroGradient: "from-[#E4B118] via-[#F2C94C] to-[#D4A017]",
    content: [
      { type: "intro", text: "Un package equity de 2% peut valoir 500k€ ou 0€ selon les clauses de vesting, de leaver, et d'accélération. Voici les 7 pièges qui transforment une fortune en mirage." },
      { type: "h2", text: "Piège 1 : Le cliff trop long" },
      { type: "p", text: "Le cliff est la période pendant laquelle vous n'acquérez aucun droit. Le standard est 12 mois. Mais certains contrats prévoient un cliff de 24 mois. Si vous partez à 23 mois, vous perdez 100% de votre equity. Négociez un cliff de 12 mois maximum, idéalement 6 mois." },
      { type: "h2", text: "Piège 2 : Le bad leaver trop large" },
      { type: "p", text: "Un 'bad leaver' perd tout son equity non vested (et parfois même le vested). La définition de bad leaver est critique : elle doit être limitée aux fautes graves (fraude, concurrence déloyale). Si le contrat dit 'toute démission est un bad leaver', refusez. Une démission pour un meilleur poste n'est pas une faute." },
      { type: "pullQuote", text: "J'ai vu un DG perdre 800k€ d'equity parce qu'il avait signé un bad leaver clause qui considérait toute démission comme une faute.", author: "Marc Vidal" },
      { type: "h2", text: "Piège 3 : Pas d'accélération en cas d'acquisition" },
      { type: "p", text: "Si l'entreprise est rachetée et que votre vesting n'est pas accéléré, vous perdez tout. Négociez obligatoirement un 'double trigger' : l'equity s'accélère si (1) l'entreprise est acquise ET (2) vous êtes licencié dans les 12 mois suivant l'acquisition. Idéalement, négociez un 'single trigger' : l'acquisition seule accélère 50% du vesting." },
      { type: "h2", text: "Piège 4 : Le strike price trop élevé" },
      { type: "p", text: "Le strike price (prix d'exercice) de vos BSPCE ou stock options doit être fixé à la valeur de l'entreprise AU MOMENT DE L'ATTRIBUTION, pas à une valorisation future. Si le strike est fixé après une levée qui augmente la valorisation, vos options perdent de la valeur. Exigez un strike price fixé à la date de signature." },
      { type: "h2", text: "Piège 5 : Pas de liquidité preference" },
      { type: "p", text: "En cas de vente, les investisseurs récupèrent leur investissement avant les employés (liquidation preference). Si la liquidation preference est 2x ou 3x, il faut que l'entreprise soit vendue à un multiple élevé pour que votre equity ait de la valeur. Demandez quelle est la liquidation preference et le total des préférences cumulées." },
      { type: "h2", text: "Piège 6 : La période d'exercice trop courte" },
      { type: "p", text: "Après votre départ, vous avez généralement 90 jours pour exercer vos options vested. Si vous ne pouvez pas payer le strike price dans les 90 jours, vous perdez tout. Négociez une période d'exercice étendue (5-10 ans) ou un 'cashless exercise' qui permet d'exercer sans débourser." },
      { type: "h2", text: "Piège 7 : Le dilution invisible" },
      { type: "p", text: "Votre 2% d'equity peut devenir 0.5% après plusieurs levées. Demandez quelles sont les prévisions de levée et le pool d'options disponible. Si le pool d'options est de 20% et que vous êtes le dernier entrant, votre dilution sera massive. Négociez une protection anti-dilution ou un refresh d'options après chaque levée." },
      { type: "h2", text: "Ce que vous devez faire" },
      { type: "p", text: "Avant de signer, faites vérifier le contrat d'equity par un avocat spécialisé en droit social et fiscal. Le coût (500-2000€) est négligeable comparé à l'enjeu (souvent plusieurs centaines de milliers d'euros). Et utilisez le Conseiller IA de PRSTO pour simuler différents scénarios de sortie et comprendre l'impact de chaque clause." },
    ],
  },

  // ─── Article 9 ──────────────────────────────────────────
  {
    slug: "gouvernance-comex-cadres-dirigeants",
    title: "Gouvernance de Comex : comment un DG construit un comité qui décide",
    subtitle: "Pourquoi 80% des Comex sont des réunions de reporting et comment transformer le vôtre en machine décisionnelle",
    excerpt: "Un Comex qui ne décide pas est un Comex qui coûte. Voici la méthode pour transformer votre comité de direction en véritable organe de gouvernance stratégique.",
    date: "2026-05-03",
    author: newAuthors.david,
    category: "Stratégie",
    tags: ["Comex", "gouvernance", "décision", "leadership", "DG"],
    readingTime: "8 min",
    featured: false,
    heroGradient: "from-[#103826] via-[#1A4A2E] to-[#0E3A29]",
    content: [
      { type: "intro", text: "80% des Comex en France sont des réunions de reporting où chaque membre présente ses chiffres. C'est un gaspillage de temps et de talent. Un vrai Comex décide, n'arbitre pas, et transforme le collectif en avantage concurrentiel." },
      { type: "h2", text: "Le diagnostic : votre Comex est-il un Comex de reporting ?" },
      { type: "p", text: "Si votre Comex ressemble à ceci, vous avez un problème : chaque membre présente 15 slides de reporting, le DG écoute et commente, les décisions sont reportées à la prochaine réunion, et les vraies discussions se font en bilatéral après la réunion. Ce modèle est dominant en France — et il est inefficace." },
      { type: "p", text: "Un Comex efficace passe 70% de son temps sur 3-4 décisions stratégiques et 30% sur le suivi opérationnel. L'inverse est la norme. Le coût d'un Comex inefficace est énorme : 8 personnes × 3 heures × 12 fois par an = 288 heures de dirigeants, soit l'équivalent de 150 jours-homme gaspillés." },
      { type: "pullQuote", text: "Un Comex qui ne décide pas est un organe social. Un Comex qui décide est un avantage concurrentiel.", author: "David Marchand" },
      { type: "h2", text: "Les 5 principes d'un Comex qui décide" },
      { type: "h3", text: "1. L'agenda inversé" },
      { type: "p", text: "Au lieu de demander à chaque membre de préparer son reporting, le DG définit 3-4 sujets de décision pour chaque Comex. Les membres préparent leurs inputs sur ces sujets. Le reporting est envoyé en amont (écrit, 1 page maximum par fonction) et n'est PAS présenté en réunion." },
      { type: "h3", text: "2. Le pre-read obligatoire" },
      { type: "p", text: "Chaque décision soumise au Comex doit faire l'objet d'un document de 2-3 pages envoyé 48h avant : contexte, options, recommandation, risques. Pas de pre-read = pas de discussion. Cette règle force la préparation et élimine les présentations PowerPoint interminables." },
      { type: "h3", text: "3. La règle 'disagree and commit'" },
      { type: "p", text: "Une fois qu'une décision est prise (par consensus ou par autorité du DG), chaque membre doit la soutenir publiquement. Pas de 'je n'étais pas d'accord mais j'ai été minoré'. Si un membre ne peut pas soutenir une décision, il doit le dire PENDANT la réunion, pas après." },
      { type: "h3", text: "4. Le suivi des décisions" },
      { type: "p", text: "Chaque Comex commence par un review des décisions prises lors du Comex précédent : statut, échéances, blocages. Ce suivi transforme le Comex d'un forum de discussion en un organe d'exécution." },
      { type: "h3", text: "5. La rotation des sujets" },
      { type: "p", text: "Chaque membre du Comex anime à tour de rôle un sujet stratégique. Cela force chacun à sortir de sa fonction et à penser en DG. C'est aussi un excellent outil de development pour les futurs dirigeants." },
      { type: "h2", text: "Le rôle du DG dans le Comex" },
      { type: "p", text: "Le DG n'est pas un animateur — c'est un facilitateur et un décideur. Son rôle est de poser les bonnes questions, de challenger les recommandations, et de trancher quand le consensus n'émerge pas. Un DG qui ne tranche jamais perd sa crédibilité. Un DG qui tranche toujours sans écouter perd la confiance de son équipe." },
      { type: "p", text: "L'équilibre est délicat. Utilisez le Mock Interview Panel de PRSTO pour vous entraîner aux situations difficiles : un CFO qui bloque une investissement, un CTO qui veut doubler le budget R&D, un DRH qui alerte sur une dégradation culturelle. Ces simulations vous préparent aux vraies tensions du Comex." },
    ],
  },

  // ─── Article 10 ──────────────────────────────────────────
  {
    slug: "transition-vers-conseil-administration",
    title: "De DG à administrateur : la transition stratégique que peu de dirigeants anticipent",
    subtitle: "Pourquoi siéger à un conseil d'administration est la suite logique d'un parcours de DG — et comment s'y préparer",
    excerpt: "Le mandat d'administrateur n'est pas une retraite. C'est un nouveau métier qui exige des compétences spécifiques. Voici comment réussir cette transition.",
    date: "2026-04-26",
    author: newAuthors.catherine,
    category: "Transition",
    tags: ["conseil d'administration", "mandat", "board", "transition", "administrateur"],
    readingTime: "7 min",
    featured: false,
    heroGradient: "from-[#1A4A2E] via-[#103826] to-[#0E3A29]",
    content: [
      { type: "intro", text: "Après 20 ans de management opérationnel, beaucoup de DG envisagent le mandat d'administrateur comme une suite naturelle. C'est vrai — mais c'est un métier radicalement différent qui exige une préparation spécifique." },
      { type: "h2", text: "Pourquoi le mandat d'administrateur n'est pas une retraite" },
      { type: "p", text: "L'image de l'administrateur qui dort en réunion de conseil appartient au passé. Les boards modernes exigent une contribution active : expertise sectorielle, challenge stratégique, réseau opérationnel, et capacité à auditer les décisions du DG. Un administrateur passif ne sera pas renouvelé." },
      { type: "p", text: "En France, la rémunération d'un administrateur en société cotée varie de 30k€ à 80k€ par an (jetons de présence + indemnités de comité). En société non cotée, c'est 10k€ à 30k€. Ce n'est pas un revenu de remplacement — c'est un revenu complémentaire qui valorise votre expérience." },
      { type: "pullQuote", text: "Le mandat d'administrateur n'est pas une fin de carrière. C'est un début — celui où votre expérience sert à d'autres.", author: "Catherine Lefort" },
      { type: "h2", text: "Les compétences d'un bon administrateur" },
      { type: "ul", items: [
        "Savoir lire un bilan et un P&L sans être expert-comptable — comprendre les signaux faibles financiers",
        "Poser des questions stratégiques sans tomber dans l'opérationnel — l'admin n'est pas le manager",
        "Challenge le DG sans le déstabiliser — fermeté sur le fond, respect sur la forme",
        "Apporter un réseau et des opportunités — clients, talents, partenaires",
        "Maîtriser la gouvernance — droits de vote, conventions réglementées, responsabilités légales",
      ]},
      { type: "h2", text: "Comment obtenir son premier mandat" },
      { type: "p", text: "Les mandats ne se demandent pas — ils s'offrent. Pour être approché, vous devez être visible dans les écosystèmes où les boards sourcing : AFJE (Association Française des Juristes d'Entreprise), IFA (Institut Français des Administrateurs), cercles sectoriels, et réseaux de PE/VC." },
      { type: "p", text: "La méthode la plus efficace : postulez aux mandats de startups et scale-ups. Ces entreprises recherchent des administrateurs expérimentés qui apportent structure et réseau. Le ticket d'entrée est plus accessible qu'en société cotée, et l'expérience acquise est immédiatement valorisable pour des mandats plus prestigieux." },
      { type: "p", text: "PRSTO peut vous aider dans cette transition : le CRM Recruteur pour suivre vos relations avec les boards, le Proof Vault pour documenter votre expertise governance, et le Conseiller IA pour préparer votre pitch de candidat-administrateur." },
    ],
  },
];
