/**
 * 50 CV examples executive — par poste
 * ===================================
 * SEO target: "cv directeur général", "cv cfo", "cv country manager", etc.
 *
 * Chaque entry a:
 * - slug: URL-friendly
 * - title: poste (avec variantes)
 * - category: famille exec
 * - salaryRange: fourchette FR
 * - keywords: mots-clés SEO à inclure
 * - summary: intro 100-150 mots
 * - keySkills: compétences clés attendues
 * - achievements: exemples de réalisations chiffrées
 * - faq: 3 Q/R pour rich snippets
 */

export interface CVExample {
  slug: string;
  title: string;
  category: "C-Suite" | "Direction" | "Management" | "Conseil" | "International";
  salaryRange: string;
  keywords: string[];
  summary: string;
  keySkills: string[];
  achievements: string[];
  faq: Array<{ question: string; answer: string }>;
}

export const CV_EXAMPLES: CVExample[] = [
  // ═══ C-SUITE (10) ═══
  {
    slug: "cv-directeur-general",
    title: "CV Directeur Général (DG)",
    category: "C-Suite",
    salaryRange: "150K€ - 500K€ + bonus",
    keywords: ["cv directeur général", "cv dg", "exemple cv dg", "comment rédiger cv directeur général"],
    summary: "Le CV d'un Directeur Général doit refléter une vision stratégique, une capacité à piloter une organisation complète et un impact business mesurable. Contrairement à un CV manager, le CV DG met l'accent sur le P&L global, la gouvernance (CoDir, Board), les opérations M&A et la transformation organisationnelle. Longueur recommandée : 1-2 pages maximum, format sobre, réalisations chiffrées.",
    keySkills: ["Stratégie corporate", "P&L global", "Gouvernance (CoDir/Board)", "M&A / croissance externe", "Leadership d'organisation", "Relations investisseurs", "Transformation digitale", "International expansion"],
    achievements: [
      "Dirigé un groupe de 1 200 collaborateurs, P&L de 280 M€, croissance EBITDA +24% sur 3 ans",
      "Piloté 3 acquisitions (45 M€ total) avec intégration opérationnelle en 90 jours",
      "Transformé l'organisation (5 directions) en mode agile, réduisant le time-to-market de 35%",
      "Levé 80 M€ auprès de fonds PE pour financer la croissance internationale",
    ],
    faq: [
      { question: "Quelle longueur pour un CV de Directeur Général ?", answer: "1 à 2 pages maximum. Les recruteurs passent en moyenne 30 secondes sur un CV exec — la concision est un signal de maturité." },
      { question: "Faut-il mentionner le package salarial sur un CV DG ?", answer: "Non, jamais sur le CV. Le package se discute en entretien. Mentionnez en revanche la taille du P&L géré." },
      { question: "Doit-on inclure une photo sur un CV DG ?", answer: "C'est optionnel en France. Si vous en mettez une, investissez dans un portrait professionnel (pas LinkedIn de vacances)." },
    ],
  },
  {
    slug: "cv-ceo",
    title: "CV CEO (Chief Executive Officer)",
    category: "C-Suite",
    salaryRange: "200K€ - 1M€+ (variable selon taille)",
    keywords: ["cv ceo", "cv chief executive officer", "exemple cv ceo startup"],
    summary: "Le CV CEO diffère du CV DG : il met l'accent sur la vision long-terme, la relation avec le Board / investisseurs, la levée de fonds et l'hypercroissance. Particulièrement pertinent pour les scale-ups et startups Series A+. Le CEO doit démontrer sa capacité à exécuter une vision, pas seulement à gérer des opérations.",
    keySkills: ["Vision & strategy", "Board management", "Fundraising (VC/PE)", "Hypergrowth leadership", "Public representation", "Crisis management", "Talent attraction", "Product-market fit"],
    achievements: [
      "Levé 50 M€ en Series B auprès de Tier-1 VCs (Balderton, Index Ventures)",
      "Triplé l'ARR de 8 M€ à 25 M€ en 18 mois (NRR 140%)",
      "Construit une équipe de 80 personnes (5 VPs recrutés), ouverture 3 pays",
      "Présentation au Board trimestrielle, transparence KPIs (OKR framework)",
    ],
    faq: [
      { question: "Un CV CEO doit-il être différent d'un CV DG ?", answer: "Oui. Le CEO met l'accent sur la vision, le fundraising et l'hypercroissance. Le DG insiste sur l'opérationnel et le P&L d'une organisation mature." },
      { question: "Comment présenter une levée de fonds sur un CV CEO ?", answer: "Mentionnez le montant, le tour (Seed/A/B), les investisseurs et l'utilisation des fonds. Ex: 'Levé 50M€ Series B (Balderton) pour accélérer l'expansion EU+US'." },
      { question: "Faut-il un CV CEO si on est fondateur ?", answer: "Oui, même en tant que fondateur. Les investisseurs et partenaires voudront voir votre parcours structuré, pas seulement votre pitch deck." },
    ],
  },
  {
    slug: "cv-cfo",
    title: "CV CFO (Directeur Financier)",
    category: "C-Suite",
    salaryRange: "150K€ - 400K€ + bonus",
    keywords: ["cv cfo", "cv directeur financier", "exemple cv cfo", "cv finance executive"],
    summary: "Le CV CFO doit rassurer sur 3 dimensions : la maîtrise technique (audit, contrôle de gestion, fiscalité), l'impact stratégique (M&A, financements, IPO) et le leadership (équipe finance, relations Board/auditeurs). Les réalisations doivent être chiffrées en M€ et % — un CFO qui ne chiffre pas son impact est un signal négatif.",
    keySkills: ["Financial planning & analysis", "M&A execution", "Treasury management", "Investor relations", "Audit & compliance", "Cash management", "Tax optimization", "ERP implementation"],
    achievements: [
      "Optimisé la trésorerie de 80 M€, réduisant le coût de la dette de 180 bps",
      "Piloté 2 acquisitions (45 M€) : due diligence, financement, intégration financière",
      "Restructuré la dette (refinancement 120 M€), économies 4 M€/an en intérêts",
      "Construit équipe finance de 25 personnes (5 directs), mis en place SAP S4",
    ],
    faq: [
      { question: "Un CV CFO doit-il mentionner l'audit Big 4 ?", answer: "Oui, c'est un signal fort pour les recruteurs. Mentionnez : cabinet, années, type de missions et certifications (CPA, DSCG)." },
      { question: "Quels chiffres mettre sur un CV CFO ?", answer: "P&L géré, taille d'équipe, montant des financements/M&A, économies réalisées en M€, amélioration des marges en %." },
      { question: "Le CV CFO doit-il être plus technique que celui du CEO ?", answer: "Oui, le CFO doit montrer la maîtrise technique (IFRS, US GAAP, tax) mais sans tomber dans le détail opérationnel. Le stratégique reste dominant." },
    ],
  },
  {
    slug: "cv-coo",
    title: "CV COO (Directeur des Opérations)",
    category: "C-Suite",
    salaryRange: "150K€ - 350K€ + bonus",
    keywords: ["cv coo", "cv directeur operations", "cv operations executive"],
    summary: "Le CV COO doit démontrer la capacité à exécuter la stratégie définie par le CEO. Focus sur : opérations industrielles ou de service, supply chain, qualité, transformation opérationnelle et pilotage des équipes terrain. Le COO est souvent le 'numéro 2' — il doit montrer qu'il peut être le 'chef des chefs'.",
    keySkills: ["Operations management", "Supply chain", "Lean / Six Sigma", "Industrial transformation", "Quality (ISO)", "Plant management", "Process optimization", "Operational excellence"],
    achievements: [
      "Piloté 4 sites industriels (1 200 personnes), CA 350 M€, marge brute +6 pts",
      "Déployé le Lean Manufacturing sur 4 usines, OEE +18% en 12 mois",
      "Réduit les coûts opérationnels de 22 M€ en 18 mois (programme d'excellence)",
      "Transformé la supply chain, réduisant les stocks de 28% et le OTD +15 pts",
    ],
    faq: [
      { question: "COO vs Directeur Général Adjoint ?", answer: "Le COO est clairement le n°2 opérationnel, avec une responsabilité P&L. Le DGA peut avoir un scope plus restreint (functions support). Le CV COO doit montrer un impact transversal." },
      { question: "Le Lean Six Sigma est-il obligatoire sur un CV COO ?", answer: "Pas obligatoire mais fortement valorisé, surtout en industrie. Si vous êtes Black Belt, mentionnez-le — c'est un signal fort." },
      { question: "Comment montrer son impact COO sur un CV ?", answer: "Chiffrez tout : coûts évités, OEE amélioré, stocks réduits, OTD augmenté. Un COO qui ne chiffre pas son impact paraît théorique." },
    ],
  },
  {
    slug: "cv-cto",
    title: "CV CTO (Directeur Technique)",
    category: "C-Suite",
    salaryRange: "120K€ - 300K€ + equity",
    keywords: ["cv cto", "cv directeur technique", "cv chief technology officer"],
    summary: "Le CV CTO doit équilibrer profondeur technique (stack, architecture) et leadership (équipe tech, stratégie technique, relations Board). Cible : scale-ups tech, grands groupes en transformation digitale. Évitez le piège du CV développeur sénior — le CTO pilote une stratégie technique, pas du code.",
    keySkills: ["Technical strategy", "Architecture (microservices, cloud)", "Team leadership (50+ engineers)", "Tech stack modernization", "DevOps / SRE culture", "Security & compliance", "R&D management", "Make or buy decisions"],
    achievements: [
      "Construit équipe tech de 60 ingénieurs (8 directs), stack AWS microservices",
      "Migré monolithe vers microservices, réduisant time-to-deploy de 3 semaines à 4h",
      "Réduit coûts cloud de 35% (3 M€/an) via optimisation architecture",
      "Mis en place SOC 2 Type II compliance pour scale-up US expansion",
    ],
    faq: [
      { question: "Un CV CTO doit-il montrer du code ?", answer: "Non. Le CTO ne code plus. Mentionnez les stacks pour montrer votre maîtrise technique, mais concentrez-vous sur l'architecture, l'équipe et l'impact business." },
      { question: "Equity ou salaire élevé pour un CTO ?", answer: "Dépend du stage : scale-up = equity élevé, salaire modéré. Grand groupe = salaire élevé, equity limité. Le CV peut mentionner 'stock options' sans détail." },
      { question: "Faut-il mentionner les certifications cloud (AWS/GCP) ?", answer: "Oui si récentes et pertinentes. Un CTO certifié AWS Solutions Architect Pro montre qu'il garde la main sur la technique." },
    ],
  },
  {
    slug: "cv-cmo",
    title: "CV CMO (Directeur Marketing)",
    category: "C-Suite",
    salaryRange: "130K€ - 300K€ + bonus",
    keywords: ["cv cmo", "cv directeur marketing", "cv chief marketing officer"],
    summary: "Le CV CMO doit démontrer l'impact business du marketing, pas seulement la créativité. KPIs clés : croissance du CA marketing-generated, CAC, LTV, brand awareness, ROI des campagnes. Le CMO moderne est data-driven et pilote un P&L marketing, pas juste un budget com.",
    keySkills: ["Brand strategy", "Performance marketing", "Marketing automation", "Data analytics", "Content strategy", "PR & communication", "Digital transformation", "Team leadership"],
    achievements: [
      "Piloté budget marketing de 25 M€, CA généré +38% (ROI 4.2x)",
      "Réduit CAC de 32% en 18 mois (attribution multi-touch, SEO+content)",
      "Lancé nouvelle identité de marque, brand awareness +28 pts (études BVA)",
      "Construit équipe marketing de 35 personnes (CRM, content, performance, brand)",
    ],
    faq: [
      { question: "CMO vs Directeur de la Communication ?", answer: "Le CMO pilote le P&L marketing complet (brand + perf + digital + content). Le DirCom est plus restreint (RP, image, marque employeur). Le CMO est plus stratégique." },
      { question: "Quels KPIs mettre sur un CV CMO ?", answer: "CA marketing-generated, CAC, LTV/CAC ratio, ROI par canal, brand awareness, NPS. Évitez les vanity metrics (likes, followers)." },
      { question: "Le CV CMO doit-il montrer des campagnes créatives ?", answer: "Plutôt que les créas, montrez l'impact business. 'Lancé campagne X, ROI 4.2x, +38% CA généré' est plus parlant qu'une image de campagne." },
    ],
  },
  {
    slug: "cv-chro",
    title: "CV CHRO (Directeur RH Groupe)",
    category: "C-Suite",
    salaryRange: "120K€ - 280K€ + bonus",
    keywords: ["cv chro", "cv directeur rh", "cv chief human resources officer"],
    summary: "Le CV CHRO doit démontrer l'alignement RH avec la stratégie business : transformation organisationnelle, leadership development, talent acquisition pour postes clés, culture d'entreprise, relations sociales (CSE, syndicats). Le CHRO moderne est un business partner stratégique, pas un administrateur RH.",
    keySkills: ["Strategic HR", "Organizational design", "Talent acquisition", "Leadership development", "Labor relations (CSE)", "Comp & benefits", "DEI strategy", "HR digital transformation"],
    achievements: [
      "Piloté transformation RH de 2 500 collaborateurs (5 pays), engagement +18 pts",
      "Redéfini l'organisation (passage de 6 à 4 directions), économies 8 M€/an",
      "Lancé académie leadership (300 managers formés), promotion interne +35%",
      "Négocié accord CSE (teletravail 3j/s, flexibilité), grèves -90% vs n-1",
    ],
    faq: [
      { question: "CHRO vs DRH classique ?", answer: "Le CHRO est membre du Comex, pilote la stratégie RH groupe. Le DRH peut être plus opérationnel sur une BU. Le CV CHRO doit montrer un impact stratégique." },
      { question: "Le diplôme RH est-il obligatoire pour CHRO ?", answer: "Non. Beaucoup de CHRO viennent du business (MBA) ou du consulting. Le master RH est valorisé mais pas indispensable." },
      { question: "Comment montrer l'impact RH sur un CV ?", answer: "Chiffrez : engagement, turnover, promotion interne, économies de réorg, accords signés. L'RH sans chiffres paraît 'soft'." },
    ],
  },
  {
    slug: "cv-cio",
    title: "CV CIO (Directeur des Systèmes d'Information)",
    category: "C-Suite",
    salaryRange: "130K€ - 280K€ + bonus",
    keywords: ["cv cio", "cv directeur informatique", "cv dsi"],
    summary: "Le CV CIO doit montrer la transformation digitale des SI, la rationalisation du parc applicatif, la cybersécurité et l'alignement IT/business. Distinction importante : CIO (interne, stratégique) vs CTO (produit tech). Le CIO pilote le SI d'entreprise, pas la R&D produit.",
    keySkills: ["IT strategy", "Digital transformation", "ERP (SAP, Oracle)", "Cloud migration", "Cybersecurity", "IT governance", "Vendor management", "Agile at scale"],
    achievements: [
      "Piloté migration cloud (AWS), 60 applications, économies 12 M€/an",
      "Transformé le SI (décommissionnement 30 legacy apps), time-to-market -40%",
      "Mis en place ISO 27001, zéro incident sécurité majeur en 3 ans",
      "Budget IT 45 M€ (5 directs, 200 équipe), SLA business 99.5%",
    ],
    faq: [
      { question: "CIO vs CTO ?", answer: "Le CIO pilote le SI interne (ERP, infra, sécurité). Le CTO pilote la tech du produit. Dans les grands groupes, les deux coexistent. En scale-up, souvent fusionnés." },
      { question: "Le CIO doit-il savoir coder ?", answer: "Non. Le CIO est un gestionnaire de transformation IT. Il doit comprendre l'architecture et les enjeux business, pas écrire du code." },
      { question: "Quelles certifications valoriser ?", answer: "TOGAF (architecture), ITIL (service management), CISSP/CISM (sécurité), PMP (projet). Mentionnez les plus pertinentes au poste visé." },
    ],
  },
  {
    slug: "cv-cro",
    title: "CV CRO (Chief Revenue Officer)",
    category: "C-Suite",
    salaryRange: "150K€ - 350K€ + bonus + equity",
    keywords: ["cv cro", "cv chief revenue officer", "cv directeur commercial revenue"],
    summary: "Le CV CRO doit montrer la responsabilité transversale des revenus : sales, marketing, customer success, partnerships. Particulièrement pertinent en SaaS/scale-up. Le CRO porte l'ARR/MRR/Net Retention Ratio — il doit démontrer une croissance prédictible et durable.",
    keySkills: ["Revenue operations", "Sales leadership", "Forecast accuracy", "Sales enablement", "Customer success", "Pricing strategy", "Channel partnerships", "CRM (Salesforce/HubSpot)"],
    achievements: [
      "Triplé l'ARR de 12 M€ à 38 M€ en 24 mois (NRR 142%, GRR 95%)",
      "Aligné sales+marketing+CS, conversion lead-to-customer +28%",
      "Construit équipe revenue de 45 personnes (AEs, SDRs, CSMs)",
      "Mis en place forecasting accuracy >90% (vs 60% avant)",
    ],
    faq: [
      { question: "CRO vs Directeur Commercial ?", answer: "Le CRO couvre sales+marketing+CS (P&L revenue complet). Le DirCom est souvent limité aux ventes. Le CRO est plus stratégique et data-driven." },
      { question: "Le CRO est-il un poste SaaS uniquement ?", answer: "Historiquement oui. De plus en plus de groupes traditionnels adoptent le rôle pour piloter la transformation revenue. Le CV doit adapter le vocabulaire." },
      { question: "Quels KPIs absolus sur un CV CRO ?", answer: "ARR, MRR, NRR, GRR, CAC, LTV, sales cycle, win rate. Sans ces chiffres, le CV CRO paraît incomplet." },
    ],
  },
  {
    slug: "cv-cso",
    title: "CV CSO (Chief Strategy Officer)",
    category: "C-Suite",
    salaryRange: "150K€ - 320K€ + bonus",
    keywords: ["cv cso", "cv chief strategy officer", "cv directeur stratégie"],
    summary: "Le CV CSO doit montrer la capacité à définir et exécuter la stratégie corporate : analyses de marché, M&A, partnerships, business development, corporate development. Le CSO est souvent le 'right hand' du CEO sur les sujets stratégiques. Background fréquent : consulting (McKinsey, BCG, Bain).",
    keySkills: ["Corporate strategy", "M&A", "Market analysis", "Business development", "Strategic partnerships", "Financial modeling", "Board reporting", "Competitive intelligence"],
    achievements: [
      "Défini stratégie 5 ans, pivot group vers SaaS, ARR x3 en 30 mois",
      "Piloté 5 acquisitions (120 M€ total), intégration valeur créée +180%",
      "Identifié 3 marchés adjacents, 2 lancés (CA généré 18 M€ en 18 mois)",
      "Reporting Board trimestriel, alignment CoDir sur KPIs stratégiques",
    ],
    faq: [
      { question: "CSO vs Directeur du Développement ?", answer: "Le CSO est plus stratégique (M&A, vision 5 ans). Le DirDev est plus opérationnel (BD, partnerships). Le CSO est membre du Comex, le DirDev dépend du CSO ou du CEO." },
      { question: "Le background consulting est-il obligatoire ?", answer: "Non mais fortement valorisé (McKinsey/BCG/Bain). Sinon, montrer une expérience M&A ou strategy dans un grand groupe." },
      { question: "Comment montrer l'impact stratégique sur un CV ?", answer: "M&A exécutés, nouveaux marchés ouverts, pivots stratégiques réussis. Évitez les 'analyses réalisées' — montrez les décisions prises et l'impact business." },
    ],
  },

  // ═══ DIRECTIONS FONCTIONNELLES (15) ═══
  {
    slug: "cv-directeur-commercial",
    title: "CV Directeur Commercial",
    category: "Direction",
    salaryRange: "100K€ - 250K€ + commission",
    keywords: ["cv directeur commercial", "cv sales director", "exemple cv directeur commercial"],
    summary: "Le CV Directeur Commercial doit montrer la capacité à piloter une équipe commerciale, atteindre les objectifs de CA et construire un machine sales prédictible. KPIs clés : CA réalisé vs target, taux de conversion, sales cycle, taille d'équipe, expansion géographique.",
    keySkills: ["Sales leadership", "Forecasting", "Sales methodology (MEDDIC, Challenger)", "Team building", "CRM (Salesforce)", "Pipeline management", "Negotiation", "Account-based selling"],
    achievements: [
      "Piloté équipe commerciale de 35 personnes, CA 85 M€ (+22% vs n-1)",
      "Déployé méthode MEDDIC, win rate +18 pts en 12 mois",
      "Ouvert 2 pays (Espagne, Italie), CA généré 12 M€ en 18 mois",
      "Réduit sales cycle de 90 à 65 jours, conversion +24%",
    ],
    faq: [
      { question: "Quels KPIs mettre sur un CV Directeur Commercial ?", answer: "CA réalisé vs target, taille équipe, win rate, sales cycle, expansion géographique. Toujours chiffrer." },
      { question: "Méthode sales à mentionner ?", answer: "MEDDIC, Challenger, SPIN, Solution Selling. Mentionnez celle déployée avec impact mesuré." },
      { question: "Le CV doit-il mentionner le secteur ?", answer: "Oui, c'est crucial. Un DirCom SaaS n'est pas un DirCom industrie. Mentionnez clairement le vertical." },
    ],
  },
  {
    slug: "cv-directeur-industriel",
    title: "CV Directeur Industriel",
    category: "Direction",
    salaryRange: "100K€ - 220K€ + bonus",
    keywords: ["cv directeur industriel", "cv industrial director", "cv directeur production"],
    summary: "Le CV Directeur Industriel doit montrer la maîtrise des opérations industrielles : production, supply chain, qualité, maintenance, HSE. KPIs clés : OEE, OTD, taux de rebut, TRS, coûts unitaires. Le Directeur Industriel moderne pilote l'usine 4.0 (IoT, IA, automation).",
    keySkills: ["Production management", "Lean Manufacturing", "Six Sigma Black Belt", "Supply chain", "Quality ISO 9001", "HSE management", "Industry 4.0", "Plant management"],
    achievements: [
      "Dirigé 3 usines (800 personnes), CA 180 M€, OEE 82% (vs 68% n-1)",
      "Réduit taux de rebut de 4.2% à 1.8%, économies 6 M€/an",
      "Déployé Industrie 4.0 (IoT + IA prédictive), disponibilité machines +12 pts",
      "Zéro accident avec arrêt en 2 ans (vs 8 n-1), certification ISO 45001",
    ],
    faq: [
      { question: "Lean Six Sigma obligatoire ?", answer: "Black Belt ou Master Black Belt est très valorisé. Green Belt minimum pour postes seniors. Mentionnez les certifications." },
      { question: "Le Directeur Industriel doit-il être ingénieur ?", answer: "Majoritairement oui (école d'ingénieur). Mais des profils École de Commerce + expérience terrain existent, surtout dans le retail/CPG." },
      { question: "HSE est-il important sur le CV ?", answer: "Très. Mentionnez les certifications (ISO 45001) et l'amélioration des taux d'accidents. C'est un sujet sensible pour les recruteurs industriels." },
    ],
  },
  {
    slug: "cv-directeur-supply-chain",
    title: "CV Directeur Supply Chain",
    category: "Direction",
    salaryRange: "95K€ - 200K€ + bonus",
    keywords: ["cv directeur supply chain", "cv supply chain director", "cv logistique"],
    summary: "Le CV Directeur Supply Chain doit montrer la maîtrise de bout en bout : planification, achats, logistique, distribution, S&OP. KPIs clés : OTD, inventory turnover, cash-to-cash, coûts logistiques en % du CA. La supply chain moderne pilote la résilience post-COVID.",
    keySkills: ["S&OP process", "Demand planning", "Procurement", "Logistics", "Inventory management", "ERP (SAP)", "Lean supply chain", "Supplier management"],
    achievements: [
      "Piloté supply chain groupe (5 pays, 12 sites), OTD 96% (+8 pts)",
      "Réduit stocks de 32 M€ à 22 M€ (rotation x1.4), service maintenu",
      "Restructuré réseau logistique, économies 8 M€/an",
      "Déployé S&OP mensuel, forecast accuracy 88% (vs 65%)",
    ],
    faq: [
      { question: "Supply chain vs Logistique ?", answer: "La supply chain est end-to-end (plan, source, make, deliver). La logistique est un sous-ensemble (transport, entreposage). Le CV Directeur SC doit montrer la vision complète." },
      { question: "S&OP est-il important à mentionner ?", answer: "Très. Le S&OP (Sales & Operations Planning) est un différenciateur clé pour un poste senior. Mentionnez la cadence et l'impact." },
      { question: "Quels outils mentionner ?", answer: "SAP (SCM, IBP), Oracle, Kinaxis, Blue Yonder. Mentionnez votre maîtrise et l'impact business (forecast accuracy, OTD)." },
    ],
  },
  {
    slug: "cv-directeur-juridique",
    title: "CV Directeur Juridique",
    category: "Direction",
    salaryRange: "120K€ - 250K€ + bonus",
    keywords: ["cv directeur juridique", "cv general counsel", "cv legal director"],
    summary: "Le CV Directeur Juridique doit montrer la maîtrise du droit des affaires, corporate, contrats, conformité, contentieux, propriété intellectuelle. Le General Counsel moderne est un business partner stratégique, pas seulement un juriste. Mentionnez les barreaux ou certifications.",
    keySkills: ["Corporate law", "M&A legal", "Contract law", "Compliance (Sapin 2, RGPD)", "Litigation management", "IP/IT law", "Regulatory affairs", "Legal tech"],
    achievements: [
      "Piloté cadre juridique de 5 acquisitions (120 M€), zéro litige post-closing",
      "Mis en place programme conformité Sapin 2, zéro sanction autorité",
      "Restructuré 12 filiales européennes, économies 2 M€/an",
      "Construit équipe juridique de 12 personnes (3 avocats internes)",
    ],
    faq: [
      { question: "Le CAPA (barreau) est-il obligatoire ?", answer: "Non mais très valorisé. Mentionnez-le si vous l'avez. Sinon, mettez en avant les masters spécialisés et l'expérience." },
      { question: "Compliance vs Legal ?", answer: "Compliance (Sapin 2, RGPD, sanctions) devient un métier distinct. Le CV doit montrer les deux dimensions ou se positionner clairement." },
      { question: "Legal tech à mentionner ?", answer: "Oui, c'est un signal de modernité. Mentionnez les outils déployés (Contract Lifecycle Management, e-discovery, etc.)." },
    ],
  },
  {
    slug: "cv-directeur-risques",
    title: "CV Directeur des Risques",
    category: "Direction",
    salaryRange: "120K€ - 240K€ + bonus",
    keywords: ["cv directeur des risques", "cv chief risk officer", "cv risk management"],
    summary: "Le CV Directeur des Risques doit montrer la maîtrise des risques : financiers, opérationnels, stratégiques, de conformité, cyber. Particulièrement pertinent en banque/assurance. KPIs : exposés, provisions, ratios réglementaires (Bâle, Solvabilité).",
    keySkills: ["Risk framework (COSO, ISO 31000)", "Operational risk", "Credit risk", "Market risk", "Regulatory (Bâle, Solvabilité 2)", "Stress testing", "Risk appetite", "Internal control"],
    achievements: [
      "Piloté cadre risque groupe (3 500 personnes, bilan 12 Mds€)",
      "Réduit coût du risque de 18%, économies 22 M€/an",
      "Mis en place stress tests (EBA), validation ACPR sans réserve",
      "Construit équipe risque de 18 personnes, mapping 360 risques",
    ],
    faq: [
      { question: "Quelle certification pour Directeur Risques ?", answer: "FRM (Financial Risk Manager) est la référence internationale. PRM (Professional Risk Manager) aussi. Mentionnez-les si vous les avez." },
      { question: "Risk manager vs Compliance officer ?", answer: "Risk couvre les risques (financiers, opérationnels). Compliance couvre la conformité réglementaire. Souvent fusionnés en Risk & Compliance." },
      { question: "Banque vs Assurance ?", answer: "Les frameworks diffèrent (Bâle vs Solvabilité 2). Mentionnez clairement votre univers pour éviter les confusions." },
    ],
  },
  {
    slug: "cv-directeur-transformation",
    title: "CV Directeur de la Transformation",
    category: "Direction",
    salaryRange: "130K€ - 280K€ + bonus",
    keywords: ["cv directeur transformation", "cv transformation director", "cv chief transformation officer"],
    summary: "Le CV Directeur de la Transformation doit montrer la capacité à piloter des programmes transverses : digital, orga, cultural, operating model. Background fréquent : consulting (McKinsey, BCG, Accenture). Le Chief Transformation Officer est souvent nommé pour 2-3 ans sur une mission.",
    keySkills: ["Transformation strategy", "Change management", "Operating model design", "Process reengineering", "Program management (PMO)", "Cultural transformation", "Digital initiatives", "Stakeholder management"],
    achievements: [
      "Piloté plan de transformation 80 M€ (digital + orga), 220 M€ valeur créée",
      "Transformé 5 directions (1 200 personnes), économies 35 M€/an",
      "Déployé culture agile (300 personnes formées), time-to-market -45%",
      "Mis en place PMO groupe (15 projets transverses), délai moyen -30%",
    ],
    faq: [
      { question: "Transformation vs PMO ?", answer: "Le Directeur Transformation définit la stratégie et les programmes. Le PMO exécute. Le CV Directeur Transformation doit montrer les deux dimensions." },
      { question: "Le background consulting est-il attendu ?", answer: "Très souvent oui (McKinsey, BCG, Bain, Accenture, Deloitte). Sinon, montrer des rôles internes de transformation réussis." },
      { question: "Comment montrer l'impact ?", answer: "Valeur créée (M€), coûts évités, adoption (utilisateurs), cultural shift (engagement, NPS). Chiffrer systématiquement." },
    ],
  },
  {
    slug: "cv-directeur-digital",
    title: "CV Directeur Digital / CDO",
    category: "Direction",
    salaryRange: "110K€ - 250K€ + bonus",
    keywords: ["cv directeur digital", "cv chief digital officer", "cv cdo"],
    summary: "Le CV Directeur Digital doit montrer la transformation digitale d'une organisation legacy : e-commerce, marketing digital, data, IA, automation. Distinction : CDO (transformation digitale business) vs CIO (SI interne). Le CDO moderne pilote l'innovation business, pas seulement la tech.",
    keySkills: ["Digital strategy", "E-commerce", "Digital marketing", "Data strategy", "AI/ML adoption", "Customer experience", "Digital KPIs", "Intrapreneurship"],
    achievements: [
      "Piloté transformation digitale, CA digital 0 → 28% du CA groupe en 3 ans",
      "Lancé e-commerce (12 M€ CA an 1, 45 M€ an 3), 18% marge",
      "Mis en place data platform (BigQuery), 30 use cases IA en production",
      "Transformé customer experience, NPS +24 pts, churn -28%",
    ],
    faq: [
      { question: "CDO vs CIO vs CTO ?", answer: "CDO = transformation digitale business. CIO = SI interne. CTO = tech produit. Souvent confondus. Le CV doit clarifier le scope." },
      { question: "Le CDO doit-il savoir coder ?", answer: "Non. Le CDO est un business leader avec forte culture tech. Il doit comprendre l'architecture, la data et l'IA, sans coder." },
      { question: "Quels KPIs pour CDO ?", answer: "CA digital %, conversion, NPS, churn, coûts digitaux vs bénéfices, adoption IA, data products lancés." },
    ],
  },
  {
    slug: "cv-directeur-data",
    title: "CV Directeur Data / CDO",
    category: "Direction",
    salaryRange: "110K€ - 240K€ + bonus",
    keywords: ["cv directeur data", "cv chief data officer", "cv cdo data"],
    summary: "Le CV Directeur Data doit montrer la stratégie data : gouvernance, qualité, plateforme, use cases IA/ML, data science. Distinction : CDO Data (stratégie data) vs CDO Digital (transformation digitale). Le CDO Data moderne pilote l'activation business de la data.",
    keySkills: ["Data strategy", "Data governance", "Data platform (cloud, lakehouse)", "Data science", "AI/ML", "Data engineering", "Privacy & ethics", "Self-service BI"],
    achievements: [
      "Construit data platform (Snowflake + dbt), 50 use cases IA en production",
      "Activé 30 M€ de valeur data (fraude, churn, pricing, recommandation)",
      "Mis en place gouvernance data (stewards, dictionnaire), qualité +35%",
      "Construit équipe data de 25 personnes (DE, DS, DA, governance)",
    ],
    faq: [
      { question: "CDO Data vs Chief Data Scientist ?", answer: "Le CDO Data pilote la stratégie data complète (gouvernance, plateforme, use cases). Le CDS est plus technique (modèles, R&D). Le CV CDO doit montrer la vision business." },
      { question: "Le CDO Data doit-il être ingénieur ?", answer: "Pas obligatoirement. Un background business + forte culture data suffit. Mais la maîtrise des architectures modernes (lakehouse, ML ops) est cruciale." },
      { question: "Quelles stacks à mentionner ?", answer: "Snowflake, BigQuery, Databricks, dbt, Airflow, MLflow, SageMaker. Mentionnez celles déployées avec impact." },
    ],
  },
  {
    slug: "cv-directeur-achats",
    title: "CV Directeur des Achats",
    category: "Direction",
    salaryRange: "100K€ - 220K€ + bonus",
    keywords: ["cv directeur achats", "cv procurement director", "cv chief procurement officer"],
    summary: "Le CV Directeur des Achats doit montrer la maîtrise stratégique : sourcing, négociation, gestion fournisseurs, achats responsables. KPIs clés : savings en M€, % spend under management, supplier performance, supplier diversity. Les achats modernes intègrent ESG et résilience.",
    keySkills: ["Strategic sourcing", "Negotiation", "Supplier management", "Category management", "Procure-to-pay", "ESG procurement", "Digital procurement (Coupa, SAP Ariba)", "Risk management"],
    achievements: [
      "Piloté achats groupe (320 M€ spend), savings 28 M€ (8.7% du spend)",
      "Restructuré 12 catégories, spend under management 85% (vs 55%)",
      "Mis en place politique RSE achats, 35% fournisseurs certifiés (vs 12%)",
      "Déployé Coupa (e-procurement), délai cycle achat -45%",
    ],
    faq: [
      { question: "Le Directeur Achats doit-il avoir un profil acheteur pur ?", answer: "Majoritairement oui. Mais des profils consulting ou finance sont valorisés pour les postes de CPO groupe. Mentionnez les savings en M€." },
      { question: "Quelle certification pour CPO ?", answer: "CIPS (Chartered Institute of Procurement) est la référence internationale. Mentionnez le niveau (MCIPS especially)." },
      { question: "ESG dans les achats ?", answer: "Devenu crucial. Mentionnez votre stratégie (supplier diversity, scope 3 emissions, certification). C'est un différenciateur fort en 2026." },
    ],
  },
  {
    slug: "cv-directeur-qualite",
    title: "CV Directeur Qualité",
    category: "Direction",
    salaryRange: "85K€ - 180K€ + bonus",
    keywords: ["cv directeur qualité", "cv quality director", "cv qualité"],
    summary: "Le CV Directeur Qualité doit montrer la maîtrise des systèmes qualité : ISO 9001, sectoriels (ISO 13485, IATF 16949, ESD), amélioration continue (Lean Six Sigma), audits. KPIs : taux de non-conformité, coûts de non-qualité, certifications maintenues.",
    keySkills: ["Quality management system", "ISO 9001 / 14001 / 45001", "Sector-specific (IATF, ISO 13485)", "Six Sigma Black Belt", "Audit management", "Continuous improvement", "CAPA", "Risk-based quality"],
    achievements: [
      "Piloté QMS multi-sites (8 sites, 3 pays), zéro non-conformité majeure",
      "Réduit coûts de non-qualité de 4.2% à 1.8% du CA, économies 12 M€/an",
      "Obtenu certification IATF 16949, renouvellement sans écart",
      "Déployé Lean Six Sigma (15 Green Belts, 4 Black Belts formés)",
    ],
    faq: [
      { question: "Le Black Belt est-il obligatoire ?", answer: "Très valorisé, surtout en industrie. Green Belt minimum pour postes seniors. Black Belt pour Directeur Qualité groupe." },
      { question: "Qualité vs HSE ?", answer: "Souvent fusionnés en QHSE. Si distincts, le CV Qualité se concentre sur conformité produit et process. Le HSE gère sécurité et environnement." },
      { question: "Certifications sectorielles ?", answer: "Selon le secteur : IATF 16949 (auto), ISO 13485 (medical), ESD (électronique), AS9100 (aéro). Mentionnez celles pertinentes." },
    ],
  },
  {
    slug: "cv-directeur-filiale",
    title: "CV Directeur de Filiale",
    category: "Direction",
    salaryRange: "100K€ - 250K€ + bonus + intéressement",
    keywords: ["cv directeur filiale", "cv branch manager", "cv directeur regional"],
    summary: "Le CV Directeur de Filiale doit montrer la responsabilité P&L complète d'une entité géographique ou business unit. Souvent un tremplin vers un poste de DG. KPIs : CA filiale, EBITDA, part de marché locale, équipe managée.",
    keySkills: ["P&L management", "Local market strategy", "Team leadership", "Sales development", "Operations management", "Stakeholder management (HQ + local)", "Regulatory compliance", "Cultural adaptation"],
    achievements: [
      "Dirigé filiale Espagne (180 personnes, CA 65 M€), croissance +32% en 3 ans",
      "Restructuré organisation commerciale, part de marché +4 pts (12% → 16%)",
      "Négocié 2 accords stratégiques locaux, CA généré 14 M€/an",
      "Équipe managée (8 directs), engagement 78% (top quartile groupe)",
    ],
    faq: [
      { question: "Directeur Filiale vs Country Manager ?", answer: "Similaires. Le Country Manager est souvent pour une filiale pays entière. Le Directeur Filiale peut être sur une BU ou une zone. Le CV doit clarifier le scope." },
      { question: "Faut-il parler la langue locale ?", answer: "Très fortement recommandé, sinon obligatoire. Un Directeur Filiale Espagne qui ne parle pas espagnol est rare. Mentionnez le niveau (C1/C2)." },
      { question: "Comment montrer l'autonomie ?", answer: "Décisions stratégiques prises localement, budget géré, reporting direct au HQ. Montrez que vous êtes 'CEO de votre filiale'." },
    ],
  },
  {
    slug: "cv-directeur-audit",
    title: "CV Directeur de l'Audit Interne",
    category: "Direction",
    salaryRange: "100K€ - 220K€ + bonus",
    keywords: ["cv directeur audit", "cv audit director", "cv internal audit"],
    summary: "Le CV Directeur Audit Interne doit montrer la maîtrise du cadre audit (IIA, COSO), du risk-based auditing et de la gouvernance. Souvent un tremplin vers Directeur Risques ou Compliance. Background fréquent : Big 4 (EY, PwC, Deloitte, KPMG).",
    keySkills: ["Internal audit (IIA)", "Risk-based auditing", "COSO framework", "SOX compliance", "Fraud auditing", "Audit reporting (Board)", "Team leadership", "Data analytics for audit"],
    achievements: [
      "Piloté audit interne groupe (35 auditeurs, 80 missions/an)",
      "Identifié 220 M€ de risques potentiels, plans d'action déployés",
      "Mis en place data analytics (ACL, Power BI), couverture audit +45%",
      "Reporting Board trimestriel, satisfaction stakeholders 92%",
    ],
    faq: [
      { question: "Le CIA (Certified Internal Auditor) est-il obligatoire ?", answer: "Très valorisé, surtout pour postes seniors. Mentionnez-le. Le CPA/ACCA est aussi bien perçu." },
      { question: "Audit interne vs Big 4 ?", answer: "Big 4 = audit externe (comptable). Audit interne = contrôle interne et risques. Les profils Big 4 sont valorisés mais doivent s'adapter au mindset interne." },
      { question: "Comment montrer l'impact ?", answer: "Risques identifiés, plans d'action déployés (et suivis), économies réelles, recommandations acceptées par le Board." },
    ],
  },
  {
    slug: "cv-directeur-conformite",
    title: "CV Directeur de la Conformité",
    category: "Direction",
    salaryRange: "110K€ - 240K€ + bonus",
    keywords: ["cv directeur conformité", "cv compliance officer", "cv chief compliance officer"],
    summary: "Le CV Directeur Conformité doit montrer la maîtrise des réglementations (Sapin 2, RGPD, sanctions, ACPR/AMF), du programme conformité et de la culture éthique. Surtout pertinent en banque, assurance, pharma, énergie. Le Compliance Officer moderne pilote l'éthique beyond compliance.",
    keySkills: ["Compliance framework", "Sapin 2 / Sapin 3", "RGPD / Data privacy", "Sanctions internationales", "AML / KYC", "Ethics program", "Regulatory watch", "Training & awareness"],
    achievements: [
      "Piloté programme conformité groupe (2 500 personnes), zéro sanction autorité",
      "Mis en place Sapin 2 (cartographie 180 risques, 25 investigations)",
      "Réduit incidents RGPD de 70%, DLPO formé dans chaque direction",
      "Construit équipe compliance de 14 personnes, satisfaction Board 95%",
    ],
    faq: [
      { question: "Compliance vs Risk ?", answer: "Compliance = conformité réglementaire. Risk = risques financiers/opérationnels. Souvent fusionnés (Risk & Compliance). Le CV doit clarifier le scope." },
      { question: "Quelle certification pour Compliance Officer ?", answer: "CCEP (Certified Compliance & Ethics Professional) international. ICA (International Compliance Association) en UK/EU. Mentionnez-les." },
      { question: "Le Compliance Officer est-il un juriste ?", answer: "Pas obligatoirement. Beaucoup viennent de l'audit, du risque ou du contrôle interne. Le mindset est plus process que juridique." },
    ],
  },
  {
    slug: "cv-directeur-communication",
    title: "CV Directeur de la Communication",
    category: "Direction",
    salaryRange: "100K€ - 220K€ + bonus",
    keywords: ["cv directeur communication", "cv communication director", "cv dircom"],
    summary: "Le CV Directeur Communication doit montrer la stratégie de marque employeur, RP, communication interne/externe, crises. KPIs : share of voice, NPS employés, sentiment media, taux de notoriété. Le DirCom moderne gère aussi la réputation digitale.",
    keySkills: ["Corporate communication", "Brand reputation", "Media relations", "Internal communication", "Crisis com", "Employer branding", "Digital PR", "Public affairs"],
    achievements: [
      "Piloté communication groupe (5 pays), share of voice +18 pts",
      "Géré 3 crises médiatiques (zéro impact réputation long-terme)",
      "Lancé marque employeur, candidatures +45%, coût recrutement -22%",
      "Construit équipe com de 18 personnes (RP, digital, interne, events)",
    ],
    faq: [
      { question: "DirCom vs CMO ?", answer: "Le CMO pilote le P&L marketing (CA généré). Le DirCom pilote la réputation et l'image. Les deux coexistent en grands groupes. Le CV doit clarifier le scope." },
      { question: "Le DirCom doit-il avoir un background journalisme ?", answer: "Pas obligatoire. Beaucoup viennent de Sciences Po, marketing ou affaires publiques. Le journalisme est valorisé pour les RP." },
      { question: "Comment montrer l'impact com ?", answer: "Share of voice, sentiment, NPS, crise évitée, candidatures générées. Évitez les vanity metrics (followers, likes sans contexte)." },
    ],
  },

  // ═══ INTERNATIONAL (10) ═══
  {
    slug: "cv-country-manager",
    title: "CV Country Manager",
    category: "International",
    salaryRange: "130K€ - 300K€ + bonus + equity",
    keywords: ["cv country manager", "cv country head", "cv general manager country"],
    summary: "Le CV Country Manager doit montrer la responsabilité complète d'un pays : P&L, stratégie locale, équipe, régulations, partnerships. Souvent un DG en puissance. Distinction : Country Manager (pays mature) vs Country Launcher (pays à créer from scratch).",
    keySkills: ["Country P&L", "Market entry strategy", "Local team building", "Regulatory navigation", "Cultural adaptation", "Partnership development", "HQ reporting", "Talent development"],
    achievements: [
      "Lancé filiale Allemagne (0 → 65 M€ CA en 36 mois, 80 personnes)",
      "Négocié 3 partnerships stratégiques (dont 1 DAX30), CA généré 18 M€",
      "Adapté offre produit au marché local, win rate +28%",
      "Équipe managée (8 directs), promotion interne de 2 successeurs",
    ],
    faq: [
      { question: "Country Manager vs CEO filiale ?", answer: "Très similaires. Le Country Manager est souvent pour une filiale d'un groupe international. Le CEO filiale peut être plus autonome. Le CV doit montrer l'autonomie réelle." },
      { question: "La langue locale est-elle obligatoire ?", answer: "Oui, sauf exceptions (startups tech avec équipe internationale). Pour l'Allemagne, l'espagnol, le portugais — la langue locale est cruciale." },
      { question: "Country Launcher vs Country Manager ?", answer: "Launcher = pays à créer (0 → 1). Manager = pays mature à développer (1 → 10). Le CV doit clarifier l'expérience." },
    ],
  },
  {
    slug: "cv-managing-director",
    title: "CV Managing Director",
    category: "International",
    salaryRange: "180K€ - 450K€ + bonus + equity",
    keywords: ["cv managing director", "cv md", "cv directeur general international"],
    summary: "Le CV Managing Director (MD) est l'équivalent international du DG. Souvent dans les cabinets de conseil (MD office), finance (MD coverage) ou multinationales (MD region). Le MD porte la responsabilité ultime d'une entité géographique ou business.",
    keySkills: ["P&L ownership", "Regional strategy", "Client relationships (key accounts)", "Senior team leadership", "Regulatory navigation", "M&A regional", "Public representation", "Crisis management"],
    achievements: [
      "Dirigé région EMEA (1 800 personnes, CA 380 M€), croissance +24%",
      "Piloté 4 acquisitions régionales (95 M€), intégration valeur +160%",
      "Construit 3 nouvelles BU locales, CA généré 32 M€ en 24 mois",
      "Équipe managée (12 directs), engagement 82% (top quartil groupe)",
    ],
    faq: [
      { question: "MD vs CEO ?", answer: "Dans les cabinets de conseil/finance, MD = top grade avant Partner. Dans les multinationales, MD = DG d'une région. Le CV doit clarifier le contexte." },
      { question: "MD coverage (banque) vs MD office (consulting) ?", answer: "Différents. MD coverage gère des clients. MD office gère un bureau/cabinet. Le CV doit montrer les deux si possible." },
      { question: "Le MD doit-il être local ?", answer: "Très souvent oui, surtout en consulting et finance. La connaissance du marché local est cruciale. Le CV doit montrer l'ancrage local." },
    ],
  },
  {
    slug: "cv-vice-president",
    title: "CV Vice-Président (VP)",
    category: "International",
    salaryRange: "140K€ - 350K€ + bonus + equity",
    keywords: ["cv vice président", "cv vp", "cv vice president"],
    summary: "Le titre Vice-Président (VP) est utilisé dans les multinationales US et banques d'investissement. En France, équivaut à Directeur Senior. Le CV VP doit montrer un scope large, un impact business majeur et une équipe significative.",
    keySkills: ["Strategic leadership", "Cross-functional management", "Board-level reporting", "M&A execution", "Stakeholder management", "P&L responsibility", "Talent development", "Change leadership"],
    achievements: [
      "VP EMEA Strategy (1 200 personnes, CA 280 M€), croissance +28%",
      "Piloté 6 M&A (180 M€), intégration synergie +180%",
      "Transformé 4 BU, économies 22 M€/an",
      "Équipe managée (10 directs VPs/Directors), promotion interne +35%",
    ],
    faq: [
      { question: "VP vs Directeur ?", answer: "Dans les structures US, VP = niveau au-dessus de Director. En France, souvent équivalent à Directeur Senior. Le CV doit clarifier la structure organisationnelle." },
      { question: "SVP vs EVP vs VP ?", answer: "VP < SVP < EVP < C-suite. EVP est membre du C-suite étendu. Le CV doit mentionner le niveau exact pour éviter les confusions." },
      { question: "Comment montrer l'impact VP ?", answer: "Scope managé (équipes, CA), M&A, transformations. Le VP est attendu sur des impacts stratégiques, pas opérationnels." },
    ],
  },
  {
    slug: "cv-area-manager",
    title: "CV Area Manager (Directeur de Zone)",
    category: "International",
    salaryRange: "100K€ - 220K€ + bonus",
    keywords: ["cv area manager", "cv directeur de zone", "cv regional director"],
    summary: "Le CV Area Manager (Directeur de Zone) doit montrer la responsabilité d'une zone géographique (Europe Sud, Asie Pacifique, etc.). Souvent dans le retail, FMCG, pharma. KPIs : CA zone, part de marché, expansion réseaux.",
    keySkills: ["Regional P&L", "Market development", "Distributor management", "Retail expansion", "Local team leadership", "Cross-cultural management", "Trade marketing", "Regulatory compliance"],
    achievements: [
      "Dirigé zone Europe Sud (Espagne, Italie, Portugal), CA 85 M€ (+22%)",
      "Ouvert 120 points de vente, CA généré 18 M€ en 24 mois",
      "Restructuré réseau distributeurs, marge zone +5 pts",
      "Équipe managée (5 Country Managers), engagement 84%",
    ],
    faq: [
      { question: "Area Manager vs Country Manager ?", answer: "L'Area Manager supervise plusieurs Country Managers sur une zone. Le Country Manager gère un pays unique. Le CV doit montrer le scope multi-pays." },
      { question: "Quelles zones sont les plus valorisées ?", answer: "EMEA, APAC et LATAM sont les plus demandées. La Chine seule est souvent un Country Manager. Le CV doit préciser les pays couverts." },
      { question: "Bilingue obligatoire ?", answer: "Anglais obligatoire. La langue de la zone est un plus fort (espagnol pour LATAM, mandarin pour Chine, etc.)." },
    ],
  },
  {
    slug: "cv-expatrie",
    title: "CV Cadre Expatrié",
    category: "International",
    salaryRange: "Variable selon pays (premium 20-40%)",
    keywords: ["cv cadre expatrié", "cv expat", "cv cadre international"],
    summary: "Le CV Cadre Expatrié doit montrer l'expérience internationale (mobilité, adaptation culturelle, expériences multi-pays). Particulièrement pertinent pour les retours d'expatriation en France ou pour de nouvelles mobilités. Mentionnez les visas et langues maîtrisées.",
    keySkills: ["Cross-cultural leadership", "Multi-country experience", "Language skills (3+)", "Mobility readiness", "Local market understanding", "Diplomatic skills", "Adaptability", "Global mindset"],
    achievements: [
      "3 expatriations réussies (Chine 4 ans, Brésil 3 ans, Singapour 2 ans)",
      "Dirigé équipes multi-culturelles (15 nationalités, 220 personnes)",
      "Maîtrise 4 langues (FR, EN, ES, Mandarin C1)",
      "Visas de travail obtenus (Chine Z, Brésil VITEM-V, Singapour EP)",
    ],
    faq: [
      { question: "Comment présenter une expatriation sur un CV ?", answer: "Mentionnez le pays, la durée, le rôle et l'impact local. Ex: 'Country Manager Chine (Shanghai) 2020-2024, CA 45 M€, 80 personnes'." },
      { question: "Le retour d'expatriation est-il difficile ?", answer: "Oui, souvent. Le CV doit montrer que l'expérience internationale est un atout (pas une 'parenthèse'). Mettez en avant l'impact business mesurable." },
      { question: "Faut-il mentionner les visas ?", answer: "Oui, surtout si vous postulez à nouveau à l'international. Mentionnez les visas obtenus (H1-B, EU Blue Card, etc.)." },
    ],
  },
  {
    slug: "cv-directeur-europe",
    title: "CV Directeur Europe",
    category: "International",
    salaryRange: "150K€ - 320K€ + bonus",
    keywords: ["cv directeur europe", "cv europe director", "cv vp europe"],
    summary: "Le CV Directeur Europe doit montrer la responsabilité d'une région Europe (multi-pays). Souvent un poste de transition vers Group Executive. Distinction : Europe Ouest (mature) vs Europe Centrale/Orientale (en croissance).",
    keySkills: ["European P&L", "Multi-country leadership", "Cross-cultural management", "European regulation", "Multi-language", "Regional HQ management", "Country managers leadership", "Regional M&A"],
    achievements: [
      "Dirigé Europe (12 pays, 1 200 personnes, CA 220 M€, +18%)",
      "Restructuré 5 filiales, économies 15 M€/an",
      "Piloté 2 acquisitions régionales (45 M€), intégration valeur +120%",
      "Équipe managée (5 Country Managers + 4 fonctionnels)",
    ],
    faq: [
      { question: "Directeur Europe vs VP Europe ?", answer: "Très similaires. Le titre VP est plus US/multinationale. Directeur Europe est plus français. Le CV doit montrer le scope réel." },
      { question: "Europe Ouest vs Centrale ?", answer: "Marchés matures (FR, DE, UK, IT, ES) vs marchés en croissance (PL, CZ, RO, HU). Le CV doit préciser la zone exacte." },
      { question: "Langues requises ?", answer: "Anglais obligatoire + idéalement 1-2 autres langues européennes. Le multilinguisme est un différenciateur fort." },
    ],
  },
  {
    slug: "cv-directeur-ameriques",
    title: "CV Directeur Amériques",
    category: "International",
    salaryRange: "180K€ - 380K€ + bonus",
    keywords: ["cv directeur ameriques", "cv americas director", "cv vp americas"],
    summary: "Le CV Directeur Amériques doit montrer la responsabilité d'une région Amériques (US, Canada, LATAM). Souvent un poste senior basé à Miami, New York, Mexico ou São Paulo. Le marché US est le plus stratégique — l'expérience US est très valorisée.",
    keySkills: ["Americas P&L", "US market expertise", "LATAM expansion", "Multi-cultural leadership", "Cross-border regulation", "US GAAP", "English/Spanish/Portuguese", "Regional strategy"],
    achievements: [
      "Dirigé Amériques (US, Canada, Mexique, Brésil), CA 180 M€ (+32%)",
      "Lancé 2 BU US (New York, Miami), CA généré 38 M€ en 30 mois",
      "Piloté 3 acquisitions LATAM (45 M€), intégration valeur +160%",
      "Équipe managée (8 Country/BU Managers)",
    ],
    faq: [
      { question: "Directeur Amériques vs VP Americas ?", answer: "Similaires. VP Americas est plus courant dans les multinationales US. Le CV doit préciser le scope pays exact." },
      { question: "US vs LATAM ?", answer: "Marchés très différents. US = mature, compétitif, cycle long. LATAM = croissance, complexité, opportunités. Le CV doit montrer l'expérience sur les deux." },
      { question: "Faut-il être basé aux US ?", answer: "Pas obligatoire mais recommandé pour les postes seniors. Sinon, mentionnez la fréquence des déplacements (50%+)." },
    ],
  },
  {
    slug: "cv-directeur-apac",
    title: "CV Directeur APAC",
    category: "International",
    salaryRange: "180K€ - 400K€ + bonus + housing",
    keywords: ["cv directeur apac", "cv asia pacific director", "cv vp apac"],
    summary: "Le CV Directeur APAC (Asie-Pacifique) doit montrer la responsabilité d'une région très dynamique. Souvent basé à Singapour, Hong Kong, Shanghai ou Tokyo. L'expérience asiatique est très valorisée — la compréhension culturelle est clé.",
    keySkills: ["APAC P&L", "Asian market expertise", "Cross-cultural leadership", "Government relations", "Multi-language (English + 1 Asian)", "Regional HQ management", "JV partnerships", "Regional supply chain"],
    achievements: [
      "Dirigé APAC (8 pays, 800 personnes, CA 145 M€, +42%)",
      "Lancé 3 JV locales (Chine, Japon, Inde), CA généré 28 M€",
      "Restructuré supply chain régionale, économies 8 M€/an",
      "Équipe managée (6 Country Managers + 3 fonctionnels)",
    ],
    faq: [
      { question: "Singapour vs Hong Kong vs Shanghai ?", answer: "Singapour = hub SEA, fiscal avantageux. Hong Kong = hub Greater China (en transition). Shanghai = marché Chine direct. Le CV doit préciser le lieu." },
      { question: "Langues asiatiques ?", answer: "Anglais business suffisant à Singapour/HK. Mandarin très valorisé pour Chine. Japonais/coréen pour ces marchés. Le CV doit mentionner le niveau." },
      { question: "Le package expat est-il inclus ?", answer: "Oui en général (housing, schooling, flights). Mentionnez si pertinent. En 2026, de plus en plus de 'local plus' (sans package expat complet)." },
    ],
  },
  {
    slug: "cv-directeur-emea",
    title: "CV Directeur EMEA",
    category: "International",
    salaryRange: "180K€ - 380K€ + bonus",
    keywords: ["cv directeur emea", "cv emea director", "cv vp emea"],
    summary: "Le CV Directeur EMEA (Europe, Middle East, Africa) doit montrer la responsabilité d'une région très diverse (50+ pays). Souvent basé à Londres, Paris, Dubaï ou Genève. La complexité EMEA (multi-réglementations, multi-langues) est un atout différenciant.",
    keySkills: ["EMEA P&L", "Multi-region strategy", "Cross-cultural leadership", "Multi-regulation expertise", "Multi-language", "Regional HQ management", "Key account management", "Regional partnerships"],
    achievements: [
      "Dirigé EMEA (28 pays, 1 800 personnes, CA 320 M€, +22%)",
      "Lancé 4 nouvelles filiales (UAE, Arabie, Nigeria, Pologne), CA 25 M€",
      "Restructuré 8 filiales matures, économies 18 M€/an",
      "Équipe managée (12 Country Managers + 5 fonctionnels)",
    ],
    faq: [
      { question: "EMEA vs Europe ?", answer: "EMEA inclut l'Europe + Moyen-Orient + Afrique. Plus large et complexe. Le CV doit montrer la gestion de cette diversité." },
      { question: "Londres vs Paris vs Dubaï ?", answer: "Londres = hub historique (post-Brexit en transition). Paris = hub EU. Dubaï = hub MEA. Le CV doit préciser la base." },
      { question: "Comment montrer la gestion de la diversité EMEA ?", answer: "Mentionnez les pays, les réglementations gérées (RGPD vs locales), les langues, les cultures. C'est un atout différenciant." },
    ],
  },
  {
    slug: "cv-business-unit-manager",
    title: "CV Business Unit Manager",
    category: "International",
    salaryRange: "120K€ - 280K€ + bonus + BU P&L",
    keywords: ["cv business unit manager", "cv bum", "cv directeur business unit"],
    summary: "Le CV Business Unit Manager (BUM) doit montrer la responsabilité P&L complète d'une BU au sein d'un groupe. Souvent un tremplin vers DG. Le BUM est un 'mini-CEO' de sa BU — il doit montrer la vision stratégique et l'exécution opérationnelle.",
    keySkills: ["BU P&L", "Strategic planning", "Cross-functional leadership", "Sales & marketing", "Operations", "Financial management", "Team leadership", "HQ reporting"],
    achievements: [
      "Dirigé BU Cloud (180 personnes, CA 65 M€, +32% en 3 ans)",
      "Lancé 3 nouveaux produits, CA généré 18 M€ en 24 mois",
      "Restructuré équipe commerciale, win rate +22 pts",
      "Équipe managée (8 directs), promotion interne de 3 successeurs",
    ],
    faq: [
      { question: "BUM vs Directeur Filiale ?", answer: "Le BUM gère une BU (verticale produit/marché). Le Directeur Filiale gère une entité géographique. Le CV doit clarifier le découpage." },
      { question: "Le BUM est-il membre du Comex ?", answer: "Souvent oui dans les groupes multi-BU. Sinon, il reporting au DG/CEO. Le CV doit montrer la gouvernance." },
      { question: "Comment passer de BUM à DG ?", answer: "Montrez l'impact P&L, le scope transversal, la capacité à gérer plusieurs BU. Le BUM avec BU > 100 M€ est un candidat DG naturel." },
    ],
  },

  // ═══ CONSEIL / FINANCE (8) ═══
  {
    slug: "cv-consultant-strategie",
    title: "CV Consultant en Stratégie",
    category: "Conseil",
    salaryRange: "80K€ - 220K€ + bonus (selon grade)",
    keywords: ["cv consultant stratégie", "cv strategy consultant", "cv mckinsey bcg"],
    summary: "Le CV Consultant en Stratégie doit montrer l'impact sur des missions stratégiques (growth, M&A, operating model). Background attendu : HEC/ESSEC + MBA ou MSc top tier. Cabinet cible : McKinsey, BCG, Bain, Oliver Wyman, Roland Berger, Kearney.",
    keySkills: ["Strategic problem solving", "Financial modeling", "Market analysis", "Synthesis & storytelling", "Client management", "Team leadership", "Pyramid principle", "MBB frameworks"],
    achievements: [
      "12 missions strategy sur 24 mois (CAC40, PE-backed, scale-ups)",
      "Piloté due diligence commerciale pour 2 LBO (180 M€ total)",
      "Promu Engagement Manager en 32 mois (vs 48 moyenne cabinet)",
      "Construit 5 nouvelles offres cabinet (ESG, digital health)",
    ],
    faq: [
      { question: "Le MBA est-il obligatoire pour MBB ?", answer: "Non mais très valorisé. Les top tiers (HEC, INSEAD, LBS, Harvard, Stanford) accélèrent fortement la carrière. Sans MBA, le MSc top tier suffit." },
      { question: "Comment présenter les missions ?", answer: "Anonymisez le client si NDA, montrez l'impact (chiffres), mentionnez le cadre (BBB, DD, strategy review). Évitez le jargon cabinet." },
      { question: "Le consulting mène-il à DG ?", answer: "Oui, surtout après 5-7 ans en cabinet. Le CV doit montrer l'impact opérationnel, pas seulement les recommandations stratégiques." },
    ],
  },
  {
    slug: "cv-directeur-conseil",
    title: "CV Directeur Conseil (Partner)",
    category: "Conseil",
    salaryRange: "200K€ - 600K€+ (variable selon cabinet)",
    keywords: ["cv directeur conseil", "cv partner consulting", "cv associé conseil"],
    summary: "Le CV Directeur Conseil (Partner/Associé) doit montrer la responsabilité d'un Practice ou Office : développement commercial, gestion d'équipe (50+ consultants), delivery de missions stratégiques, P&L du Practice.",
    keySkills: ["Practice leadership", "Business development", "Client portfolio management", "Team leadership (50+)", "P&L management", "Thought leadership", "Recruiting (senior)", "Cabinet governance"],
    achievements: [
      "Partner en 8 ans (vs 12 moyenne cabinet), Practice Strategy 18 personnes",
      "Portefeuille clients 12 M€ (CAC40 + PE funds), croissance +28%/an",
      "Piloté 5 missions Stratégie C-suite (transformation, M&A, governance)",
      "Promu 4 Managers en Senior Managers (promotion interne +35%)",
    ],
    faq: [
      { question: "Partner vs Associate Partner vs Principal ?", answer: "Grades différents selon cabinet. Associate Partner/Principal = pre-partner. Partner = associé (équity). Le CV doit préciser le grade exact." },
      { question: "Combien d'années pour Partner ?", answer: "8-12 ans selon cabinet. McKinsey/BCG/Bain plus rapides (8 ans). Big 4 plus lents (10-12 ans). Le CV doit montrer la trajectoire." },
      { question: "Le Partner doit-il vendre ?", answer: "Oui, c'est central. Le CV doit montrer le portefeuille clients, le CA généré, le win rate. C'est le critère numéro 1." },
    ],
  },
  {
    slug: "cv-investisseur-prive",
    title: "CV Investisseur Private Equity",
    category: "Conseil",
    salaryRange: "150K€ - 500K€+ (carried interest)",
    keywords: ["cv private equity", "cv pe associate", "cv pe director"],
    summary: "Le CV Private Equity doit montrer l'expérience complète : sourcing, due diligence, deal execution, portfolio management, exit. Cabinets cibles : KKR, Blackstone, Carlyle, Ardian, Eurazeo, Permira, CVC. Le carried interest est un signal de réussite.",
    keySkills: ["LBO modeling", "Due diligence (commercial, financial, legal)", "Deal sourcing", "Portfolio management", "Value creation plans", "Exit strategy (IPO, secondary, trade sale)", "LP relations", "Debt structuring"],
    achievements: [
      "5 deals LBO fermés (180 M€ equity), 2 exits (IRR 28%, MOIC 2.4x)",
      "Sourcing 320 opportunités/an, 12 au IC, 2 fermés",
      "Portfolio management 4 companies, EBITDA +35% en 24 mois",
      "Promu Director en 6 ans (vs 8 moyenne fund)",
    ],
    faq: [
      { question: "Le CV PE doit-il montrer les deals ?", answer: "Oui mais anonymisez si NDA. Mentionnez : secteur, equity size, IRR/MOIC à l'exit. C'est le critère numéro 1." },
      { question: "Associate vs VP vs Director vs MD ?", answer: "Associate (0-3 ans), VP/Senior Associate (3-6), Director/Principal (6-9), MD/Partner (9+). Le CV doit préciser le grade." },
      { question: "Le carried est-il à mentionner ?", answer: "Pas le montant mais le signal de carried received. Mentionnez 'carried interest participant' si applicable. C'est un signal fort." },
    ],
  },
  {
    slug: "cv-venture-capital",
    title: "CV Venture Capital",
    category: "Conseil",
    salaryRange: "100K€ - 350K€+ (carry)",
    keywords: ["cv venture capital", "cv vc associate", "cv vc partner"],
    summary: "Le CV Venture Capital doit montrer l'expérience : sourcing startups, due diligence, deal execution, board seats, portfolio support. Funds cibles : Index, Balderton, Sequoia, Accel, Kima, Daphni. L'angélisme personnel est un signal fort.",
    keySkills: ["Deal sourcing (startups)", "Tech due diligence", "Term sheet negotiation", "Board observer/member", "Portfolio support (fundraising, recruiting, strategy)", "Network (founders, VCs)", "Market analysis (tech trends)", "Follow-on strategy"],
    achievements: [
      "8 deals Series A/B fermés (45 M€ total deployed), 2 markups x3+",
      "Sourcing 800 startups/an, 15 at IC, 2 closed",
      "Board observer 4 startups, 1 board member (Series B)",
      "3 angélismes personnels (12k€ each), 1 markup x2.5",
    ],
    faq: [
      { question: "Le CV VC doit-il montrer l'angélisme personnel ?", answer: "Oui, c'est un signal fort (skin in the game). Mentionnez le montant, le secteur, l'impact. Évitez les noms si confidentiel." },
      { question: "Associate vs Principal vs Partner ?", answer: "Associate (0-3), Principal/Senior Associate (3-6), Partner (6+). Le CV doit préciser le grade et le fund size." },
      { question: "Comment montrer le sourcing ?", answer: "Nombre de startups screenées, IC presented, closed. Mentionnez le réseau (founders, accelerators, angel networks)." },
    ],
  },
  {
    slug: "cv-banquier-affaires",
    title: "CV Banquier d'Affaires (M&A)",
    category: "Conseil",
    salaryRange: "120K€ - 500K€+ (bonus dominant)",
    keywords: ["cv banquier affaires", "cv m&a analyst", "cv investment banking"],
    summary: "Le CV Banquier d'Affaires doit montrer l'expertise M&A, ECM/DCM, levaged finance, restructuring. Banks cibles : Goldman, Morgan Stanley, JPM, Lazard, Rothschild, Evercore. Le deal flow et les transactions fermées sont le critère numéro 1.",
    keySkills: ["M&A execution", "Financial modeling (LBO, accretion/dilution)", "Pitch preparation", "Due diligence coordination", "Deal documentation (CIM, IM)", "Client management", "Valuation (DCF, comps)", "Capital markets"],
    achievements: [
      "12 deals fermés en 24 mois (8 M&A, 3 ECM, 1 DCM), 4.2 Mds€ total",
      "Lead analyst sur 2 cross-border M&A (1.2 Mds€ total)",
      "Promu Associate en 2 ans (vs 3 moyenne), VP en 5 ans",
      "Top bucket bonus 3 années consécutives",
    ],
    faq: [
      { question: "Le CV IB doit-il montrer les deals ?", answer: "Oui mais anonymisez si NDA. Mentionnez : type (M&A/ECM/DCM), secteur, montant, votre rôle. C'est le critère numéro 1." },
      { question: "Analyst vs Associate vs VP vs MD ?", answer: "Analyst (0-3), Associate (3-6), VP (6-9), Director (9-12), MD (12+). Le CV doit préciser le grade exact." },
      { question: "Boutique vs Bulge bracket ?", answer: "Bulge bracket (Goldman, JPM, MS) = deals large cap, plus structuré. Elite boutique (Lazard, Evercore, Rothschild) = deals mid/large, plus de responsibility." },
    ],
  },
  {
    slug: "cv-directeur-fonds",
    title: "CV Directeur de Fonds (Asset Management)",
    category: "Conseil",
    salaryRange: "150K€ - 400K€+ (carry/performance fee)",
    keywords: ["cv directeur fonds", "cv fund manager", "cv asset management"],
    summary: "Le CV Directeur de Fonds doit montrer la performance (track record), la stratégie d'investissement, l'AUM géré. Cibles : Amundi, Carmignac, Blackrock, Fidelity, T. Rowe Price. La performance annualisée sur 5-10 ans est le critère numéro 1.",
    keySkills: ["Portfolio management", "Investment strategy", "Risk management", "Performance attribution", "LP relations", "Market research", "Stock picking (long-only) / Macro (alloc)", "ESG integration"],
    achievements: [
      "Géré fund € Mid Caps (450 M€ AUM), performance annualisée 14.2% sur 5 ans (vs 11.8% benchmark)",
      "Top decile peer group sur 3 ans, 2ème quartile sur 1 an",
      "Levé 180 M€ auprès d'institutionnels (assurances, fonds de pensions)",
      "Promu Senior Fund Manager en 6 ans (vs 9 moyenne)",
    ],
    faq: [
      { question: "Le track record est-il public ?", answer: "Pour les funds publics (mutual funds), oui. Pour les funds privés (PE, hedge funds), souvent confidentiel. Le CV doit montrer l'outperformance vs benchmark." },
      { question: "Fund manager vs Portfolio manager ?", answer: "Similaires. Le Fund Manager porte la stratégie du fund. Le Portfolio Manager peut gérer un mandat plus large (multi-funds)." },
      { question: "Quelles certifications ?", answer: "CFA (Chartered Financial Analyst) est la référence. Mentionnez aussi AMF (FR), CAIA (alternative)." },
    ],
  },
  {
    slug: "cv-directeur-administration",
    title: "CV Directeur Administratif et Financier (DAF)",
    category: "Conseil",
    salaryRange: "100K€ - 220K€ + bonus",
    keywords: ["cv daf", "cv directeur administratif financier", "cv cfo pme"],
    summary: "Le CV DAF (Directeur Administratif et Financier) doit montrer la responsabilité élargie : finance, RH, juridique, IT, admin. Particulièrement pertinent en PME/ETI. Le DAF est souvent le n°2 du DG dans les structures < 500 personnes.",
    keySkills: ["Financial management", "Cash management", "HR oversight", "Legal coordination", "IT governance", "Administrative management", "Bank relations", "Reporting Board"],
    achievements: [
      "DAF groupe PME (350 personnes, CA 85 M€), reporting Board mensuel",
      "Optimisé BFR, trésorerie libérée 8 M€ en 12 mois",
      "Mis en place ERP (SAP Business ByDesign), délai clôture -30 jours",
      "Co-piloté 2 acquisitions (25 M€), intégration admin complète",
    ],
    faq: [
      { question: "DAF vs CFO ?", answer: "Le DAF gère finance + RH + jur + IT + admin (scope élargi, PME). Le CFO gère finance uniquement (grand groupe, plus spécialisé). Le CV doit clarifier le scope." },
      { question: "Le DAF doit-il être DSCG/CPA ?", answer: "Pas obligatoire mais très valorisé. Le DSCG (FR) ou CPA/DAC (international) est un signal fort. Le CV doit mentionner les certifications." },
      { question: "DAF est-il un tremplin vers DG ?", answer: "Oui en PME/ETI. Le DAF connaît tous les chiffres, peut prendre la DG. Le CV doit montrer la vision business beyond finance." },
    ],
  },
  {
    slug: "cv-controleur-gestion",
    title: "CV Directeur Contrôle de Gestion",
    category: "Conseil",
    salaryRange: "85K€ - 180K€ + bonus",
    keywords: ["cv directeur contrôle de gestion", "cv controleur de gestion senior", "cv fp&a director"],
    summary: "Le CV Directeur Contrôle de Gestion doit montrer la maîtrise du pilotage performance : budget, forecasting, KPIs, business partnering. Souvent un tremplin vers DAF/CFO. Le FP&A moderne est data-driven et orienté insights business.",
    keySkills: ["Budget & forecasting", "KPI design", "Business partnering", "Financial analysis", "Variance analysis", "Reporting (Board/CoDir)", "BI tools (Power BI, Tableau)", "Modeling"],
    achievements: [
      "Dirigé FP&A groupe (12 entités, 8 pays), forecast accuracy 92%",
      "Construit cockpit CoDir (35 KPIs), prise de décision accélérée",
      "Optimisé processus budget (4 mois → 6 semaines), adoption 95%",
      "Équipe managée (8 contrôleurs), satisfaction business 90%",
    ],
    faq: [
      { question: "Contrôle de gestion vs FP&A ?", answer: "Très similaires. FP&A (Financial Planning & Analysis) est le terme anglo-saxon. Le CV doit montrer les deux dimensions (reporting + business partnering)." },
      { question: "Le CFA est-il utile ?", answer: "Non, plutôt DSCG ou CIMA. Le CFA est pour les investisseurs. Le DSCG pour les contrôleurs/DAF. Le CV doit mentionner les certifications pertinentes." },
      { question: "Comment passer à DAF ?", answer: "Montrez l'impact stratégique (insights, recommandations), pas seulement le reporting. Élargissez le scope (RH, IT, jur si possible)." },
    ],
  },

  // ═══ MANAGEMENT OPÉRATIONNEL (7) ═══
  {
    slug: "cv-directeur-projet",
    title: "CV Directeur de Projet",
    category: "Management",
    salaryRange: "80K€ - 180K€ + bonus",
    keywords: ["cv directeur projet", "cv project director", "cv programme manager"],
    summary: "Le CV Directeur de Projet doit montrer la maîtrise du programme management (multi-projets), de la gouvernance et du stakeholder management. Le PMO moderne est un business partner stratégique, pas un administrateur de planning.",
    keySkills: ["Program management (MSP, PgMP)", "Stakeholder management", "Governance design", "Risk management", "Change management", "PMO setup", "Agile at scale (SAFe)", "Executive reporting"],
    achievements: [
      "Dirigé programme transformation (45 projets, 80 M€ budget, 220 personnes)",
      "Livré 92% des projets dans le délai et le budget (vs 65% moyenne groupe)",
      "Mis en place PMO groupe (15 PMs), délai moyen projet -30%",
      "Adoption framework Agile SAFe, time-to-market -45%",
    ],
    faq: [
      { question: "PMP vs PRINCE2 vs MSP ?", answer: "PMP (PMI) = standard US/international. PRINCE2 = UK/Europe. MSP = programme management. Mentionnez les certifications pertinentes." },
      { question: "PMO vs Directeur de Projet ?", answer: "Le PMO peut être support (méthodes, outils). Le Directeur de Projet pilote des projets. Le CV doit montrer les deux dimensions." },
      { question: "Comment montrer l'impact ?", answer: "Projets livrés (délai, budget), valeur créée (M€), adoption users, satisfaction stakeholders. Chiffrer systématiquement." },
    ],
  },
  {
    slug: "cv-directeur-rse",
    title: "CV Directeur RSE / Sustainability",
    category: "Management",
    salaryRange: "100K€ - 220K€ + bonus",
    keywords: ["cv directeur rse", "cv sustainability director", "cv esg director"],
    summary: "Le CV Directeur RSE doit montrer la stratégie ESG (Environment, Social, Governance), le reporting (CSRD, GRI, SASB), les objectifs net zéro et la transformation culturelle. Le poste a explosé depuis la CSRD obligatoire en 2024.",
    keySkills: ["ESG strategy", "CSRD reporting", "Carbon accounting (scope 1/2/3)", "Net zero roadmap", "Sustainable sourcing", "DEI strategy", "Stakeholder engagement (NGOs, investors)", "ESG ratings (MSCI, Sustainalytics)"],
    achievements: [
      "Défini stratégie net zero 2040, validée par SBTi (1.5°C)",
      "Réduit émissions scope 1+2 de 35% en 3 ans, scope 3 de 18%",
      "Mis en place CSRD reporting (double materialité), zéro restatement",
      "Amélioré ratings MSCI (BBB → A), Sustainalytics (24 → 18)",
    ],
    faq: [
      { question: "RSE vs Sustainability vs ESG ?", answer: "Très proches. RSE (FR) = Sustainability (EN) = responsabilité sociétale. ESG = critères évaluables. Le CV doit montrer la maîtrise des trois." },
      { question: "Quelle certification pour Directeur RSE ?", answer: "CSR证书 (Complémentaire RSE), SASB FSA, GRI Certified. Mentionnez aussi les certificates sectoriels (LEED, BREEAM pour real estate)." },
      { question: "Le Directeur RSE reporte au CEO ?", answer: "De plus en plus. Historiquement au DRH ou Comex élargi. En 2026, souvent direct CEO pour montrer l'importance stratégique." },
    ],
  },
  {
    slug: "cv-directeur-innovation",
    title: "CV Directeur de l'Innovation",
    category: "Management",
    salaryRange: "110K€ - 240K€ + bonus",
    keywords: ["cv directeur innovation", "cv innovation director", "cv chief innovation officer"],
    summary: "Le CV Directeur Innovation doit montrer la stratégie d'innovation : R&D, intrapreneuriat, partnerships startups, venture client, open innovation. Le CINO moderne pilote l'innovation business, pas seulement la R&D technique.",
    keySkills: ["Innovation strategy", "R&D management", "Open innovation", "Startup partnerships", "Venture client", "Intrapreneurship", "Design thinking", "Innovation portfolio management"],
    achievements: [
      "Piloté portefeuille innovation (28 projets, 15 M€/an budget)",
      "Lancé 4 nouvelles offres (CA généré 22 M€ en 30 mois)",
      "Signé 12 partnerships startups (venture client), 3 acquisitions",
      "Construit équipe innovation de 18 personnes (designers, PMs, devs)",
    ],
    faq: [
      { question: "Innovation vs R&D ?", answer: "R&D = recherche technique. Innovation = business + tech + design. Le CV Directeur Innovation doit montrer l'impact business, pas seulement les brevets." },
      { question: "Le CINO reporte au CEO ?", answer: "Souvent. Sinon au CSO ou CTO. Le CV doit montrer la gouvernance (Comex reporting, board updates)." },
      { question: "Comment montrer l'impact innovation ?", answer: "CA généré par nouvelles offres, ROI des partnerships, brevets déposés, adoption interne. Évitez les vanity metrics (hackathons, idéation sans suite)." },
    ],
  },
  {
    slug: "cv-directeur-customer-success",
    title: "CV Directeur Customer Success",
    category: "Management",
    salaryRange: "100K€ - 220K€ + bonus + equity",
    keywords: ["cv directeur customer success", "cv vp customer success", "cv cs director"],
    summary: "Le CV Directeur Customer Success doit montrer la responsabilité de la rétention, expansion et advocacy client. Surtout SaaS. KPIs clés : NRR, GRR, churn, NPS, expansion rate. Le VP CS moderne pilote un P&L rétention, pas seulement un support.",
    keySkills: ["Customer success strategy", "NRR/GRR optimization", "Churn prevention", "Expansion selling", "CS operations (Gainsight)", "Team leadership", "Customer health scoring", "Executive engagement"],
    achievements: [
      "Dirigé CS équipe de 35 CSMs, NRR 138% (vs 105% n-1)",
      "Réduit logo churn de 12% à 4%, net revenue churn négatif (-2%)",
      "Lancé Customer Advisory Board (15 C-levels), NPS +18 pts",
      "Mis en place Gainsight, health score accuracy 92%",
    ],
    faq: [
      { question: "CS vs Support ?", answer: "Support = réactif (tickets). CS = proactif (rétention, expansion). Le CV Directeur CS doit montrer l'impact rétention/expansion, pas seulement le support." },
      { question: "Le VP CS reporte au CRO ?", answer: "De plus en plus. Historiquement au COO ou CEO. Le rattachement au CRO aligne revenue end-to-end (acquisition + rétention)." },
      { question: "NRR target ?", answer: "Top tier SaaS = 130%+. Good = 110%+. Below 100% = problème. Le CV doit mentionner le NRR et la trajectoire." },
    ],
  },
  {
    slug: "cv-directeur-operations",
    title: "CV Directeur des Opérations (COO PME)",
    category: "Management",
    salaryRange: "100K€ - 220K€ + bonus",
    keywords: ["cv directeur operations", "cv operations director", "cv coo pme"],
    summary: "Le CV Directeur des Opérations (PME/ETI) doit montrer un scope large : production, logistique, qualité, customer service, IT. Souvent le n°2 du DG en PME. Le COO PME est un généraliste opérationnel, pas un spécialiste.",
    keySkills: ["Operations management", "Process optimization", "Lean management", "Team leadership", "Project management", "ERP (SAP, Oracle)", "Performance KPIs", "Cross-functional collaboration"],
    achievements: [
      "Dirigé opérations groupe PME (450 personnes, 4 sites), CA 95 M€",
      "Réduit coûts opérationnels de 18%, économies 14 M€/an",
      "Mis en place Lean Management, productivité +24%",
      "Équipe managée (10 directs), engagement 82%",
    ],
    faq: [
      { question: "Directeur Opérations vs COO ?", answer: "Similaires. Le COO est plus C-suite, le Directeur Ops plus PME/ETI. Le CV doit montrer le scope large (production + logistique + qualité)." },
      { question: "Le COO PME doit-il être ingénieur ?", answer: "Majoritairement oui (production). Mais des profils commerce + expérience terrain existent (services, retail). Le CV doit adapter le discours." },
      { question: "Comment passer à DG ?", answer: "Montrez l'impact transversal (multi-functions), la gestion de P&L, la vision stratégique. Le COO PME est un candidat DG naturel." },
    ],
  },
  {
    slug: "cv-directeur-talents",
    title: "CV Directeur des Talents",
    category: "Management",
    salaryRange: "95K€ - 200K€ + bonus",
    keywords: ["cv directeur talents", "cv talent director", "cv head of talent"],
    summary: "Le CV Directeur des Talents doit montrer la stratégie talent : acquisition, development, retention, succession planning. Souvent rattaché au CHRO. Le Talent Director moderne est data-driven (people analytics) et orienté business impact.",
    keySkills: ["Talent acquisition strategy", "Leadership development", "Succession planning", "People analytics", "Employer branding", "Talent mapping", "Executive search management", "DEI talent strategy"],
    achievements: [
      "Piloté stratégie talent groupe (1 200 personnes), turnover -32%",
      "Construit succession planning (25 postes clés), 80% internal mobility",
      "Lancé académie leadership (180 managers formés), promotion interne +45%",
      "Optimisé coût recrutement -28%, time-to-hire -40%",
    ],
    faq: [
      { question: "Talent vs RH ?", answer: "Le Talent est stratégique (acquisition + development + succession). Le RH est plus large (paie, admin, social). Le CV Directeur Talents doit montrer l'impact business." },
      { question: "Le Directeur Talents reporte au CHRO ?", answer: "Oui en général. Sinon au CEO dans les PME. Le CV doit montrer la gouvernance (Comex, Board)." },
      { question: "People analytics est-il crucial ?", answer: "Devenu incontournable. Mentionnez les outils (Visier, ChartHop, Lattice) et l'impact (turnover, engagement, performance)." },
    ],
  },
  {
    slug: "cv-chef-de-projet-senior",
    title: "CV Chef de Projet Senior",
    category: "Management",
    salaryRange: "70K€ - 130K€ + bonus",
    keywords: ["cv chef de projet senior", "cv senior project manager", "cv lead project"],
    summary: "Le CV Chef de Projet Senior doit montrer la maîtrise du project management (PMP, PRINCE2), du delivery multi-stakeholders et de l'impact business. Souvent un tremplin vers Directeur de Projet. Le Project Manager Senior moderne pilote des projets stratégiques.",
    keySkills: ["Project management (PMP, PRINCE2)", "Stakeholder management", "Risk management", "Agile (Scrum, Kanban)", "Budget management", "Team leadership", "Executive reporting", "Change management"],
    achievements: [
      "Piloté 12 projets stratégiques (45 M€ total, multi-pays)",
      "Livré 95% des projets dans le délai et le budget",
      "Mis en place framework Agile hybride, time-to-market -30%",
      "Équipe projet managée (8-15 personnes multi-disciplinaires)",
    ],
    faq: [
      { question: "PMP vs PRINCE2 ?", answer: "PMP (PMI) = standard US/international. PRINCE2 = UK/Europe. Mentionnez celle que vous avez, et l'impact (projets livrés)." },
      { question: "Le PMP est-il obligatoire ?", answer: "Pas obligatoire mais très valorisé. Mentionnez-le si vous l'avez. Sinon, montrez l'impact projet en chiffres." },
      { question: "Chef de projet vs Directeur de projet ?", answer: "Le Chef de Projet pilote 1-3 projets. Le Directeur de Projet pilote un programme (5-15 projets) ou un portefeuille. Le CV doit montrer le scope." },
    ],
  },
];

// ─── Helpers ────────────────────────────────────────────────
export function getCVExampleBySlug(slug: string): CVExample | undefined {
  return CV_EXAMPLES.find((cv) => cv.slug === slug);
}

export function getCVExamplesByCategory(category: CVExample["category"]): CVExample[] {
  return CV_EXAMPLES.filter((cv) => cv.category === category);
}

export function getAllCVExampleSlugs(): string[] {
  return CV_EXAMPLES.map((cv) => cv.slug);
}

export const CV_CATEGORIES: Array<{ id: CVExample["category"]; label: string; description: string }> = [
  { id: "C-Suite", label: "C-Suite", description: "CEO, CFO, COO, CTO, CMO, CHRO, CIO, CRO, CSO — top management" },
  { id: "Direction", label: "Directions fonctionnelles", description: "Directeurs fonctionnels (commercial, industriel, supply, juridique, etc.)" },
  { id: "Management", label: "Management opérationnel", description: "Directeurs projet, RSE, innovation, customer success, operations" },
  { id: "Conseil", label: "Conseil & Finance", description: "Consulting, PE, VC, IB, Asset Management, DAF, contrôle de gestion" },
  { id: "International", label: "International", description: "Country Manager, MD, VP, Area Manager, Directeurs régionaux" },
];
