/**
 * 50 synonymes management — par verbe/fréquent
 * =============================================
 * SEO target: "synonyme diriger", "synonyme manager", "synonyme piloter", etc.
 *
 * Cluster SEO type Rezi (ils capturent "develop synonym", "collaborate synonym").
 * PRSTO fait pareil en français avec des verbes executive.
 */

export interface SynonymExample {
  slug: string;
  word: string;
  category: "Action" | "Leadership" | "Management" | "Stratégie" | "Communication" | "Résultat";
  context: string; // quand l'utiliser
  synonyms: Array<{
    word: string;
    nuance: string; // différence subtile
    example: string; // phrase exemple
    powerLevel: "fort" | "neutre" | "doux";
  }>;
  cvUseCase: string; // comment l'utiliser dans un CV exec
  faq: Array<{ question: string; answer: string }>;
}

export const SYNONYM_EXAMPLES: SynonymExample[] = [
  // ═══ ACTION (10) ═══
  {
    slug: "synonyme-diriger",
    word: "diriger",
    category: "Action",
    context: "Verbe central du management executive. À varier selon le contexte (gouvernance vs opérationnel).",
    synonyms: [
      { word: "piloter", nuance: "plus opérationnel, suggère le contrôle actif", example: "Piloté la transformation digitale du groupe", powerLevel: "fort" },
      { word: "gérer", nuance: "neutre, suggère la gestion courante", example: "Géré un portefeuille de 12 clients", powerLevel: "neutre" },
      { word: "manager", nuance: "anglicisme, plus moderne, leadership direct", example: "Managé une équipe de 25 personnes", powerLevel: "neutre" },
      { word: "conduire", nuance: "suggère l'orientation stratégique", example: "Conduit la stratégie d'expansion Europe", powerLevel: "fort" },
      { word: "orchestrer", nuance: "suggère la coordination complexe", example: "Orchestré l'intégration post-M&A", powerLevel: "fort" },
      { word: "gouverner", nuance: "très formel, suggère la gouvernance", example: "Gouverné le Conseil d'Administration", powerLevel: "fort" },
      { word: "encadrer", nuance: "plus doux, suggère le mentorat", example: "Encadré 8 stagiaires MBA", powerLevel: "doux" },
    ],
    cvUseCase: "Dans un CV exec, alternez 'piloter', 'conduire' et 'orchestrer' selon le contexte. Évitez 'gérer' (trop passif) et 'manager' (anglicisme).",
    faq: [
      { question: "Quel est le meilleur synonyme de diriger pour un CV ?", answer: "'Piloter' pour les projets, 'conduire' pour la stratégie, 'orchestrer' pour les opérations complexes. Évitez 'gérer' (trop passif)." },
      { question: "Manager est-il correct en français ?", answer: "Accepté en business. Mais préférez 'diriger' ou 'piloter' dans un CV formel. 'Manager' est plus moderne mais peut paraître angliciste." },
      { question: "Comment éviter la répétition de 'diriger' dans un CV ?", answer: "Variez avec 'piloter', 'conduire', 'orchestrer', 'gouverner'. Un CV exec riche utilise 4-5 verbes différents." },
    ],
  },
  {
    slug: "synonyme-piloter",
    word: "piloter",
    category: "Action",
    context: "Très utilisé en business. À varier pour éviter la répétition.",
    synonyms: [
      { word: "diriger", nuance: "plus formel, suggère l'autorité", example: "Dirigé le projet stratégique groupe", powerLevel: "fort" },
      { word: "conduire", nuance: "suggère l'orientation", example: "Conduit la mission de transformation", powerLevel: "fort" },
      { word: "mener", nuance: "plus dynamique, suggère l'action", example: "Mené les négociations M&A", powerLevel: "neutre" },
      { word: "gérer", nuance: "neutre, suggère l'opérationnel", example: "Géré le portefeuille clients", powerLevel: "neutre" },
      { word: "coordonner", nuance: "suggère la mise en synergie", example: "Coordonné 5 équipes transverses", powerLevel: "neutre" },
      { word: "animer", nuance: "plus humain, suggère le leadership", example: "Animé le réseau des alumni", powerLevel: "doux" },
    ],
    cvUseCase: "Dans un CV, alternez 'piloter' (projets), 'diriger' (équipes), 'conduire' (stratégie). 'Piloter' reste le plus puissant pour les transformations.",
    faq: [
      { question: "Piloter vs Conduire ?", answer: "'Piloter' = contrôler activement. 'Conduire' = orienter. Pour les transformations, 'piloter'. Pour la stratégie, 'conduire'." },
      { question: "Piloter est-il trop technique ?", answer: "Non, c'est devenu standard en business. Mais évitez la sur-utilisation (max 3-4 fois par CV)." },
      { question: "Quand utiliser 'mener' ?", answer: "Pour les actions ponctuelles (négociations, missions). Ex: 'Mené les négociations avec les syndicats'." },
    ],
  },
  {
    slug: "synonyme-manager",
    word: "manager",
    category: "Action",
    context: "Anglicisme très répandu. À utiliser avec parcimonie dans un CV formel.",
    synonyms: [
      { word: "diriger", nuance: "plus formel, autorité affirmée", example: "Dirigé une équipe de 50 personnes", powerLevel: "fort" },
      { word: "encadrer", nuance: "plus doux, suggère le mentorat", example: "Encadré 5 juniors en rotation", powerLevel: "doux" },
      { word: "animer", nuance: "suggère la dynamique d'équipe", example: "Animé le CoDir hebdomadaire", powerLevel: "neutre" },
      { word: "coordonner", nuance: "suggère la mise en synergie", example: "Coordonné 3 équipes transverses", powerLevel: "neutre" },
      { word: "superviser", nuance: "suggère le contrôle", example: "Supervisé 12 consultants", powerLevel: "neutre" },
      { word: "conduire", nuance: "suggère l'orientation", example: "Conduit l'équipe vers l'objectif", powerLevel: "fort" },
    ],
    cvUseCase: "Préférez 'diriger' ou 'piloter' dans un CV exec formel. 'Manager' est acceptable en tech/scale-up. Évitez 'superviser' (tôt hiérarchique).",
    faq: [
      { question: "Manager est-il français ?", answer: "Anglicisme accepté en business. Préférez 'diriger' dans un CV formel. 'Manager' en tech/startup." },
      { question: "Manager vs Encadrer ?", answer: "'Manager' = autorité + opérationnel. 'Encadrer' = mentorat. Pour les juniors, 'encadrer'. Pour les teams, 'diriger'." },
      { question: "Manager une équipe ou diriger une équipe ?", answer: "Les deux corrects. 'Diriger' plus formel/autoritaire. 'Manager' plus moderne/collaboratif." },
    ],
  },
  {
    slug: "synonyme-creer",
    word: "créer",
    category: "Action",
    context: "Verbe fort pour parler de mise en place, lancement, fondation.",
    synonyms: [
      { word: "fonder", nuance: "suggère la fondation durable", example: "Fondé l'entité Espagne", powerLevel: "fort" },
      { word: "instaurer", nuance: "suggère la mise en place formelle", example: "Instauré un processus qualité", powerLevel: "neutre" },
      { word: "établir", nuance: "neutre, suggère la mise en place", example: "Établi le plan stratégique", powerLevel: "neutre" },
      { word: "lancer", nuance: "suggère le démarrage", example: "Lancé le produit SaaS", powerLevel: "fort" },
      { word: "démarrer", nuance: "plus dynamique, suggère l'initiation", example: "Démarré l'activité LATAM", powerLevel: "neutre" },
      { word: "initier", nuance: "suggère la première fois", example: "Initié la transformation digitale", powerLevel: "fort" },
      { word: "bâtir", nuance: "suggère la construction solide", example: "Bâti une équipe de 80 personnes", powerLevel: "fort" },
    ],
    cvUseCase: "Dans un CV exec, utilisez 'fonder' pour les entités, 'lancer' pour les produits, 'instaurer' pour les processus, 'initier' pour les transformations.",
    faq: [
      { question: "Créer vs Fonder ?", answer: "'Créer' = générique. 'Fonder' = durable, fondateur. Pour une entité/entreprise, 'fonder'. Pour un produit, 'lancer'." },
      { question: "Quand utiliser 'initier' ?", answer: "Pour les transformations/premiers projets. Ex: 'Initié la transformation digitale du groupe'. Signal fort de leadership." },
      { question: "Bâtir est-il professionnel ?", answer: "Oui, très valorisé en CV exec. Suggère la construction solide. Ex: 'Bâti une équipe world-class'." },
    ],
  },
  {
    slug: "synonyme-transformer",
    word: "transformer",
    category: "Action",
    context: "Central en CV exec — montrez les transformations menées.",
    synonyms: [
      { word: "réinventer", nuance: "suggère la transformation radicale", example: "Réinventé le business model", powerLevel: "fort" },
      { word: "restructurer", nuance: "suggère la réorganisation", example: "Restructuré 5 filiales", powerLevel: "fort" },
      { word: "réorganiser", nuance: "suggère la nouvelle organisation", example: "Réorganisé la direction commerciale", powerLevel: "neutre" },
      { word: "moderniser", nuance: "suggère la mise à jour", example: "Modernisé le SI groupe", powerLevel: "neutre" },
      { word: "renouveler", nuance: "suggère le changement", example: "Renouvelé l'offre produit", powerLevel: "neutre" },
      { word: "faire évoluer", nuance: "plus doux, suggère la progression", example: "Fait évoluer la culture d'entreprise", powerLevel: "doux" },
      { word: "bouleverser", nuance: "très fort, suggère la disruption", example: "Bouleversé le marché par l'innovation", powerLevel: "fort" },
    ],
    cvUseCase: "Dans un CV exec, 'transformer' et 'réinventer' sont les plus puissants. Évitez 'faire évoluer' (trop doux) pour les transformations majeures.",
    faq: [
      { question: "Transformer vs Réinventer ?", answer: "'Transformer' = changement profond. 'Réinventer' = transformation radicale. Pour les pivots stratégiques, 'réinventer'." },
      { question: "Restructurer est-il négatif ?", answer: "Peut l'être (licenciements). Mais dans un CV exec, 'restructuré' montre la capacité à prendre des décisions difficiles. Précisez l'impact positif." },
      { question: "Comment parler de transformation sans paraître négatif ?", answer: "Utilisez 'moderniser', 'renouveler' pour les changements progressifs. Réservez 'transformer' pour les changements majeurs." },
    ],
  },
  {
    slug: "synonyme-optimiser",
    word: "optimiser",
    category: "Action",
    context: "Très utilisé en business. À varier selon le contexte (coûts, process, perf).",
    synonyms: [
      { word: "améliorer", nuance: "neutre, suggère le progressif", example: "Amélioré le taux de conversion", powerLevel: "neutre" },
      { word: "maximiser", nuance: "suggère l'optimum", example: "Maximisé le ROI marketing", powerLevel: "fort" },
      { word: "rationnaliser", nuance: "suggère la mise en ordre", example: "Rationalisé le portefeuille produits", powerLevel: "neutre" },
      { word: "industrialiser", nuance: "suggère la scalabilité", example: "Industrialisé le processus de vente", powerLevel: "fort" },
      { word: "fiabiliser", nuance: "suggère la robustesse", example: "Fiabilisé la chaîne d'approvisionnement", powerLevel: "neutre" },
      { word: "streamliner", nuance: "anglicisme, suggère la simplification", example: "Streamliné les opérations", powerLevel: "neutre" },
      { word: "augmenter", nuance: "plus simple, direct", example: "Augmenté les ventes de 28%", powerLevel: "neutre" },
    ],
    cvUseCase: "Dans un CV exec, 'optimiser' reste pertinent. Variez avec 'industrialiser' (scalabilité), 'maximiser' (impact), 'fiabiliser' (robustesse).",
    faq: [
      { question: "Optimiser vs Améliorer ?", answer: "'Optimiser' = atteindre l'optimum. 'Améliorer' = rendre meilleur. Pour les KPIs business, 'optimiser' plus fort." },
      { question: "Industrialiser est-il tech ?", answer: "Non, applicable à tout process. Ex: 'Industrialisé le processus de recrutement'." },
      { question: "Comment éviter la répétition d'optimiser ?", answer: "Variez avec 'améliorer', 'maximiser', 'fiabiliser', 'augmenter'. Évitez 'streamliner' (anglicisme)." },
    ],
  },
  {
    slug: "synonyme-developper",
    word: "développer",
    category: "Action",
    context: "Très fréquent. À varier pour enrichir le vocabulaire exec.",
    synonyms: [
      { word: "déployer", nuance: "suggère le déploiement large", example: "Déployé la stratégie EMEA", powerLevel: "fort" },
      { word: "cultiver", nuance: "plus doux, suggère la croissance", example: "Cultivé les relations clients", powerLevel: "doux" },
      { word: "faire croître", nuance: "direct, suggère la croissance", example: "Fait croître l'ARR de 8 à 25 M€", powerLevel: "fort" },
      { word: "étendre", nuance: "suggère l'expansion", example: "Étendu l'activité à 3 pays", powerLevel: "fort" },
      { word: "amplifier", nuance: "suggère l'intensification", example: "Amplifié l'impact de la marque", powerLevel: "fort" },
      { word: "construire", nuance: "suggère la solidité", example: "Construit une équipe de 60 personnes", powerLevel: "neutre" },
      { word: "bâtir", nuance: "plus fort, suggère la fondation", example: "Bâti le practice Tech du cabinet", powerLevel: "fort" },
    ],
    cvUseCase: "Dans un CV exec, alternez 'développer', 'déployer', 'étendre', 'faire croître'. Préférez 'bâtir' pour les constructions durables.",
    faq: [
      { question: "Développer vs Déployer ?", answer: "'Développer' = faire croître. 'Déployer' = mettre en place. Pour une stratégie, 'déployer'. Pour une activité, 'développer'." },
      { question: "Comment parler de croissance sur un CV ?", answer: "'Fait croître l'ARR de X à Y' (SaaS), 'Triplé le CA' (business). Variez les formulations pour éviter la répétition." },
      { question: "Bâtir est-il professionnel ?", answer: "Très valorisé en exec. Suggère la construction solide. Ex: 'Bâti une organisation de 200 personnes'." },
    ],
  },
  {
    slug: "synonyme-negocier",
    word: "négocier",
    category: "Action",
    context: "Central en CV exec (M&A, partnerships, contrats, salaires).",
    synonyms: [
      { word: "conclure", nuance: "suggère la finalisation", example: "Conclu 12 partnerships stratégiques", powerLevel: "fort" },
      { word: "finaliser", nuance: "neutre, suggère l'achèvement", example: "Finalisé le deal LBO 80 M€", powerLevel: "neutre" },
      { word: "sécuriser", nuance: "suggère la garantie", example: "Sécurisé le contrat cadre 5 ans", powerLevel: "fort" },
      { word: "obtenir", nuance: "direct, suggère le résultat", example: "Obtenu 45 M€ de financement", powerLevel: "neutre" },
      { word: "décrocher", nuance: "plus familier, suggère l'effort", example: "Décroché le mandat exclusif", powerLevel: "doux" },
      { word: "arracher", nuance: "très fort, suggère la difficulté", example: "Arraché la victory contre les concurrents", powerLevel: "fort" },
      { word: "traiter", nuance: "neutre, suggère le process", example: "Traité 18 dossiers M&A", powerLevel: "neutre" },
    ],
    cvUseCase: "Dans un CV exec, 'négocier' reste standard. Variez avec 'conclure', 'sécuriser', 'obtenir' pour montrer l'impact.",
    faq: [
      { question: "Négocier vs Conclure ?", answer: "'Négocier' = process. 'Conclure' = résultat. Pour les deals réussis, 'conclu' plus impactant." },
      { question: "Sécuriser est-il professionnel ?", answer: "Très, surtout en PE/M&A. Ex: 'Sécurisé le closing du tour de table 50 M€'." },
      { question: "Arracher est-il trop familier ?", answer: "Oui, à réserver pour les contextes très compétitifs. Préférez 'décroché' ou 'obtenu' en CV formel." },
    ],
  },
  {
    slug: "synonyme-lancer",
    word: "lancer",
    category: "Action",
    context: "Verbe dynamique pour les nouveautés (produits, projets, entités).",
    synonyms: [
      { word: "inaugurer", nuance: "très formel, suggère l'officialisation", example: "Inauguré la filiale Singapour", powerLevel: "fort" },
      { word: "initier", nuance: "suggère la première fois", example: "Initié le programme RSE", powerLevel: "fort" },
      { word: "déployer", nuance: "suggère la mise en place", example: "Déployé le nouveau CRM", powerLevel: "fort" },
      { word: "introduire", nuance: "neutre, suggère l'arrivée", example: "Introduit le produit sur le marché", powerLevel: "neutre" },
      { word: "mettre en place", nuance: "neutre, plus descriptif", example: "Mis en place la nouvelle organisation", powerLevel: "neutre" },
      { word: "démarrer", nuance: "plus dynamique, suggère l'action", example: "Démarré l'activité Cloud", powerLevel: "neutre" },
      { word: "implanter", nuance: "suggère l'enracinement", example: "Implanté la marque en Chine", powerLevel: "fort" },
    ],
    cvUseCase: "Dans un CV exec, alternez 'lancé', 'déployé', 'initié', 'implanté' selon le contexte (produit, marché, programme).",
    faq: [
      { question: "Lancer vs Déployer ?", answer: "'Lancer' = démarrage (produit, entité). 'Déployer' = mise en place (stratégie, organisation). Pour les produits, 'lancer'. Pour les stratégies, 'déployer'." },
      { question: "Implanter est-il exec ?", answer: "Très, surtout pour l'expansion géographique. Ex: 'Implanté la marque en Asie du Sud-Est'." },
      { question: "Quand utiliser 'initier' ?", answer: "Pour les premières fois. Ex: 'Initié la transformation digitale du groupe'." },
    ],
  },
  {
    slug: "synonyme-implanter",
    word: "implanter",
    category: "Action",
    context: "Spécifique à l'expansion géographique ou l'installation durable.",
    synonyms: [
      { word: "installer", nuance: "neutre, suggère la mise en place", example: "Installé la nouvelle usine", powerLevel: "neutre" },
      { word: "fonder", nuance: "suggère la fondation durable", example: "Fondé la filiale Mexico", powerLevel: "fort" },
      { word: "établir", nuance: "neutre, suggère la mise en place", example: "Établi le bureau de représentation", powerLevel: "neutre" },
      { word: "déployer", nuance: "suggère l'expansion", example: "Déployé l'activité sur 5 pays", powerLevel: "fort" },
      { word: "lancer", nuance: "suggère le démarrage", example: "Lancé l'activité LATAM", powerLevel: "fort" },
      { word: "imposer", nuance: "suggère la force", example: "Imposé la marque sur le marché", powerLevel: "fort" },
      { word: "enraciner", nuance: "suggère la profondeur", example: "Enraciné la culture d'entreprise", powerLevel: "neutre" },
    ],
    cvUseCase: "Dans un CV exec, 'implanté' est puissant pour l'international. Variez avec 'fondé', 'déployé', 'établi' selon le contexte.",
    faq: [
      { question: "Implanter vs Installer ?", answer: "'Implanter' = installation durable (entité, marque). 'Installer' = mise en place physique. Pour les filiales, 'implanter'." },
      { question: "Quand utiliser 'fonder' ?", answer: "Pour les créations ex-nihilo. Ex: 'Fondé la filiale Allemagne'." },
      { question: "Imposer est-il trop fort ?", answer: "Pour les marchés compétitifs, ça marche. Ex: 'Imposé la marque face aux leaders historiques'." },
    ],
  },

  // ═══ LEADERSHIP (10) ═══
  {
    slug: "synonyme-accompagner",
    word: "accompagner",
    category: "Leadership",
    context: "Très utilisé en management. À varier pour enrichir.",
    synonyms: [
      { word: "soutenir", nuance: "suggère le support actif", example: "Soutenu 5 startups dans leur scale-up", powerLevel: "neutre" },
      { word: "guider", nuance: "suggère l'orientation", example: "Guidé le Board dans la stratégie", powerLevel: "neutre" },
      { word: "épauler", nuance: "plus familier, suggère l'aide", example: "Épaulé le CEO dans la levée", powerLevel: "doux" },
      { word: "mentorater", nuance: "anglicisme, suggère le mentorat", example: "Mentoré 8 jeunes talents", powerLevel: "neutre" },
      { word: "coachater", nuance: "anglicisme, suggère le coaching", example: "Coaché 12 managers", powerLevel: "neutre" },
      { word: "conseiller", nuance: "suggère l'expertise", example: "Conseillé 15 PE funds", powerLevel: "neutre" },
      { word: "orienter", nuance: "suggère la direction", example: "Orienté la transformation culturelle", powerLevel: "neutre" },
    ],
    cvUseCase: "Dans un CV exec, alternez 'accompagné', 'soutenu', 'conseillé', 'mentoré'. 'Accompagner' reste polyvalent.",
    faq: [
      { question: "Accompagner vs Soutenir ?", answer: "'Accompagner' = sur la durée. 'Soutenir' = sur un moment. Pour les transformations, 'accompagner'. Pour les crises, 'soutenir'." },
      { question: "Mentorater est-il français ?", answer: "Anglicisme accepté en business. Préférez 'mentoré' (participe passé) ou 'accompagné comme mentor'." },
      { question: "Conseiller vs Accompagner ?", answer: "'Conseiller' = expertise ponctuelle. 'Accompagner' = sur la durée. Pour les missions advisory, 'conseiller'. Pour les transformations, 'accompagner'." },
    ],
  },
  {
    slug: "synonyme-federer",
    word: "fédérer",
    category: "Leadership",
    context: "Central en leadership — montrez votre capacité à rassembler.",
    synonyms: [
      { word: "rassembler", nuance: "neutre, suggère l'unité", example: "Rassemblé 5 directions autour du projet", powerLevel: "neutre" },
      { word: "mobiliser", nuance: "suggère l'action collective", example: "Mobilisé 200 personnes sur la transformation", powerLevel: "fort" },
      { word: "rallier", nuance: "suggère la convainction", example: "Rallié le Board à la nouvelle stratégie", powerLevel: "fort" },
      { word: "unir", nuance: "suggère la cohésion", example: "Uni les équipes post-M&A", powerLevel: "neutre" },
      { word: "mener", nuance: "suggère le leadership actif", example: "Mené l'équipe à l'objectif", powerLevel: "fort" },
      { word: "engager", nuance: "suggère l'adhésion", example: "Engagé les équipes dans la vision", powerLevel: "fort" },
      { word: "souder", nuance: "suggère la solidité", example: "Soudé une équipe pluridisciplinaire", powerLevel: "fort" },
    ],
    cvUseCase: "Dans un CV exec, 'fédéré' et 'mobilisé' sont les plus puissants. Variez avec 'rallié' (conviction), 'soudé' (cohésion).",
    faq: [
      { question: "Fédérer vs Mobiliser ?", answer: "'Fédérer' = rassembler. 'Mobiliser' = mettre en action. Pour les transformations, 'mobilisé' plus fort." },
      { question: "Rallier est-il exec ?", answer: "Oui, surtout pour le Board/Comex. Ex: 'Rallié le Board à la nouvelle stratégie'." },
      { question: "Comment montrer le leadership sans paraître autoritaire ?", answer: "Utilisez 'fédérer', 'mobiliser', 'engager', 'soutenir'. Évitez 'imposer', 'forcer'." },
    ],
  },
  {
    slug: "synonyme-motiver",
    word: "motiver",
    category: "Leadership",
    context: "À utiliser pour montrer le leadership humain.",
    synonyms: [
      { word: "engager", nuance: "suggère l'adhésion active", example: "Engagé les équipes dans la vision", powerLevel: "fort" },
      { word: "inspirer", nuance: "suggère la vision", example: "Inspiré 200 commerciaux vers l'objectif", powerLevel: "fort" },
      { word: "stimuler", nuance: "suggère l'énergie", example: "Stimulé l'innovation interne", powerLevel: "neutre" },
      { word: "encourager", nuance: "plus doux, suggère le soutien", example: "Encouragé la prise d'initiative", powerLevel: "doux" },
      { word: "impulser", nuance: "suggère la dynamique", example: "Impulsé une nouvelle culture", powerLevel: "fort" },
      { word: "énergiser", nuance: "anglicisme, suggère l'énergie", example: "Énergisé l'équipe vers la hypergrowth", powerLevel: "neutre" },
      { word: "galvaniser", nuance: "très fort, suggère l'enthousiasme", example: "Galvanisé les troupes en crise", powerLevel: "fort" },
    ],
    cvUseCase: "Dans un CV exec, 'engagé', 'inspiré', 'impulsé' sont les plus impactants. Évitez 'énergiser' (anglicisme).",
    faq: [
      { question: "Motiver vs Engager ?", answer: "'Motiver' = créer la motivation. 'Engager' = créer l'adhésion active. Pour les transformations, 'engager' plus fort." },
      { question: "Inspirer est-il exec ?", answer: "Très, surtout pour le leadership visionnaire. Ex: 'Inspiré l'organisation vers la vision 2030'." },
      { question: "Galvaniser est-il trop fort ?", answer: "Pour les contextes de crise/transformation majeure, ça marche. Sinon, préférez 'engager' ou 'inspirer'." },
    ],
  },
  {
    slug: "synonyme-deleguer",
    word: "déléguer",
    category: "Leadership",
    context: "Compétence clé exec — montrer qu'on sait lâcher prise.",
    synonyms: [
      { word: "confier", nuance: "suggère la confiance", example: "Confié la direction Europe à un successor", powerLevel: "neutre" },
      { word: "habiliter", nuance: "suggère l'autonomie", example: "Habilité 8 directeurs à décider", powerLevel: "fort" },
      { word: "mandater", nuance: "suggère la mission", example: "Mandaté 3 VPs pour la transformation", powerLevel: "neutre" },
      { word: "autonomiser", nuance: "suggère l'empowerment", example: "Autonomisé les équipes locales", powerLevel: "fort" },
      { word: "empowerater", nuance: "anglicisme, suggère l'autonomisation", example: "Empoweré 12 managers", powerLevel: "neutre" },
      { word: "affecter", nuance: "neutre, suggère l'attribution", example: "Affecté 5 directeurs aux BU", powerLevel: "neutre" },
      { word: "confier", nuance: "suggère la responsabilité", example: "Confié la gestion financière au DAF", powerLevel: "neutre" },
    ],
    cvUseCase: "Dans un CV exec, 'déléguer' reste standard. Variez avec 'autonomisé', 'habilité' pour montrer l'empowerment.",
    faq: [
      { question: "Déléguer vs Confier ?", answer: "'Déléguer' = transférer autorité. 'Confier' = transférer confiance. Pour les responsabilités, 'déléguer'. Pour les missions, 'confier'." },
      { question: "Empowerater est-il français ?", answer: "Anglicisme. Préférez 'autonomiser' ou 'habiliter' en français. 'Empoweré' peut s'utiliser en tech/scale-up." },
      { question: "Comment montrer qu'on délègue bien ?", answer: "Mentionnez les réussites des équipes déléguées. Ex: 'Délégué la direction Espagne à un successor (promu en 24 mois)'." },
    ],
  },
  {
    slug: "synonyme-coacher",
    word: "coachater",
    category: "Leadership",
    context: "Anglicisme très répandu. À utiliser ou varier.",
    synonyms: [
      { word: "accompagner", nuance: "neutre, plus large", example: "Accompagné 5 managers vers la promotion", powerLevel: "neutre" },
      { word: "mentorater", nuance: "suggère le mentorat expérience", example: "Mentoré 8 jeunes talents", powerLevel: "neutre" },
      { word: "former", nuance: "suggère l'apprentissage", example: "Formé 200 commerciaux", powerLevel: "neutre" },
      { word: "guider", nuance: "suggère l'orientation", example: "Guidé 12 startups", powerLevel: "neutre" },
      { word: "conseiller", nuance: "suggère l'expertise", example: "Conseillé 5 CEOs", powerLevel: "neutre" },
      { word: "épauler", nuance: "plus familier", example: "Épaulé le founder dans la scale-up", powerLevel: "doux" },
      { word: "préparer", nuance: "suggère l'anticipation", example: "Préparé mon successor", powerLevel: "neutre" },
    ],
    cvUseCase: "Dans un CV exec, 'accompagné' est plus formel que 'coacher'. 'Mentoré' valorise l'aspect transmission.",
    faq: [
      { question: "Coachater est-il français ?", answer: "Anglicisme accepté en business. Préférez 'accompagné' ou 'mentoré' en CV formel." },
      { question: "Mentorater vs Coachater ?", answer: "'Mentorater' = transmission d'expérience. 'Coachater' = accompagnement méthodologique. Pour les juniors, 'mentorater'. Pour les seniors, 'coachater'." },
      { question: "Quand utiliser 'conseiller' ?", answer: "Pour l'expertise ponctuelle. Ex: 'Conseillé 5 PE funds sur le sector tech'." },
    ],
  },
  {
    slug: "synonyme-soutenir",
    word: "soutenir",
    category: "Leadership",
    context: "Pour montrer le soutien actif aux équipes, projets, initiatives.",
    synonyms: [
      { word: "appuyer", nuance: "suggère le renfort", example: "Appuyé 3 projets stratégiques", powerLevel: "neutre" },
      { word: "épauler", nuance: "plus familier, suggère l'aide", example: "Épaulé le CEO dans la crise", powerLevel: "doux" },
      { word: "encourager", nuance: "suggère la motivation", example: "Encouragé l'innovation interne", powerLevel: "doux" },
      { word: "promouvoir", nuance: "suggère la valorisation", example: "Promu la culture data-driven", powerLevel: "fort" },
      { word: "défendre", nuance: "suggère l'engagement", example: "Défendu le budget R&D au Board", powerLevel: "fort" },
      { word: "valider", nuance: "suggère l'approbation", example: "Validé 12 projets transverses", powerLevel: "neutre" },
      { word: "faciliter", nuance: "suggère la simplification", example: "Facilité 18 collaborations", powerLevel: "neutre" },
    ],
    cvUseCase: "Dans un CV exec, 'soutenu' reste standard. Variez avec 'défendu' (Board), 'promu' (culture), 'facilité' (collaboration).",
    faq: [
      { question: "Soutenir vs Appuyer ?", answer: "'Soutenir' = appui moral et matériel. 'Appuyer' = renfort actif. Pour les projets, 'appuyé'. Pour les équipes, 'soutenu'." },
      { question: "Défendre est-il exec ?", answer: "Très, surtout pour le Board/Comex. Ex: 'Défendu le budget transformation au Board'." },
      { question: "Quand utiliser 'faciliter' ?", answer: "Pour montrer le soutien opérationnel. Ex: 'Facilité 18 collaborations cross-fonctionnelles'." },
    ],
  },
  {
    slug: "synonyme-inspirer",
    word: "inspirer",
    category: "Leadership",
    context: "Très valorisé en leadership visionnaire.",
    synonyms: [
      { word: "motiver", nuance: "plus opérationnel", example: "Motivé 200 commerciaux", powerLevel: "neutre" },
      { word: "fédérer", nuance: "suggère le rassemblement", example: "Fédéré 5 directions", powerLevel: "fort" },
      { word: "galvaniser", nuance: "très fort, suggère l'enthousiasme", example: "Galvanisé les troupes en crise", powerLevel: "fort" },
      { word: "entraîner", nuance: "suggère l'effet d'entraînement", example: "Entraîné l'équipe vers l'objectif", powerLevel: "neutre" },
      { word: "embarquer", nuance: "familier, suggère l'adhésion", example: "Embarqué 80 personnes dans la vision", powerLevel: "doux" },
      { word: "impulser", nuance: "suggère la dynamique", example: "Impulsé une nouvelle culture", powerLevel: "fort" },
      { word: "passionner", nuance: "suggère l'émotion", example: "Passionné les équipes pour la mission", powerLevel: "fort" },
    ],
    cvUseCase: "Dans un CV exec, 'inspiré' et 'impulsé' sont les plus impactants. Évitez 'embarqué' (trop familier).",
    faq: [
      { question: "Inspirer vs Motiver ?", answer: "'Inspirer' = susciter l'enthousiasme. 'Motiver' = donner envie d'agir. Pour les visions, 'inspirer'. Pour les objectifs, 'motiver'." },
      { question: "Galvaniser est-il trop fort ?", answer: "Pour les crises ou transformations majeures, ça marche. Sinon, préférez 'inspirer' ou 'fédérer'." },
      { question: "Comment montrer le leadership inspirant ?", answer: "Utilisez 'inspiré', 'fédéré', 'impulsé'. Mentionnez les résultats collectifs (promotions, NPS équipe, etc.)." },
    ],
  },
  {
    slug: "synonyme-engager",
    word: "engager",
    category: "Leadership",
    context: "Central en transformation — montrez l'adhésion des équipes.",
    synonyms: [
      { word: "mobiliser", nuance: "suggère l'action collective", example: "Mobilisé 200 personnes", powerLevel: "fort" },
      { word: "fédérer", nuance: "suggère le rassemblement", example: "Fédéré 5 directions", powerLevel: "fort" },
      { word: "embarquer", nuance: "familier, suggère l'adhésion", example: "Embarqué 80 personnes", powerLevel: "doux" },
      { word: "rallier", nuance: "suggère la convainction", example: "Rallié le Board", powerLevel: "fort" },
      { word: "impliquer", nuance: "suggère la participation", example: "Impliqué 12 stakeholders", powerLevel: "neutre" },
      { word: "entraîner", nuance: "suggère l'effet d'entraînement", example: "Entraîné l'équipe", powerLevel: "neutre" },
      { word: "passionner", nuance: "suggère l'émotion", example: "Passionné les équipes", powerLevel: "fort" },
    ],
    cvUseCase: "Dans un CV exec, 'engagé' et 'mobilisé' sont les plus forts. Variez avec 'rallié' (Board), 'fédéré' (équipes).",
    faq: [
      { question: "Engager vs Mobiliser ?", answer: "'Engager' = adhésion. 'Mobiliser' = action collective. Pour les transformations, 'mobilisé' plus fort." },
      { question: "Embarquer est-il trop familier ?", answer: "Un peu. Préférez 'engager' ou 'fédérer' en CV formel. 'Embarquer' OK en tech/scale-up." },
      { question: "Comment montrer l'engagement des équipes ?", answer: "Mentionnez les chiffres : NPS équipe, engagement survey, taux d'adoption. 'Engagé 85% des équipes dans la vision'." },
    ],
  },
  {
    slug: "synonyme-confier",
    word: "confier",
    category: "Leadership",
    context: "Pour montrer la confiance accordée aux équipes.",
    synonyms: [
      { word: "déléguer", nuance: "suggère l'autorité transférée", example: "Délégué la direction Europe", powerLevel: "fort" },
      { word: "mandater", nuance: "suggère la mission", example: "Mandaté 3 VPs", powerLevel: "neutre" },
      { word: "habiliter", nuance: "suggère l'autonomie", example: "Habilité 8 directeurs", powerLevel: "fort" },
      { word: "charger", nuance: "suggère la responsabilité", example: "Chargé 5 managers de la transformation", powerLevel: "neutre" },
      { word: "affecter", nuance: "neutre, suggère l'attribution", example: "Affecté 5 directeurs aux BU", powerLevel: "neutre" },
      { word: "commettre", nuance: "très formel, suggère la délégation", example: "Commi le DAF pour les négociations", powerLevel: "neutre" },
      { word: "investir", nuance: "suggère la confiance solennelle", example: "Investi le COO des pleins pouvoirs", powerLevel: "fort" },
    ],
    cvUseCase: "Dans un CV exec, 'délégué' et 'habilité' sont les plus forts. 'Confié' reste neutre.",
    faq: [
      { question: "Confier vs Déléguer ?", answer: "'Confier' = confiance. 'Déléguer' = transfert d'autorité. Pour les responsabilités, 'déléguer'." },
      { question: "Quand utiliser 'habiliter' ?", answer: "Pour montrer l'empowerment formel. Ex: 'Habilité 8 directeurs à prendre des décisions autonomes'." },
      { question: "Investir est-il professionnel ?", answer: "Oui, surtout pour les mandats solennels. Ex: 'Investi le COO des pleins pouvoirs pour la transformation'." },
    ],
  },
  {
    slug: "synonyme-conseiller",
    word: "conseiller",
    category: "Leadership",
    context: "Pour montrer l'expertise advisory et le mentoring de C-level.",
    synonyms: [
      { word: "orienter", nuance: "suggère la direction", example: "Orienté le Board dans la stratégie", powerLevel: "neutre" },
      { word: "guider", nuance: "suggère l'orientation", example: "Guidé 12 startups", powerLevel: "neutre" },
      { word: "accompagner", nuance: "suggère le soutien", example: "Accompagné 5 CEOs", powerLevel: "neutre" },
      { word: "consultater", nuance: "anglicisme, suggère la consultation", example: "Consulté sur 18 missions M&A", powerLevel: "neutre" },
      { word: "épauler", nuance: "plus familier", example: "Épaulé le DG dans la crise", powerLevel: "doux" },
      { word: "instruire", nuance: "très formel, suggère l'enseignement", example: "Instructé le Board sur les enjeux tech", powerLevel: "fort" },
      { word: "éclairer", nuance: "suggère la clarté", example: "Éclairé la décision du Comex", powerLevel: "fort" },
    ],
    cvUseCase: "Dans un CV exec, 'conseillé' reste standard. Variez avec 'éclairé' (Board), 'accompagné' (long-terme).",
    faq: [
      { question: "Conseiller vs Accompagner ?", answer: "'Conseiller' = expertise ponctuelle. 'Accompagner' = sur la durée. Pour les missions advisory, 'conseiller'. Pour les transformations, 'accompagner'." },
      { question: "Éclairer est-il exec ?", answer: "Très, surtout pour le Board. Ex: 'Éclairé le Board sur les enjeux tech'." },
      { question: "Consultater est-il français ?", answer: "Anglicisme. Préférez 'consulté' ou 'conseillé'. 'Consulté sur 18 missions M&A'." },
    ],
  },

  // ═══ STRATÉGIE (8) ═══
  {
    slug: "synonyme-elaborer",
    word: "élaborer",
    category: "Stratégie",
    context: "Verbe central en stratégie. À varier selon le contexte.",
    synonyms: [
      { word: "concevoir", nuance: "suggère la créativité", example: "Conçu la stratégie 5 ans", powerLevel: "fort" },
      { word: "définir", nuance: "suggère la formalisation", example: "Défini la vision stratégique", powerLevel: "fort" },
      { word: "formuler", nuance: "suggère l'expression", example: "Formulé le plan stratégique", powerLevel: "neutre" },
      { word: "structurer", nuance: "suggère l'organisation", example: "Structuré la démarche stratégique", powerLevel: "neutre" },
      { word: "construire", nuance: "suggère la solidité", example: "Construit le business plan", powerLevel: "neutre" },
      { word: "draftater", nuance: "anglicisme, suggère la rédaction", example: "Drafté le plan de transformation", powerLevel: "doux" },
      { word: "bâtir", nuance: "plus fort, suggère la fondation", example: "Bâti la roadmap 2026-2030", powerLevel: "fort" },
    ],
    cvUseCase: "Dans un CV exec, 'défini' et 'conçu' sont les plus impactants. Variez avec 'bâti' (durabilité).",
    faq: [
      { question: "Élaborer vs Définir ?", answer: "'Élaborer' = créer dans le détail. 'Définir' = formaliser. Pour les plans, 'élaborer'. Pour les visions, 'définir'." },
      { question: "Concevoir est-il exec ?", answer: "Très, surtout pour la stratégie. Ex: 'Conçu la stratégie 5 ans du groupe'." },
      { question: "Draftater est-il français ?", answer: "Anglicisme. Préférez 'rédigé' ou 'élaboré' en français." },
    ],
  },
  {
    slug: "synonyme-definir",
    word: "définir",
    category: "Stratégie",
    context: "Très utilisé en stratégie. À varier.",
    synonyms: [
      { word: "élaborer", nuance: "suggère le travail approfondi", example: "Élaboré la stratégie 5 ans", powerLevel: "fort" },
      { word: "concevoir", nuance: "suggère la créativité", example: "Conçu la vision stratégique", powerLevel: "fort" },
      { word: "formuler", nuance: "suggère l'expression", example: "Formulé les objectifs 2030", powerLevel: "neutre" },
      { word: "tracer", nuance: "suggère le chemin", example: "Tracé la roadmap stratégique", powerLevel: "neutre" },
      { word: "arrêter", nuance: "très formel, suggère la décision", example: "Arrêté le plan stratégique", powerLevel: "fort" },
      { word: "établir", nuance: "neutre, suggère la mise en place", example: "Établi les KPIs stratégiques", powerLevel: "neutre" },
      { word: "dessiner", nuance: "suggère le contour", example: "Dessiné le plan de transformation", powerLevel: "neutre" },
    ],
    cvUseCase: "Dans un CV exec, 'défini' reste standard. Variez avec 'conçu' (créativité), 'tracé' (roadmap).",
    faq: [
      { question: "Définir vs Élaborer ?", answer: "'Définir' = formaliser. 'Élaborer' = créer dans le détail. Pour les visions, 'définir'. Pour les plans, 'élaborer'." },
      { question: "Arrêter est-il exec ?", answer: "Oui, surtout pour les décisions formelles. Ex: 'Arrêté le plan stratégique en CoDir'." },
      { question: "Tracer est-il professionnel ?", answer: "Très pour les roadmaps. Ex: 'Tracé la roadmap 2026-2030 du groupe'." },
    ],
  },
  {
    slug: "synonyme-concevoir",
    word: "concevoir",
    category: "Stratégie",
    context: "Pour montrer la créativité stratégique.",
    synonyms: [
      { word: "élaborer", nuance: "suggère le travail approfondi", example: "Élaboré la stratégie 5 ans", powerLevel: "fort" },
      { word: "imaginer", nuance: "suggère la vision", example: "Imaginé le futur du secteur", powerLevel: "fort" },
      { word: "définir", nuance: "suggère la formalisation", example: "Défini la vision stratégique", powerLevel: "fort" },
      { word: "créer", nuance: "neutre, suggère la nouveauté", example: "Créé le business model", powerLevel: "neutre" },
      { word: "inventer", nuance: "très fort, suggère l'innovation", example: "Inventé un nouveau mode de distribution", powerLevel: "fort" },
      { word: "designater", nuance: "anglicisme, suggère la conception", example: "Designé le nouveau parcours client", powerLevel: "neutre" },
      { word: "façonner", nuance: "suggère la construction", example: "Façonné la nouvelle identité", powerLevel: "fort" },
    ],
    cvUseCase: "Dans un CV exec, 'conçu' et 'imaginé' sont les plus impactants. Évitez 'designer' (anglicisme).",
    faq: [
      { question: "Concevoir vs Imaginer ?", answer: "'Concevoir' = création réfléchie. 'Imaginer' = vision créative. Pour les stratégies, 'concevoir'. Pour les visions, 'imaginer'." },
      { question: "Inventer est-il trop fort ?", answer: "Pour les vraies innovations, ça marche. Ex: 'Inventé un nouveau mode de distribution'. Sinon, préférez 'conçu'." },
      { question: "Façonner est-il exec ?", answer: "Très, surtout pour les transformations culturelles. Ex: 'Façonné la nouvelle identité du groupe'." },
    ],
  },
  {
    slug: "synonyme-piloter-strategie",
    word: "piloter (stratégie)",
    category: "Stratégie",
    context: "Pour montrer la mise en œuvre stratégique.",
    synonyms: [
      { word: "conduire", nuance: "suggère l'orientation", example: "Conduit la stratégie d'expansion", powerLevel: "fort" },
      { word: "dérouler", nuance: "suggère l'exécution", example: "Déroulé le plan stratégique", powerLevel: "neutre" },
      { word: "exécuter", nuance: "suggère la réalisation", example: "Exécuté la stratégie définie", powerLevel: "fort" },
      { word: "mettre en œuvre", nuance: "neutre, plus descriptif", example: "Mis en œuvre le plan stratégique", powerLevel: "neutre" },
      { word: "déployer", nuance: "suggère l'expansion", example: "Déployé la stratégie EMEA", powerLevel: "fort" },
      { word: "incarner", nuance: "suggère l'incarnation", example: "Incarne la vision stratégique", powerLevel: "fort" },
      { word: "opérationnaliser", nuance: "suggère la mise en pratique", example: "Opérationnalisé la stratégie", powerLevel: "fort" },
    ],
    cvUseCase: "Dans un CV exec, 'conduit' et 'déployé' sont les plus forts. Évitez 'déroulé' (trop mécanique).",
    faq: [
      { question: "Piloter vs Conduire ?", answer: "'Piloter' = contrôler. 'Conduire' = orienter. Pour les transformations, 'piloter'. Pour les stratégies, 'conduire'." },
      { question: "Exécuter est-il trop opérationnel ?", answer: "Non, ça montre la capacité d'exécution. Ex: 'Exécuté la stratégie définie par le Board'." },
      { question: "Opérationnaliser est-il français ?", answer: "Oui, mais jargon. Préférez 'mis en œuvre' ou 'déployé'." },
    ],
  },
  {
    slug: "synonyme-implementer",
    word: "implémentater",
    category: "Stratégie",
    context: "Anglicisme très répandu. À varier en français.",
    synonyms: [
      { word: "mettre en place", nuance: "neutre, plus descriptif", example: "Mis en place le nouveau process", powerLevel: "neutre" },
      { word: "déployer", nuance: "suggère l'expansion", example: "Déployé la solution EMEA", powerLevel: "fort" },
      { word: "instaurer", nuance: "suggère la mise en place formelle", example: "Instauré une nouvelle gouvernance", powerLevel: "neutre" },
      { word: "installer", nuance: "neutre, suggère la mise en place", example: "Installé le nouveau CRM", powerLevel: "neutre" },
      { word: "opérationnaliser", nuance: "suggère la mise en pratique", example: "Opérationnalisé le plan", powerLevel: "fort" },
      { word: "dérouler", nuance: "suggère l'exécution", example: "Déroulé le plan", powerLevel: "neutre" },
      { word: "appliquer", nuance: "neutre, suggère la mise en application", example: "Appliqué la nouvelle politique", powerLevel: "neutre" },
    ],
    cvUseCase: "Dans un CV exec, 'mis en place' et 'déployé' sont les plus standards. Évitez 'implémenter' (anglicisme).",
    faq: [
      { question: "Implémentater est-il français ?", answer: "Anglicisme. Préférez 'mis en place', 'déployé', 'instauré'." },
      { question: "Déployer vs Mettre en place ?", answer: "'Déployer' = expansion large. 'Mettre en place' = mise en place. Pour les stratégies, 'déployer'." },
      { question: "Quand utiliser 'instaurer' ?", answer: "Pour les nouveautés formelles. Ex: 'Instauré une nouvelle gouvernance'." },
    ],
  },
  {
    slug: "synonyme-aligner",
    word: "aligner",
    category: "Stratégie",
    context: "Très utilisé en management moderne. À varier.",
    synonyms: [
      { word: "harmoniser", nuance: "suggère la cohérence", example: "Harmonisé les process 5 pays", powerLevel: "neutre" },
      { word: "cohérencer", nuance: "néologisme, suggère la cohérence", example: "Cohérencé les actions", powerLevel: "doux" },
      { word: "synchroniser", nuance: "suggère la coordination", example: "Synchronisé les équipes", powerLevel: "neutre" },
      { word: "rallier", nuance: "suggère la convainction", example: "Rallié le Board à la stratégie", powerLevel: "fort" },
      { word: "orienter", nuance: "suggère la direction", example: "Orienté les équipes vers l'objectif", powerLevel: "neutre" },
      { word: "fédérer", nuance: "suggère le rassemblement", example: "Fédéré 5 directions", powerLevel: "fort" },
      { word: "converger", nuance: "suggère la convergence", example: "Fait converger les intérêts", powerLevel: "neutre" },
    ],
    cvUseCase: "Dans un CV exec, 'aligné' reste standard. Variez avec 'harmonisé' (process), 'fédéré' (équipes).",
    faq: [
      { question: "Aligner vs Harmoniser ?", answer: "'Aligner' = mettre sur le même axe. 'Harmoniser' = rendre cohérent. Pour les process, 'harmoniser'." },
      { question: "Synchroniser est-il exec ?", answer: "Oui, pour les opérations. Ex: 'Synchronisé 12 sites de production'." },
      { question: "Comment éviter la répétition d'aligner ?", answer: "Variez avec 'harmonisé', 'fédéré', 'rallié'. Évitez 'cohérencer' (néologisme)." },
    ],
  },
  {
    slug: "synonyme-anticiper",
    word: "anticiper",
    category: "Stratégie",
    context: "Très valorisé en exec — montrez la vision long-terme.",
    synonyms: [
      { word: "prévoir", nuance: "neutre, suggère la prévision", example: "Prévu l'évolution du marché", powerLevel: "neutre" },
      { word: "préempter", nuance: "suggère l'avantage", example: "Préempté le marché LATAM", powerLevel: "fort" },
      { word: "devancer", nuance: "suggère l'avance", example: "Devancé les concurrents", powerLevel: "fort" },
      { word: "pressentir", nuance: "plus intuitif", example: "Pressenti la transformation", powerLevel: "doux" },
      { word: "pressentir", nuance: "suggère l'intuition", example: "Pressenti le virage tech", powerLevel: "doux" },
      { word: "préparer", nuance: "neutre, suggère l'action", example: "Préparé la transition", powerLevel: "neutre" },
      { word: "faire face", nuance: "suggère la réponse", example: "Fait face à la crise", powerLevel: "neutre" },
    ],
    cvUseCase: "Dans un CV exec, 'anticipé' et 'préempté' sont les plus forts. Variez avec 'devancé' (concurrence).",
    faq: [
      { question: "Anticiper vs Prévoir ?", answer: "'Anticiper' = agir en avance. 'Prévoir' = prédict. Pour les stratégies, 'anticiper'." },
      { question: "Préempter est-il exec ?", answer: "Très, surtout pour les marchés. Ex: 'Préempté le marché LATAM'." },
      { question: "Devancer est-il professionnel ?", answer: "Oui, surtout vs concurrence. Ex: 'Devancé les concurrents de 18 mois'." },
    ],
  },
  {
    slug: "synonyme-enclencher",
    word: "enclencher",
    category: "Stratégie",
    context: "Pour montrer le démarrage de process.",
    synonyms: [
      { word: "lancer", nuance: "suggère le démarrage", example: "Lancé la transformation", powerLevel: "fort" },
      { word: "initier", nuance: "suggère la première fois", example: "Initié le projet", powerLevel: "fort" },
      { word: "déclencher", nuance: "suggère le déclenchement", example: "Déclenché la procédure", powerLevel: "neutre" },
      { word: "démarrer", nuance: "plus dynamique", example: "Démarré l'activité", powerLevel: "neutre" },
      { word: "amorcer", nuance: "suggère le début", example: "Amorcé la transformation", powerLevel: "neutre" },
      { word: "engager", nuance: "suggère l'engagement", example: "Engagé le processus", powerLevel: "neutre" },
      { word: "mettre en branle", nuance: "familier, suggère l'action", example: "Mis en branle la machine", powerLevel: "doux" },
    ],
    cvUseCase: "Dans un CV exec, 'lancé' et 'initié' sont les plus impactants. Évitez 'mis en branle' (familier).",
    faq: [
      { question: "Enclencher vs Lancer ?", answer: "'Enclencher' = démarrer un mécanisme. 'Lancer' = démarrer de façon visible. Pour les projets, 'lancer'." },
      { question: "Initier est-il exec ?", answer: "Très, surtout pour les premières fois. Ex: 'Initié la transformation digitale'." },
      { question: "Déclencher vs Enclencher ?", answer: "'Déclencher' = action ponctuelle. 'Enclencher' = démarrage progressif." },
    ],
  },

  // ═══ RÉSULTAT (10) ═══
  {
    slug: "synonyme-augmenter",
    word: "augmenter",
    category: "Résultat",
    context: "Central en CV exec — montrez l'impact chiffré.",
    synonyms: [
      { word: "croître", nuance: "plus formel, suggère la croissance", example: "Fait croître l'ARR de 8 à 25 M€", powerLevel: "fort" },
      { word: "doubler", nuance: "très précis, suggère x2", example: "Doublé le CA en 24 mois", powerLevel: "fort" },
      { word: "tripler", nuance: "très précis, suggère x3", example: "Triplé l'ARR en 36 mois", powerLevel: "fort" },
      { word: "multiplier", nuance: "suggère la factorielle", example: "Multiplié le CA par 4", powerLevel: "fort" },
      { word: "booster", nuance: "anglicisme, suggère l'effet", example: "Boosté la croissance", powerLevel: "neutre" },
      { word: "maximiser", nuance: "suggère l'optimum", example: "Maximisé le ROI", powerLevel: "fort" },
      { word: "développer", nuance: "neutre, suggère la croissance", example: "Développé l'activité", powerLevel: "neutre" },
    ],
    cvUseCase: "Dans un CV exec, précisez le facteur : 'doublé', 'triplé', 'multiplié par X'. Plus impactant que 'augmenté'.",
    faq: [
      { question: "Augmenter vs Croître ?", answer: "'Augmenter' = générique. 'Croître' = croissance organique. Préférez 'croître' ou les facteurs (doublé, triplé)." },
      { question: "Comment chiffrer la croissance ?", answer: "Précis : 'Doublé le CA (de 8 à 16 M€)'. Pourcentage : '+120%'. Multiple : 'x3'. Le facteur est le plus impactant." },
      { question: "Booster est-il professionnel ?", answer: "Anglicisme accepté en business. Préférez 'boosté' (participe) ou 'acceleré'." },
    ],
  },
  {
    slug: "synonyme-reduire",
    word: "réduire",
    category: "Résultat",
    context: "Central en CV exec — montrez les gains de coûts.",
    synonyms: [
      { word: "diminuer", nuance: "neutre, suggère la baisse", example: "Diminué les coûts de 22%", powerLevel: "neutre" },
      { word: "réduire", nuance: "neutre", example: "Réduit le churn de 12% à 4%", powerLevel: "neutre" },
      { word: "amoindrir", nuance: "plus doux", example: "Amoindri les risques", powerLevel: "doux" },
      { word: "baisser", nuance: "neutre", example: "Baissé les prix de 8%", powerLevel: "neutre" },
      { word: "compresser", nuance: "suggère la pression", example: "Compressé les délais", powerLevel: "fort" },
      { word: "rétrécir", nuance: "suggère la taille", example: "Rétréci le portefeuille", powerLevel: "doux" },
      { word: "tailler", nuance: "suggère l'action", example: "Taillé dans les coûts", powerLevel: "fort" },
      { word: "diviser", nuance: "suggère la factorielle", example: "Divisé par 2", powerLevel: "fort" },
    ],
    cvUseCase: "Dans un CV exec, 'réduit' reste standard. Préférez les chiffres précis : 'divisé par 2', 'réduit de 22%'.",
    faq: [
      { question: "Réduire vs Diminuer ?", answer: "Très proches. 'Réduire' plus courant en business. 'Diminuer' légèrement plus formel." },
      { question: "Comment parler de réductions de coûts ?", answer: "Précisez : 'Réduit les coûts de 22% (8 M€/an)'. Le % et le montant absolus sont plus impactants." },
      { question: "Compresser est-il exec ?", answer: "Pour les délais et coûts, ça marche. Ex: 'Compressé le cycle de vente de 90 à 65 jours'." },
    ],
  },
  {
    slug: "synonyme-atteindre",
    word: "atteindre",
    category: "Résultat",
    context: "Pour montrer l'atteinte des objectifs.",
    synonyms: [
      { word: "réaliser", nuance: "neutre, suggère l'accomplissement", example: "Réalisé 95% des objectifs", powerLevel: "neutre" },
      { word: "accomplir", nuance: "suggère l'effort", example: "Accompli la transformation", powerLevel: "fort" },
      { word: "concrétiser", nuance: "suggère la matérialisation", example: "Concrétisé la vision", powerLevel: "fort" },
      { word: "franchir", nuance: "suggère le passage", example: "Franchi le cap du million", powerLevel: "neutre" },
      { word: "dpasser", nuance: "suggère l'excellence", example: "Dépassé les objectifs de 18%", powerLevel: "fort" },
      { word: "toucher", nuance: "neutre", example: "Touché le objectif visé", powerLevel: "doux" },
      { word: "exaucer", nuance: "très formel", example: "Exaucé la promesse", powerLevel: "fort" },
    ],
    cvUseCase: "Dans un CV exec, 'dépassé' est le plus impactant (excellence). Variez avec 'réalisé' (neutre), 'accompli' (effort).",
    faq: [
      { question: "Atteindre vs Réaliser ?", answer: "'Atteindre' = objectif. 'Réaliser' = accomplir. Pour les objectifs, 'atteint'." },
      { question: "Dépasser est-il exec ?", answer: "Très, surtout vs objectif. Ex: 'Dépassé les objectifs de 18%'." },
      { question: "Comment montrer l'atteinte d'objectifs ?", answer: "Précisez : 'Atteint 105% de l'objectif' ou 'Dépassé les objectifs de 18%'. Le chiffre est crucial." },
    ],
  },
  {
    slug: "synonyme-obtenir",
    word: "obtenir",
    category: "Résultat",
    context: "Pour montrer les résultats concrets.",
    synonyms: [
      { word: "décrocher", nuance: "plus dynamique", example: "Décroché le contrat de 25 M€", powerLevel: "neutre" },
      { word: "sécuriser", nuance: "suggère la garantie", example: "Sécurisé le deal", powerLevel: "fort" },
      { word: "réussir", nuance: "neutre", example: "Réussi la transformation", powerLevel: "neutre" },
      { word: "gagner", nuance: "suggère la competition", example: "Gagné le marché", powerLevel: "fort" },
      { word: "conquérir", nuance: "très fort, suggère l'effort", example: "Conquis le marché européen", powerLevel: "fort" },
      { word: "arracher", nuance: "très fort, suggère la difficulté", example: "Arraché la victory", powerLevel: "fort" },
      { word: "récolter", nuance: "suggère le fruit", example: "Récolté les fruits", powerLevel: "doux" },
    ],
    cvUseCase: "Dans un CV exec, 'obtenu' reste standard. Variez avec 'sécurisé' (garantie), 'conquis' (marché).",
    faq: [
      { question: "Obtenir vs Décrocher ?", answer: "'Obtenir' = neutre. 'Décrocher' = effort. Pour les contrats importants, 'décroché'." },
      { question: "Conquérir est-il exec ?", answer: "Très, surtout pour les marchés. Ex: 'Conquis le marché européen'." },
      { question: "Arracher est-il trop fort ?", answer: "Pour les victoires difficiles, ça marche. Sinon, préférez 'obtenu' ou 'décroché'." },
    ],
  },
  {
    slug: "synonyme-generer",
    word: "générer",
    category: "Résultat",
    context: "Très utilisé en business. À varier.",
    synonyms: [
      { word: "produire", nuance: "neutre", example: "Produit 45 M€ de CA", powerLevel: "neutre" },
      { word: "créer", nuance: "suggère la nouveauté", example: "Créé 28 M€ de valeur", powerLevel: "fort" },
      { word: "dégager", nuance: "suggère le résultat", example: "Dégagé 12 M€ d'EBITDA", powerLevel: "neutre" },
      { word: "rapporter", nuance: "suggère le gain", example: "Rapporté 8 M€/an", powerLevel: "neutre" },
      { word: "engendrer", nuance: "suggère la cause", example: "Engendré 35% de croissance", powerLevel: "neutre" },
      { word: "procurer", nuance: "plus formel", example: "Procuré 5 M€ d'économies", powerLevel: "neutre" },
      { word: "occasionner", nuance: "suggère la conséquence", example: "Occasionné 2 M€ de gains", powerLevel: "doux" },
    ],
    cvUseCase: "Dans un CV exec, 'généré' et 'dégagé' sont les plus standards. Variez avec 'créé' (valeur).",
    faq: [
      { question: "Générer vs Dégager ?", answer: "Très proches. 'Générer' = produire. 'Dégager' = libérer. Pour l'EBITDA, 'dégagé'." },
      { question: "Créer est-il exec ?", answer: "Oui, surtout pour la valeur. Ex: 'Créé 28 M€ de valeur actionnariale'." },
      { question: "Comment parler de génération de CA ?", answer: "Précis : 'Généré 45 M€ de CA (+32%)'. Le montant et le % sont plus impactants." },
    ],
  },
  {
    slug: "synonyme-optimiser-resultats",
    word: "optimiser (résultats)",
    category: "Résultat",
    context: "Pour montrer l'amélioration des KPIs.",
    synonyms: [
      { word: "améliorer", nuance: "neutre", example: "Amélioré la marge de 4 pts", powerLevel: "neutre" },
      { word: "maximiser", nuance: "suggère l'optimum", example: "Maximisé le ROI", powerLevel: "fort" },
      { word: "booster", nuance: "anglicisme", example: "Boosté la performance", powerLevel: "neutre" },
      { word: "propulser", nuance: "très fort", example: "Propulsé le CA", powerLevel: "fort" },
      { word: "fiabiliser", nuance: "suggère la robustesse", example: "Fiabilisé les process", powerLevel: "neutre" },
      { word: "industrialiser", nuance: "suggère la scalabilité", example: "Industrialisé la méthode", powerLevel: "fort" },
      { word: "sublimer", nuance: "très fort, suggère l'excellence", example: "Sublimé les résultats", powerLevel: "fort" },
    ],
    cvUseCase: "Dans un CV exec, 'optimisé' reste standard. Variez avec 'maximisé' (impact), 'industrialisé' (scale).",
    faq: [
      { question: "Optimiser vs Maximiser ?", answer: "'Optimiser' = atteindre l'optimum. 'Maximiser' = au max. Pour les KPIs, 'maximisé' plus fort." },
      { question: "Propulser est-il professionnel ?", answer: "Pour les pics de croissance, ça marche. Sinon, préférez 'boosté' ou 'maximisé'." },
      { question: "Comment montrer l'optimisation ?", answer: "Précisez : 'Optimisé les coûts de 22% (8 M€/an)'. Le % et le montant sont plus impactants." },
    ],
  },
  {
    slug: "synonyme-realiser",
    word: "réaliser",
    category: "Résultat",
    context: "Très fréquent. À varier.",
    synonyms: [
      { word: "accomplir", nuance: "suggère l'effort", example: "Accompli la transformation", powerLevel: "fort" },
      { word: "atteindre", nuance: "suggère l'objectif", example: "Atteint les objectifs", powerLevel: "neutre" },
      { word: "concrétiser", nuance: "suggère la matérialisation", example: "Concrétisé la vision", powerLevel: "fort" },
      { word: "exécuter", nuance: "suggère l'action", example: "Exécuté le plan", powerLevel: "fort" },
      { word: "materialiser", nuance: "suggère la matérialisation", example: "Matérialisé les gains", powerLevel: "neutre" },
      { word: "mener à bien", nuance: "suggère l'achèvement", example: "Mené à bien le projet", powerLevel: "neutre" },
      { word: "boucler", nuance: "familier, suggère la finalisation", example: "Bouclé le tour de table", powerLevel: "doux" },
    ],
    cvUseCase: "Dans un CV exec, 'réalisé' reste standard. Variez avec 'accompli' (effort), 'concrétisé' (vision).",
    faq: [
      { question: "Réaliser vs Accomplir ?", answer: "'Réaliser' = générique. 'Accomplir' = effort. Pour les transformations, 'accompli'." },
      { question: "Boucler est-il professionnel ?", answer: "Familier. Préférez 'finalisé' ou 'clôturé' en CV formel. 'Bouclé' OK en tech/scale-up." },
      { question: "Comment montrer la réalisation ?", answer: "Précisez le résultat : 'Réalisé 28 M€ de CA (+32%)'. Le chiffre est crucial." },
    ],
  },
  {
    slug: "synonyme-surpasser",
    word: "surpasser",
    category: "Résultat",
    context: "Pour montrer l'excellence et le dépassement.",
    synonyms: [
      { word: "dépasser", nuance: "neutre", example: "Dépassé les objectifs de 18%", powerLevel: "neutre" },
      { word: "excéder", nuance: "plus formel", example: "Excédé les prévisions", powerLevel: "neutre" },
      { word: "transcender", nuance: "très fort", example: "Transcendé les attentes", powerLevel: "fort" },
      { word: "outrepasser", nuance: "très formel", example: "Outrepassé les limites", powerLevel: "fort" },
      { word: "déborder", nuance: "suggère le trop-plein", example: "Débordé les attentes", powerLevel: "neutre" },
      { word: "exceder", nuance: "neutre", example: "Excédé les objectifs", powerLevel: "neutre" },
      { word: "déclasser", nuance: "très fort", example: "Déclassé la concurrence", powerLevel: "fort" },
    ],
    cvUseCase: "Dans un CV exec, 'dépassé' est le plus standard. 'Transcendé' est très fort pour les succès majeurs.",
    faq: [
      { question: "Surpasser vs Dépasser ?", answer: "'Surpasser' = surpasser. 'Dépasser' = aller au-delà. Très proches. 'Dépassé' plus courant." },
      { question: "Transcender est-il exec ?", answer: "Pour les réussites exceptionnelles, ça marche. Ex: 'Transcendé les attentes du Board'." },
      { question: "Comment montrer l'excellence ?", answer: "Précisez : 'Dépassé les objectifs de 28%'. Le % est crucial. 'Transcendé' pour les pics." },
    ],
  },
  {
    slug: "synonyme-degager",
    word: "dégager",
    category: "Résultat",
    context: "Spécifique aux résultats financiers (EBITDA, marge, cash).",
    synonyms: [
      { word: "générer", nuance: "neutre", example: "Généré 45 M€ de CA", powerLevel: "neutre" },
      { word: "produire", nuance: "neutre", example: "Produit 12 M€ d'EBITDA", powerLevel: "neutre" },
      { word: "réaliser", nuance: "neutre", example: "Réalisé 8 M€ de cash", powerLevel: "neutre" },
      { word: "libérer", nuance: "suggère la libération", example: "Libéré 12 M€ de trésorerie", powerLevel: "fort" },
      { word: "créer", nuance: "suggère la valeur", example: "Créé 28 M€ de valeur", powerLevel: "fort" },
      { word: "apporter", nuance: "suggère la contribution", example: "Apporté 5 M€ d'économies", powerLevel: "neutre" },
      { word: "distribuer", nuance: "suggère le partage", example: "Distribué 2 M€ de dividendes", powerLevel: "neutre" },
    ],
    cvUseCase: "Dans un CV exec, 'dégagé' reste standard pour l'EBITDA. Variez avec 'libéré' (cash), 'créé' (valeur).",
    faq: [
      { question: "Dégager vs Générer ?", answer: "Très proches. 'Dégager' = libérer (cash, EBITDA). 'Générer' = produire (CA). Pour l'EBITDA, 'dégagé'." },
      { question: "Comment parler d'EBITDA ?", answer: "Précis : 'Dégagé 12 M€ d'EBITDA (marge 18%)'. Le montant et la marge sont attendus." },
      { question: "Libérer est-il exec ?", answer: "Très, surtout pour le cash. Ex: 'Libéré 12 M€ de trésorerie via optimisation BFR'." },
    ],
  },
  {
    slug: "synonyme-liberer",
    word: "libérer",
    category: "Résultat",
    context: "Pour montrer le déblocage de cash, ressources, énergie.",
    synonyms: [
      { word: "dégager", nuance: "suggère le résultat", example: "Dégagé 12 M€ de cash", powerLevel: "neutre" },
      { word: "affranchir", nuance: "suggère l'émancipation", example: "Affranchi les équipes des process", powerLevel: "fort" },
      { word: "débarrasser", nuance: "suggère l'élimination", example: "Débarrassé l'organisation des tâches à faible valeur", powerLevel: "fort" },
      { word: "rendre disponible", nuance: "neutre", example: "Rendu disponible 8 M€", powerLevel: "neutre" },
      { word: "débloquer", nuance: "suggère le déblocage", example: "Débloqué 5 M€ de budget", powerLevel: "fort" },
      { word: "désengorger", nuance: "suggère la fluidification", example: "Désengorgé les process", powerLevel: "neutre" },
      { word: "démultiplier", nuance: "très fort, suggère la multiplication", example: "Démultiplié l'impact", powerLevel: "fort" },
    ],
    cvUseCase: "Dans un CV exec, 'libéré' est puissant pour le cash. Variez avec 'débloqué' (budget), 'démultiplié' (impact).",
    faq: [
      { question: "Libérer vs Dégager ?", answer: "'Libérer' = rendre disponible. 'Dégager' = produire. Pour le cash bloqué, 'libéré'." },
      { question: "Débloquer est-il exec ?", answer: "Très, surtout pour le budget. Ex: 'Débloqué 5 M€ de budget R&D'." },
      { question: "Comment montrer l'impact cash ?", answer: "Précisez : 'Libéré 12 M€ de trésorerie via réduction BFR'. Le mécanisme et le montant sont attendus." },
    ],
  },

  // ═══ COMMUNICATION (7) ═══
  {
    slug: "synonyme-presenter",
    word: "présenter",
    category: "Communication",
    context: "Central en exec — présentations Board, Comex, conférences.",
    synonyms: [
      { word: "exposer", nuance: "suggère la clarté", example: "Exposé la stratégie au Board", powerLevel: "neutre" },
      { word: "soumettre", nuance: "suggère la soumission", example: "Soumis le plan au Board", powerLevel: "neutre" },
      { word: "défendre", nuance: "suggère l'engagement", example: "Défendu le budget au Comex", powerLevel: "fort" },
      { word: "pitchater", nuance: "anglicisme, suggère le pitch", example: "Pitché le projet aux investisseurs", powerLevel: "neutre" },
      { word: "partager", nuance: "suggère la transparence", example: "Partagé les résultats au town hall", powerLevel: "neutre" },
      { word: "soumettre", nuance: "suggère la proposition", example: "Soumis les options au Board", powerLevel: "neutre" },
      { word: "rendre compte", nuance: "suggère le reporting", example: "Rendu compte au Board trimestriellement", powerLevel: "neutre" },
    ],
    cvUseCase: "Dans un CV exec, 'présenté' reste standard. Variez avec 'défendu' (engagement), 'rendu compte' (reporting).",
    faq: [
      { question: "Présenter vs Exposer ?", answer: "'Présenter' = montrer. 'Exposer' = expliquer. Pour le Board, 'présenté' ou 'exposé'." },
      { question: "Défendre est-il exec ?", answer: "Très, surtout pour le Board. Ex: 'Défendu le budget transformation au Board'." },
      { question: "Pitchater est-il français ?", answer: "Anglicisme. Préférez 'présenté' ou 'pitché' en tech. 'Pitché' OK en startup/scale-up." },
    ],
  },
  {
    slug: "synonyme-convaincre",
    word: "convaincre",
    category: "Communication",
    context: "Central en leadership — montrez la capacité de persuasion.",
    synonyms: [
      { word: "persuader", nuance: "suggère la persuasion", example: "Persuadé le Board d'investir", powerLevel: "fort" },
      { word: "rallier", nuance: "suggère la convainction", example: "Rallié le Comex à la stratégie", powerLevel: "fort" },
      { word: "emporter", nuance: "suggère la victory", example: "Emporté l'adhésion du Board", powerLevel: "fort" },
      { word: "gagner", nuance: "suggère le gain", example: "Gagné la confiance du CEO", powerLevel: "neutre" },
      { word: "convertir", nuance: "suggère la transformation", example: "Convertis les sceptiques", powerLevel: "fort" },
      { word: "séduire", nuance: "suggère l'attrait", example: "Séduit les investisseurs", powerLevel: "neutre" },
      { word: "embarquer", nuance: "familier, suggère l'adhésion", example: "Embarqué les équipes", powerLevel: "doux" },
    ],
    cvUseCase: "Dans un CV exec, 'convaincu' et 'rallié' sont les plus impactants. Évitez 'embarqué' (familier).",
    faq: [
      { question: "Convaincre vs Persuader ?", answer: "Très proches. 'Convaincre' = raison. 'Persuader' = émotion. Pour le Board, 'convaincu'." },
      { question: "Rallier est-il exec ?", answer: "Très, surtout pour le Comex/Board. Ex: 'Rallié le Comex à la nouvelle stratégie'." },
      { question: "Comment montrer la persuasion ?", answer: "Précisez le résultat : 'Convaincu le Board d'investir 50 M€ (unanimité)'." },
    ],
  },
  {
    slug: "synonyme-expliquer",
    word: "expliquer",
    category: "Communication",
    context: "Pour montrer la pédagogie et la communication.",
    synonyms: [
      { word: "présenter", nuance: "neutre", example: "Présenté la stratégie au Board", powerLevel: "neutre" },
      { word: "exposer", nuance: "suggère la clarté", example: "Exposé les enjeux", powerLevel: "neutre" },
      { word: "détailler", nuance: "suggère le détail", example: "Détaillé le plan", powerLevel: "neutre" },
      { word: "vulgariser", nuance: "suggère la simplification", example: "Vulgarisé les enjeux tech", powerLevel: "neutre" },
      { word: "clarifier", nuance: "suggère la clarté", example: "Clarifié les objectifs", powerLevel: "neutre" },
      { word: "expliciter", nuance: "très formel", example: "Explicité la décision", powerLevel: "neutre" },
      { word: "exposer", nuance: "suggère la mise en lumière", example: "Exposé le raisonnement", powerLevel: "neutre" },
    ],
    cvUseCase: "Dans un CV exec, 'présenté' et 'clarifié' sont les plus standards. Variez avec 'vulgarisé' (pédagogie).",
    faq: [
      { question: "Expliquer vs Présenter ?", answer: "'Expliquer' = faire comprendre. 'Présenter' = montrer. Pour le Board, 'présenté'. Pour la pédagogie, 'expliqué'." },
      { question: "Vulgariser est-il exec ?", answer: "Pour la tech/finance, ça montre la pédagogie. Ex: 'Vulgarisé les enjeux IA pour le Board'." },
      { question: "Comment montrer la communication ?", answer: "Mentionnez les audiences : Board, Comex, town halls, conférences. 'Présenté à 5 Boards annuels'." },
    ],
  },
  {
    slug: "synonyme-negocier-contrats",
    word: "négocier (contrats)",
    category: "Communication",
    context: "Central en exec — négociations M&A, contrats, partnerships.",
    synonyms: [
      { word: "conclure", nuance: "suggère la finalisation", example: "Conclu 12 partnerships", powerLevel: "fort" },
      { word: "sécuriser", nuance: "suggère la garantie", example: "Sécurisé le deal", powerLevel: "fort" },
      { word: "arranger", nuance: "neutre", example: "Arrangé les termes", powerLevel: "neutre" },
      { word: "traiter", nuance: "neutre", example: "Traité 18 dossiers", powerLevel: "neutre" },
      { word: "débattre", nuance: "suggère la discussion", example: "Débattu les termes", powerLevel: "neutre" },
      { word: "discuter", nuance: "neutre", example: "Discuté les modalités", powerLevel: "neutre" },
      { word: "parlementer", nuance: "très formel", example: "Parlementé avec les syndicats", powerLevel: "fort" },
    ],
    cvUseCase: "Dans un CV exec, 'négocié' reste standard. Variez avec 'conclu' (résultat), 'sécurisé' (garantie).",
    faq: [
      { question: "Négocier vs Conclure ?", answer: "'Négocier' = process. 'Conclure' = résultat. Pour les deals réussis, 'conclu'." },
      { question: "Comment montrer les négociations ?", answer: "Précisez : 'Négocié 12 partnerships (45 M€ total)'. Le nombre et le montant sont impactants." },
      { question: "Parlementer est-il professionnel ?", answer: "Pour les négociations sociales (syndicats), ça marche. Ex: 'Parlementé avec les syndicats (CSE)'." },
    ],
  },
  {
    slug: "synonyme-communiquer",
    word: "communiquer",
    category: "Communication",
    context: "Pour montrer la communication interne et externe.",
    synonyms: [
      { word: "transmettre", nuance: "suggère le transfert", example: "Transmis la vision", powerLevel: "neutre" },
      { word: "partager", nuance: "suggère la transparence", example: "Partagé les résultats", powerLevel: "neutre" },
      { word: "diffuser", nuance: "suggère la propagation", example: "Diffusé la stratégie", powerLevel: "neutre" },
      { word: "annoncer", nuance: "suggère l'officialisation", example: "Annoncé la transformation", powerLevel: "fort" },
      { word: "informer", nuance: "neutre", example: "Informé les équipes", powerLevel: "neutre" },
      { word: "échanger", nuance: "suggère la双向", example: "Échangé avec les équipes", powerLevel: "neutre" },
      { word: "officialiser", nuance: "suggère la formalisation", example: "Officialisé la nouvelle organisation", powerLevel: "fort" },
    ],
    cvUseCase: "Dans un CV exec, 'communiqué' reste standard. Variez avec 'annoncé' (officialisation), 'transmis' (vision).",
    faq: [
      { question: "Communiquer vs Transmettre ?", answer: "'Communiquer' = générique. 'Transmettre' = transfert. Pour la vision, 'transmis'." },
      { question: "Annoncer est-il exec ?", answer: "Très, surtout pour les transformations. Ex: 'Annoncé la transformation au town hall (800 personnes)'." },
      { question: "Comment montrer la communication ?", answer: "Précisez l'audience et la fréquence. 'Communiqué au Board trimestriellement, au Comex mensuellement, à 800 personnes en town hall'." },
    ],
  },
  {
    slug: "synonyme-defendre",
    word: "défendre",
    category: "Communication",
    context: "Pour montrer l'engagement et la conviction au Board/Comex.",
    synonyms: [
      { word: "soutenir", nuance: "neutre", example: "Soutenu le projet au Board", powerLevel: "neutre" },
      { word: "promouvoir", nuance: "suggère la valorisation", example: "Promu la stratégie", powerLevel: "fort" },
      { word: "prôner", nuance: "suggère l'advocacy", example: "Prôné la transformation", powerLevel: "fort" },
      { word: "plaider", nuance: "suggère le plaidoyer", example: "Plaidé pour l'investissement", powerLevel: "fort" },
      { word: "argumenter", nuance: "suggère l'argumentation", example: "Argumenté la décision", powerLevel: "neutre" },
      { word: "revendiquer", nuance: "suggère la revendication", example: "Revendiqué le budget", powerLevel: "fort" },
      { word: "batailler", nuance: "familier, suggère l'effort", example: "Bataillé pour le projet", powerLevel: "doux" },
    ],
    cvUseCase: "Dans un CV exec, 'défendu' et 'plaidé' sont les plus forts. Évitez 'bataillé' (familier).",
    faq: [
      { question: "Défendre vs Soutenir ?", answer: "'Défendre' = engagement actif. 'Soutenir' = appui. Pour le Board, 'défendu'." },
      { question: "Plaider est-il exec ?", answer: "Très, surtout pour les décisions majeures. Ex: 'Plaidé pour l'investissement de 50 M€ (unanimité)'." },
      { question: "Comment montrer l'engagement ?", answer: "Précisez le résultat : 'Défendu le budget transformation (50 M€) au Board, vote unanime'." },
    ],
  },
  {
    slug: "synonyme-representer",
    word: "représenter",
    category: "Communication",
    context: "Pour montrer la représentation externe (clients, partenaires, médias).",
    synonyms: [
      { word: "incarner", nuance: "suggère l'incarnation", example: "Incarne la vision du groupe", powerLevel: "fort" },
      { word: "personnifier", nuance: "suggère la personnification", example: "Personnifié la marque", powerLevel: "fort" },
      { word: "porter", nuance: "suggère le portage", example: "Porté la parole du groupe", powerLevel: "neutre" },
      { word: "présider", nuance: "suggère la présidence", example: "Présidé la délégation", powerLevel: "fort" },
      { word: "diriger", nuance: "suggère la direction", example: "Dirigé la délégation française", powerLevel: "fort" },
      { word: "embarquer", nuance: "familier", example: "Embarqué les parties prenantes", powerLevel: "doux" },
      { word: "incarner", nuance: "suggère l'incarnation", example: "Incarne les valeurs du groupe", powerLevel: "fort" },
    ],
    cvUseCase: "Dans un CV exec, 'représenté' reste standard. Variez avec 'incarné' (vision), 'présidé' (délégation).",
    faq: [
      { question: "Représenter vs Incarner ?", answer: "'Représenter' = être le représentant. 'Incarner' = être l'incarnation. Pour la vision, 'incarné'." },
      { question: "Présider est-il exec ?", answer: "Très, surtout pour les délégations. Ex: 'Présidé la délégation française au WEF Davos'." },
      { question: "Comment montrer la représentation ?", answer: "Précisez les contextes : 'Représenté le groupe au WEF Davos, au Medef International, aux rencontres présidentielles'." },
    ],
  },

  // ═══ MANAGEMENT (5) ═══
  {
    slug: "synonyme-structurer",
    word: "structurer",
    category: "Management",
    context: "Pour montrer la mise en ordre et l'organisation.",
    synonyms: [
      { word: "organiser", nuance: "neutre", example: "Organisé la direction", powerLevel: "neutre" },
      { word: "réorganiser", nuance: "suggère le changement", example: "Réorganisé 5 directions", powerLevel: "neutre" },
      { word: "rationaliser", nuance: "suggère la simplification", example: "Rationalisé le portefeuille", powerLevel: "neutre" },
      { word: "harmoniser", nuance: "suggère la cohérence", example: "Harmonisé les process", powerLevel: "neutre" },
      { word: "redresser", nuance: "suggère le redressement", example: "Redressé la direction sinistrée", powerLevel: "fort" },
      { word: "remodeler", nuance: "suggère le remodelage", example: "Remodelé l'organisation", powerLevel: "neutre" },
      { word: "discipliner", nuance: "suggère la rigueur", example: "Discipliné les process", powerLevel: "fort" },
    ],
    cvUseCase: "Dans un CV exec, 'structuré' reste standard. Variez avec 'rationalisé' (simplification), 'redressé' (redressement).",
    faq: [
      { question: "Structurer vs Organiser ?", answer: "'Structurer' = mettre en structure. 'Organiser' = mettre en ordre. Très proches. 'Structuré' plus formel." },
      { question: "Redresser est-il exec ?", answer: "Très, surtout pour les situations difficiles. Ex: 'Redressé la direction sinistrée (EBITDA -8% → +12%)'." },
      { question: "Comment montrer la réorganisation ?", answer: "Précisez l'impact : 'Restructuré 5 directions, économies 8 M€/an'." },
    ],
  },
  {
    slug: "synonyme-coordonner",
    word: "coordonner",
    category: "Management",
    context: "Pour montrer la mise en synergie.",
    synonyms: [
      { word: "harmoniser", nuance: "suggère la cohérence", example: "Harmonisé les actions", powerLevel: "neutre" },
      { word: "synchroniser", nuance: "suggère la simultanéité", example: "Synchronisé 12 sites", powerLevel: "neutre" },
      { word: "aligner", nuance: "suggère l'alignement", example: "Aligné les équipes", powerLevel: "neutre" },
      { word: "fédérer", nuance: "suggère le rassemblement", example: "Fédéré 5 directions", powerLevel: "fort" },
      { word: "articuler", nuance: "suggère l'articulation", example: "Articulé les actions", powerLevel: "neutre" },
      { word: "orchestrer", nuance: "suggère la coordination complexe", example: "Orchestré l'intégration M&A", powerLevel: "fort" },
      { word: "mise en synergie", nuance: "suggère la synergie", example: "Mis en synergie 3 équipes", powerLevel: "neutre" },
    ],
    cvUseCase: "Dans un CV exec, 'coordonné' reste standard. 'Orchestré' est plus fort pour les opérations complexes.",
    faq: [
      { question: "Coordonner vs Orchestrer ?", answer: "'Coordonner' = mise en synergie. 'Orchestrer' = coordination complexe. Pour les M&A, 'orchestré'." },
      { question: "Synchroniser est-il exec ?", answer: "Pour les opérations multi-sites, ça marche. Ex: 'Synchronisé 12 sites de production'." },
      { question: "Comment montrer la coordination ?", answer: "Précisez : 'Coordonné 5 directions transverses (180 personnes) sur le programme transformation'." },
    ],
  },
  {
    slug: "synonyme-superviser",
    word: "superviser",
    category: "Management",
    context: "Pour montrer le contrôle et l'encadrement.",
    synonyms: [
      { word: "contrôler", nuance: "suggère le contrôle", example: "Contrôlé 12 projets", powerLevel: "neutre" },
      { word: "encadrer", nuance: "suggère le mentorat", example: "Encadré 5 juniors", powerLevel: "doux" },
      { word: "diriger", nuance: "suggère l'autorité", example: "Dirigé l'équipe", powerLevel: "fort" },
      { word: "piloter", nuance: "suggère le contrôle actif", example: "Piloté le projet", powerLevel: "fort" },
      { word: "veiller sur", nuance: "plus doux", example: "Veillé sur 3 projets", powerLevel: "doux" },
      { word: "surveiller", nuance: "suggère la surveillance", example: "Surveillé les KPIs", powerLevel: "neutre" },
      { word: "monitorater", nuance: "anglicisme", example: "Monitoré les performances", powerLevel: "neutre" },
    ],
    cvUseCase: "Dans un CV exec, 'supervisé' reste standard. 'Piloté' est plus fort. Évitez 'monitorer' (anglicisme).",
    faq: [
      { question: "Superviser vs Piloter ?", answer: "'Superviser' = contrôler. 'Piloter' = contrôler activement. Pour les projets, 'piloté' plus fort." },
      { question: "Encadrer est-il exec ?", answer: "Plus pour les juniors. 'Encadré 5 juniors en rotation'. Pour les seniors, 'dirigé'." },
      { question: "Monitorater est-il français ?", answer: "Anglicisme. Préférez 'supervisé', 'contrôlé', 'suivi'." },
    ],
  },
  {
    slug: "synonyme-evaluer",
    word: "évaluer",
    category: "Management",
    context: "Pour montrer l'évaluation des équipes, projets, perf.",
    synonyms: [
      { word: "mesurer", nuance: "suggère la mesure", example: "Mesuré l'impact", powerLevel: "neutre" },
      { word: "analyser", nuance: "suggère l'analyse", example: "Analysé les performances", powerLevel: "neutre" },
      { word: "auditer", nuance: "suggère l'audit", example: "Audité 12 filiales", powerLevel: "neutre" },
      { word: "estimer", nuance: "suggère l'estimation", example: "Estimé les risques", powerLevel: "neutre" },
      { word: "jauger", nuance: "suggère la jauge", example: "Jaugé les compétences", powerLevel: "neutre" },
      { word: "noter", nuance: "suggère la notation", example: "Noté 45 fournisseurs", powerLevel: "neutre" },
      { word: "apprécier", nuance: "suggère l'appréciation", example: "Apprécie la performance", powerLevel: "neutre" },
    ],
    cvUseCase: "Dans un CV exec, 'évalué' reste standard. Variez avec 'audité' (audit), 'mesuré' (impact).",
    faq: [
      { question: "Évaluer vs Mesurer ?", answer: "'Évaluer' = apprécier. 'Mesurer' = quantifier. Pour les KPIs, 'mesuré'. Pour les équipes, 'évalué'." },
      { question: "Auditer est-il exec ?", answer: "Très, surtout pour le contrôle interne. Ex: 'Audité 12 filiales (zéro non-conformité majeure)'." },
      { question: "Comment montrer l'évaluation ?", answer: "Précisez : 'Évalué 45 fournisseurs (25% éliminés, 15% promus strategic partners)'." },
    ],
  },
  {
    slug: "synonyme-recruter",
    word: "recruter",
    category: "Management",
    context: "Central en exec — montrez la capacité à attirer les talents.",
    synonyms: [
      { word: "attirer", nuance: "suggère l'attraction", example: "Attiré 8 VPs", powerLevel: "fort" },
      { word: "sélectionner", nuance: "suggère la sélection", example: "Sélectionné 25 talents", powerLevel: "neutre" },
      { word: "embaucher", nuance: "neutre", example: "Embauché 45 personnes", powerLevel: "neutre" },
      { word: "intégrer", nuance: "suggère l'intégration", example: "Intégré 12 seniors", powerLevel: "neutre" },
      { word: "convaincre", nuance: "suggère la persuasion", example: "Convaincu 5 profils top tier", powerLevel: "fort" },
      { word: "débaucher", nuance: "familier, suggère l'approche active", example: "Débauché 3 stars", powerLevel: "doux" },
      { word: "faire venir", nuance: "neutre", example: "Fait venir 8 experts", powerLevel: "neutre" },
    ],
    cvUseCase: "Dans un CV exec, 'recruté' reste standard. 'Attiré' montre la marque employeur. Évitez 'débauché' (familier).",
    faq: [
      { question: "Recruter vs Attirer ?", answer: "'Recruter' = process. 'Attirer' = attraction. Pour la marque employeur, 'attiré'." },
      { question: "Comment montrer le recrutement ?", answer: "Précisez : 'Recruté 8 VPs (top quartile du marché), 5 encore en poste 3 ans après'." },
      { question: "Débaucher est-il exec ?", answer: "Familier. Préférez 'attiré' ou 'recruté' en CV formel. 'Débauché' OK en tech/scale-up." },
    ],
  },
];

// ─── Helpers ────────────────────────────────────────────────
export function getSynonymBySlug(slug: string): SynonymExample | undefined {
  return SYNONYM_EXAMPLES.find((s) => s.slug === slug);
}

export function getAllSynonymSlugs(): string[] {
  return SYNONYM_EXAMPLES.map((s) => s.slug);
}

export const SYNONYM_CATEGORIES: Array<{ id: SynonymExample["category"]; label: string; description: string }> = [
  { id: "Action", label: "Verbes d'action", description: "Diriger, piloter, créer, transformer, optimiser" },
  { id: "Leadership", label: "Verbes de leadership", description: "Accompagner, fédérer, motiver, déléguer, conseiller" },
  { id: "Stratégie", label: "Verbes de stratégie", description: "Élaborer, définir, concevoir, aligner, anticiper" },
  { id: "Résultat", label: "Verbes de résultat", description: "Augmenter, réduire, atteindre, générer, dépasser" },
  { id: "Communication", label: "Verbes de communication", description: "Présenter, convaincre, expliquer, négocier, défendre" },
  { id: "Management", label: "Verbes de management", description: "Structurer, coordonner, superviser, évaluer, recruter" },
];
