/**
 * CV Export Service — single source of truth for CV PDF generation.
 * All exports (dashboard, cv-print, extension, ZIP) must use this service.
 */

export interface CvExportInput {
  draftId: string;
  templateId?: string;
  includeFooter?: boolean;
  source?: "dashboard" | "cv-print" | "extension" | "zip";
}

export interface CvExportResult {
  pdfBytes: Uint8Array;
  filename: string;
  templateUsed: string;
  warnings: string[];
}

const VALID_TEMPLATES = [
  "ats_classic", "modern_executive", "premium_leadership",
  "executive_bordeaux", "strategic_blue", "minimal_luxe",
];

/**
 * Resolve a template ID string to a valid CvTemplateId.
 */
export function resolveCvTemplate(templateId?: string | null): string {
  if (!templateId) return "premium_leadership";
  const clean = templateId.replace(/-/g, "_").toLowerCase().trim();
  if (VALID_TEMPLATES.includes(clean)) return clean;
  // Try fuzzy match
  for (const valid of VALID_TEMPLATES) {
    if (clean.includes(valid.replace(/_/g, "")) || valid.includes(clean)) return valid;
  }
  return "premium_leadership";
}

/**
 * Sanitize rendered CV content before export.
 */
export function sanitizeCvForExport(content: string): string {
  let c = content;
  // Remove any stray footer-like text
  c = c.replace(/CV généré par PRSTO.*$/gmi, "");
  c = c.replace(/Document confidentiel.*$/gmi, "");
  c = c.replace(/Generated by PRSTO.*$/gmi, "");
  c = c.replace(/Confidential document.*$/gmi, "");
  // Clean JSON arrays in education
  c = c.replace(/\["(.*?)"\]/g, (_, m) => m || "");
  // Clean double spaces
  c = c.replace(/ {2,}/g, " ").trim();
  return c;
}
