"""Génère 15 nouveaux articles de blog avec auteurs internationaux variés."""

# 15 nouveaux auteurs internationaux (prénom only)
AUTHORS_15 = [
    {"name": "Kenji", "role": "Ex COO, Consultant Operational Excellence", "bio": "Ancien Chief Operating Officer d'un groupe technologique asiatique, il a piloté des transformations à grande échelle. Il accompagne les dirigeants dans l'excellence opérationnelle."},
    {"name": "Fatima", "role": "Executive Coach & Leadership Advisor", "bio": "Coach de dirigeants depuis 15 ans, elle a accompagné plus de 100 cadres C level dans leurs transitions. Spécialiste de l'intelligence émotionnelle au Comex."},
    {"name": "Hans", "role": "Ancien DG, Conseil en stratégie industrielle", "bio": "Dirigeant industriel pendant 20 ans dans 3 pays, il connaît les défis du manufacturing moderne et de la transition énergétique."},
    {"name": "Valentina", "role": "Talent Partner, ex cabinet de chasse international", "bio": "Chasseuse de têtes internationale, elle a mené des missions dans 12 pays. Experte des marchés dirigeants Europe-Amérique latine."},
    {"name": "Olu", "role": "CEO Coach & Board Consultant", "bio": "Ancien banquier d'affaires devenu coach de dirigeants, il a conseillé 30+ boards sur la gouvernance et la succession."},
    {"name": "Isabella", "role": "Career Strategist for Executives", "bio": "Stratège de carrière pour dirigeants, elle a aidé 150+ cadres à réussir leurs transitions professionnelles. Spécialiste du personal branding digital."},
    {"name": "Dmitri", "role": "Ex CFO, M&A Advisor", "bio": "Ancien DAF dans le secteur tech, il a piloté 12 acquisitions et 3 exits. Il forme les dirigeants aux stratégies de croissance externe."},
    {"name": "Amara", "role": "Chief People Officer, Conseil RH", "bio": "DRH dans des multinationales pendant 15 ans, elle a conçu et mis en œuvre des stratégies de transformation culturelle à grande échelle."},
    {"name": "Stefan", "role": "Managing Partner, Conseil en transformation", "bio": "Consultant en stratégie pendant 18 ans, il a accompagné des DG dans des transformations profondes d'entreprise."},
    {"name": "Leila", "role": "International Executive Search Consultant", "bio": "Consultante en recherche de dirigeants, elle connecte les talents C level avec les boards dans 15 pays."},
    {"name": "Marcus", "role": "Ex CEO, Leadership Speaker", "bio": "Ancien CEO de deux entreprises du mid cap, il partage ses retours d'expérience sur le leadership en temps de crise."},
    {"name": "Yuna", "role": "Executive Development Consultant", "bio": "Experte en développement du leadership, elle a formé plus de 200 cadres dirigeants aux compétences du 21e siècle."},
    {"name": "Pierre", "role": "Conseil en stratégie digitale pour dirigeants", "bio": "Ancien Chief Digital Officer, il accompagne les DG dans leur transformation numérique et leur vision stratégique."},
    {"name": "Anika", "role": "Compensation & Benefits Expert", "bio": "Experte en rémunération des dirigeants, elle a structuré des packages C level dans 20 pays. Spécialiste des vehicles d'equity internationaux."},
    {"name": "Diego", "role": "Board Member & Governance Advisor", "bio": "Administrateur indépendant dans 5 conseils, il forme les dirigeants à la culture du board et aux bonnes pratiques de gouvernance."},
]

# 15 sujets d'articles (tous différents des 14 existants)
ARTICLES_15 = [
    {"slug": "transformation-digitale-dg-2026", "title": "La transformation digitale vue par un DG : 5 pièges à éviter", "subtitle": "Pourquoi 70% des transformations digitales échouent et comment un DG peut inverser la tendance", "category": "Stratégie", "tags": ["transformation digitale", "DG", "PIA", "change management", "innovation"], "author_idx": 12, "date": "2026-04-19", "img_prompt": "Digital transformation concept, CEO leading technology change, circuit board pattern overlay on boardroom, modern blue tones"},
    {"slug": "imposter-syndrome-dirigeants", "title": "Le syndrome de l'imposteur chez les dirigeants : le tabou qui coûte cher", "subtitle": "60% des DG et CEO vivent avec le sentiment de ne pas mériter leur poste. Voici comment le transformer en force.", "category": "Transition", "tags": ["imposteur", "psychologie", "confiance", "leadership", "dirigeant"], "author_idx": 1, "date": "2026-04-12", "img_prompt": "Executive looking in mirror, reflection shows doubt but also strength, psychological concept, dramatic lighting"},
    {"slug": "réseautage-dirigeants-international", "title": "Construire un réseau international de dirigeants : la méthode en 6 étapes", "subtitle": "Pourquoi votre réseau local ne suffit plus et comment bâtir une présence mondiale", "category": "Réseau & Chasseurs", "tags": ["réseau", "international", "networking", "réseautage", "global"], "author_idx": 9, "date": "2026-04-05", "img_prompt": "Global executive network, world map connections, diverse professionals shaking hands across continents, blue and gold"},
    {"slug": "crise-communication-dirigeant", "title": "Communication de crise pour dirigeants : garder le cap quand tout s'effondre", "subtitle": "Les 7 principes de communication que tout DG doit maîtriser avant la prochaine crise", "category": "Stratégie", "tags": ["crise", "communication", "leadership", "réputation", "DG"], "author_idx": 10, "date": "2026-03-29", "img_prompt": "CEO in crisis management mode, press conference, serious expression, dramatic newsroom lighting, editorial"},
    {"slug": "delegation-art-dirigeant", "title": "L'art de la délégation : pourquoi les DG qui tout contrôlent échouent", "subtitle": "La délégation n'est pas un abandon, c'est un acte stratégique. Voici comment déléguer sans perdre le contrôle.", "category": "Stratégie", "tags": ["délégation", "management", "leadership", "efficacité", "DG"], "author_idx": 0, "date": "2026-03-22", "img_prompt": "Executive delegating tasks to team, chess pieces being moved, strategic delegation concept, warm tones"},
    {"slug": "package-dirigeant-international", "title": "Comparatif des packages de dirigeants : France, UK, USA, Singapour", "subtitle": "Où êtes vous le mieux payé ? Analyse détaillée des structures de rémunération C level dans 4 marchés", "category": "Négociation & Package", "tags": ["package", "international", "comparatif", "rémunération", "expatriation"], "author_idx": 13, "date": "2026-03-15", "img_prompt": "International compensation comparison, 4 country flags with financial charts, world map, premium business style"},
    {"slug": "lettre-motivation-dirigeant-morte", "title": "La lettre de motivation est morte : ce qui la remplace en 2026", "subtitle": "Pourquoi aucun DG ne lit les lettres de motivation et ce qu'il faut envoyer à la place", "category": "CV & Personal Branding", "tags": ["lettre motivation", "pitch", "personal branding", "candidature", "rédaction"], "author_idx": 5, "date": "2026-03-08", "img_prompt": "Old cover letter being replaced by modern pitch deck, transformation concept, split screen old vs new, editorial"},
    {"slug": "emotional-intelligence-comex", "title": "L'intelligence émotionnelle au Comex : l'avantage concurrentiel invisible", "subtitle": "Les DG avec un QE élevé surpassent ceux avec un QI élevé. Voici comment développer cette compétence critique.", "category": "Stratégie", "tags": ["intelligence émotionnelle", "QE", "Comex", "leadership", "soft skills"], "author_idx": 1, "date": "2026-03-01", "img_prompt": "Emotional intelligence in leadership, brain with heart, executive connecting with team, warm empathetic tones"},
    {"slug": "exit-strategy-dirigeant-fondateur", "title": "Préparer son exit de dirigeant : quand et comment partir", "subtitle": "Partir au bon moment est aussi important que d'arriver au bon moment. Voici la méthode.", "category": "Transition", "tags": ["exit", "départ", "succession", "transition", "dirigeant"], "author_idx": 10, "date": "2026-02-22", "img_prompt": "Executive exit strategy, leader walking away from building into sunset, new chapter concept, golden hour"},
    {"slug": "ma-fusion-acquisition-dirigeant", "title": "Mener une fusion acquisition en tant que DG : les 10 leçons d'un survivant", "subtitle": "70% des fusions échouent. Voici ce qui fait la différence entre une fusion réussie et un désastre.", "category": "Stratégie", "tags": ["M&A", "fusion", "acquisition", "intégration", "DG"], "author_idx": 6, "date": "2026-02-15", "img_prompt": "Corporate merger concept, two company buildings merging, puzzle pieces fitting together, business editorial"},
    {"slug": "culture-entreprise-transformation", "title": "Transformer une culture d'entreprise en 18 mois : mission impossible ?", "subtitle": "Un DG peut il vraiment changer une culture ? Analyse d'une transformation réussie.", "category": "Stratégie", "tags": ["culture", "transformation", "changement", "management", "DG"], "author_idx": 7, "date": "2026-02-08", "img_prompt": "Organizational culture transformation, diverse team collaborating, before and after concept, green growth"},
    {"slug": "préparation-retirement-dirigeant", "title": "Préparer sa retraite de dirigeant : le guide financier et psychologique", "subtitle": "Le passage de DG à la retraite est une transition majeure. Voici comment la préparer 5 ans à l'avance.", "category": "Transition", "tags": ["retraite", "finances", "transition", "psychologie", "dirigeant"], "author_idx": 4, "date": "2026-02-01", "img_prompt": "Executive retirement planning, calm leader looking at horizon, transition to new life, peaceful golden tones"},
    {"slug": "entretien-annuel-evaluation-dg", "title": "Votre évaluation annuelle de DG : comment la préparer et la retourner à votre avantage", "subtitle": "L'évaluation du DG par le board est un moment critique. Voici comment la maîtriser.", "category": "Entretien", "tags": ["évaluation", "board", "KPI", "performance", "DG"], "author_idx": 14, "date": "2026-01-25", "img_prompt": "Executive annual review by board, presentation of results, charts and graphs, serious professional setting"},
    {"slug": "burnout-dirigeant-signes-solutions", "title": "Le burnout du dirigeant : 8 signes d'alerte que personne n'ose voir", "subtitle": "Les DG ne craquent pas visiblement. Ils s'éteignent progressivement. Voici les signes à surveiller.", "category": "Transition", "tags": ["burnout", "santé", "bien-être", "stress", "dirigeant"], "author_idx": 11, "date": "2026-01-18", "img_prompt": "Executive burnout concept, leader sitting alone in dark office, exhaustion, dramatic shadows, editorial photography"},
    {"slug": "rémunération-variable-dirigeant", "title": "Le variable du dirigeant : au delà du bonus annuel", "subtitle": "LSTI, deferred compensation, phantom shares : les outils de rémunération variable que tout DG doit connaître", "category": "Négociation & Package", "tags": ["variable", "LTI", "deferred", "phantom shares", "rémunération"], "author_idx": 13, "date": "2026-01-11", "img_prompt": "Executive compensation structure, financial charts, golden coins and growth graph, premium dark green tones"},
]

print(f"15 articles définis avec {len(AUTHORS_15)} auteurs internationaux")
for a in AUTHORS_15:
    print(f"  {a['name']} — {a['role']}")
